print ("Welcome to the UCALC Chatbot System!")
print ("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓")
print ("▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓ ▓")
print ("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓")
print ("▓ ▓                               ▓ ▓")
print ("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓")
print ("Version 1.0 December test release A  ")
more1 = input("Press [ENTER] key to continue! ")
print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
print ("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓")
print ("▓                                      ▓")
print ("▓ Talk with famous people from history ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓                                      ▓")
print ("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓")
more1 = input("Press [ENTER] key to continue! ")
print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
print ("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓")
print ("▓                                        ▓")
print ("▓ Join groups and see how their opinions ▓")
print ("▓ Vary                                   ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓                                        ▓")
print ("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓")
more1 = input("Press [ENTER] key to continue! ")
print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
noMore = input("Press [ENTER] key to get started")