print ("The periodic table of elements")
print (" ")
enterToEnter = input("Press [ENTER] key to start")
loopForever = int(1)
while (loopForever == 1):
	print ("============================================================================\\")
	print ("Note: Table ID is the atomic number | Periodic table tool for UCALC V0.8    |")
	print ("============================================================================|")
	print ("| | 01  02  03  04  05  06  07  08  09  10  11  12  13  14  15  16  17  18  |")
	print ("                                                                            |")
	print (" 1  H   [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] HE  |")
	print ("    1                                                                   2   |")
	print ("                                                                            |")
	print (" 2 LI   BE  [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] B   C   N   O   F   NE  |")
	print ("   3    4                                           5   6   7   8   9   10  |")
	print ("                                                                            |")
	print (" 3 NA   MG  [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] AL  Si  P   S   CL  AR  |")
	print ("   11   12                                          13  14  15  16  17  18  |")
	print ("                                                                            |")
	print (" 4 K    CA  SC  Ti  V   CR  Mn  Fe  Co  Ni  Cu  Zn  Ga  Ge  As  Se  Br  Kr  |")
	print ("   19   20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  |")
	print ("                                                                            |")
	print (" 5 RB   SR  Y   Zr  Nb  Mo  Tc  Ru  Rh  Pd  Ag  Cd  In  Sn  Sb  Te  I   Xe  |")
	print ("   37   38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  |")
	print ("                                                                            |")
	print (" 6 CS   BA  LA  Hf  Ta  W   Re  Os  Ir  Pt  Au  Hg  Tl  Pb  Bi  Po  At  Rn  |")
	print ("   55   56  57  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  |")
	print ("                                                                            |")
	print (" 7 FR   RA  AC  RF  DB  SG  BH  HS  MT  DS  RG  CN  NH  FL  MC  LV  TS  OG  |")
	print ("   87   88  89  104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 |")
	print ("                                                                            |")
	print (" * [x]  [x] [x] Ce  Pr  Nd  Pm  Sm  Eu  Gd  Tb  Dy  Ho  Er  Tm  Yb  Lu      |")
	print ("                58  59  60  61  62  63  64  65  66  67  68  69  70  71      |")
	print ("                                                                            |")
	print (" * [x]  [x] [x] Th  Pa  U   Np  Pu  Am  Cm  Bk  Cf  Es  Fm  Md  No  Lr      |")
	print ("                90  91  92  93  94  95  96  97  98  99  100 101 102 103     |")
	print ("                                                                            |")
	print ("============================================================================|")
	print ("| 118 elements | Periodic Table Of Elements December 2018 edition | TABLE   |")
	print ("============================================================================/")
	print ("Type in an ID to start, either the number or the atomic symbol (example: FE)")
	print ("Type 'exit' to quit")
	PTOECon = str(input(">> "))
	if (PTOECon == "h" or PTOECon == "H" or PTOECon == "1"):
		print ("[H]")
		print ("Hydrogen")
		print ("Table ID: 1")
		print ("Excerpt from https://www.wikipedia.org/wiki/Hydrogen")
		print ("Hydrogen is a chemical element with symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element on the periodic table. Its monatomic form (H) is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass.[7][note 1] Non-remnant stars are mainly composed of hydrogen in the plasma state. The most common isotope of hydrogen, termed protium (name rarely used, symbol 1H), has one proton and no neutrons. ")
	if (PTOECon == "he" or PTOECon == "HE" or PTOECon == "He" or PTOECon == "2"):
		print ("[HE]")
		print ("Helium")
		print ("Table ID: 2")
		print ("Excerpt from https://www.wikipedia.org/wiki/Helium")
		print ("Helium (from Greek: ἥλιος, translit. Helios, lit. 'Sun') is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table. Its boiling point is the lowest among all the elements. After hydrogen, helium is the second lightest and second most abundant element in the observable universe, being present at about 24% of the total elemental mass, which is more than 12 times the mass of all the heavier elements combined. Its abundance is similar to this figure in the Sun and in Jupiter. This is due to the very high nuclear binding energy (per nucleon) of helium-4 with respect to the next three elements after helium. This helium-4 binding energy also accounts for why it is a product of both nuclear fusion and radioactive decay. Most helium in the universe is helium-4, the vast majority of which was formed during the Big Bang. Large amounts of new helium are being created by nuclear fusion of hydrogen in stars. ")
	if (PTOECon == "li" or PTOECon == "LI" or PTOECon == "Li" or PTOECon == "3"):
		print ("[LI]")
		print ("Lithium")
		print ("Table ID: 3")
		print ("Excerpt from https://www.wikipedia.org/wiki/Lithium")
		print ("Lithium (from Greek: λίθος, translit. lithos, lit. 'stone') is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element. Like all alkali metals, lithium is highly reactive and flammable, and is stored in mineral oil. When cut, it exhibits a metallic luster, but moist air corrodes it quickly to a dull silvery gray, then black tarnish. It never occurs freely in nature, but only in (usually ionic) compounds, such as pegmatitic minerals which were once the main source of lithium. Due to its solubility as an ion, it is present in ocean water and is commonly obtained from brines. Lithium metal is isolated electrolytically from a mixture of lithium chloride and potassium chloride. ")
	if (PTOECon == "be" or PTOECon == "BE" or PTOECon == "Be" or PTOECon == "4"):
		print ("[BE]")
		print ("Beryllium")
		print ("Table ID: 4")
		print ("Excerpt from https://www.wikipedia.org/wiki/Beryllium")
		print ("Beryllium is a chemical element with symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays. Within the cores of stars beryllium is depleted as it is fused and creates larger elements. It is a divalent element which occurs naturally only in combination with other elements in minerals. Notable gemstones which contain beryllium include beryl (aquamarine, emerald) and chrysoberyl. As a free element it is a steel-gray, strong, lightweight and brittle alkaline earth metal. ")
	if (PTOECon == "b" or PTOECon == "B" or PTOECon == "5"):
		print ("[B]")
		print ("Boron")
		print ("Table ID: 5")
		print ("Excerpt from https://www.wikipedia.org/wiki/Boron")
		print ("Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar system and in the Earth's crust.[12] Boron is concentrated on Earth by the water-solubility of its more common naturally occurring compounds, the borate minerals. These are mined industrially as evaporites, such as borax and kernite. The largest known boron deposits are in Turkey, the largest producer of boron minerals. ")
	if (PTOECon == "exit" or PTOECon == "Exit" or PTOECon == "EXIT"):
		print ("Sorry, but the exit funciton is unavailable due to a forever loop. To exit, manually close the program")
noMore = input("Press [ENTER] key to exit")
'''
comments
'''
# The whole program got overwritten at 3:58 pm due to Notepad++ experiencing an error. It has infuriated me, since I hurt my back really bad making the program and now I have to completely redo items
# the recovery process is going along well. I have the table all finished back up again, now time for definitions to be added 1/50 out of 118 so far. - Sean Patrick Myrick @ 4:57 pm on December 29th 2018
# Adding in the elements isn't hard to do, it is very easy, the part that makes it take longer is the process. 