print ("The periodic table of elements")
print (" ")
enterToEnter = input("Press [ENTER] key to start")
loopForever = int(1)
while (loopForever == 1):
	print ("============================================================================\\")
	print ("Note: Table ID is the atomic number | Periodic table tool for UCALC V0.6    |")
	print ("============================================================================|")
	print ("| | 01  02  03  04  05  06  07  08  09  10  11  12  13  14  15  16  17  18  |")
	print ("                                                                            |")
	print (" 1  H   [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] HE  |")
	print ("    1                                                                   2   |")
	print ("                                                                            |")
	print (" 2 LI   BE  [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] B   C   N   O   F   NE  |")
	print ("   3    4                                           5   6   7   8   9   10  |")
	print ("                                                                            |")
	print (" 3 NA   MG  [x] [x] [x] [x] [x] [x] [x] [x] [x] [x] AL  Si  P   S   CL  AR  |")
	print ("   11   12                                          13  14  15  16  17  18  |")
	print ("                                                                            |")
	print (" 4 K    CA  SC  Ti  V   CR  Mn  Fe  Co  Ni  Cu  Zn  Ga  Ge  As  Se  Br  Kr  |")
	print ("   19   20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  |")
	print ("                                                                            |")
	print (" 5 RB   SR  Y   Zr  Nb  Mo  Tc  Ru  Rh  Pd  Ag  Cd  In  Sn  Sb  Te  I   Xe  |")
	print ("   37   38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  |")
	print ("                                                                            |")
	print (" 6 CS   BA  LA  Hf  Ta  W   Re  Os  Ir  Pt  Au  Hg  Tl  Pb  Bi  Po  At  Rn  |")
	print ("   55   56  57  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  |")
	print ("                                                                            |")
	print (" 7 FR   RA  AC  RF  DB  SG  BH  HS  MT  DS  RG  CN  NH  FL  MC  LV  TS  OG  |")
	print ("   87   88  89  104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 |")
	print ("
	print ("============================================================================")
	print ("| 118 elements | Periodic Table Of Elements December 2018 edition | TABLE  |")
	print ("============================================================================")
	print ("Type in an ID to start, either the number or the atomic symbol (example: FE)")
	print ("Type 'exit' to quit")
	PTOECon = str(input(">> "))
	if (PTOECon == "h" or PTOECon == "H" or PTOECon == "1"):
		print ("[H]")
		print ("Hydrogen")
		print ("Table ID: 1")
		print ("Excerpt from https://www.wikipedia.org/wiki/Hydrogen")
		print ("Hydrogen is a chemical element with symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element on the periodic table. Its monatomic form (H) is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass.[7][note 1] Non-remnant stars are mainly composed of hydrogen in the plasma state. The most common isotope of hydrogen, termed protium (name rarely used, symbol 1H), has one proton and no neutrons. ")
print (" ")

# The whole program got overwritten at 3:58 pm due to Notepad++ experiencing an error. It has infuriated me, since I hurt my back really bad making the program and now I have to completely redo items
