		if calcIDSes == 30:
					print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
					print ("Addition (with decimals)")
					add1dec1 = float(input("Enter number 1: "))
					add2dec2 = float(input("Enter number 2: "))
					curanswer = (add1dec1 + add2dec2)
					print ("The current answer is: " + str(curanswer))
					add3dec3 = float(input("Enter number 3: "))
					curanswer = (add1dec1 + add2dec2 + add3dec3)
					print ("The current answer is: " + str(curanswer)) 
					bloat1 = input("| FAIL! SETUP RESTARTING (we can't fix the bug right now, we are porting features in. Stabilizing later, my bad)")