			if WikIDSelect == 30003:
				print ("Superstitious numbers")
				print ("\nUnlucky 13")
				print ("Excerpt from https://www.wikipedia.org/13_(number_")
				print ("The number 13 is considered an unlucky number in some countries.[11] The end of the Mayan calendar's 13th Baktun was superstitiously feared as a harbinger of the apocalyptic 2012 phenomenon.[12] Fear of the number 13 has a specifically recognized phobia, Triskaidekaphobia, a word coined in 1911. The superstitious sufferers of triskaidekaphobia try to avoid bad luck by keeping away from anything numbered or labelled thirteen. As a result, companies and manufacturers use another way of numbering or labelling to avoid the number, with hotels and tall buildings being conspicuous examples (thirteenth floor).[13] It is also considered unlucky to have thirteen guests at a table. Friday the 13th has been considered an unlucky day.[11]")
				print ("There are a number of theories as to why the number thirteen became associated with bad luck, but none of them have been ")
				print ("accepted as likely.[11]")
				print ("The Last Supper: At Jesus Christ's last supper, there were thirteen people around the table, counting Christ and the twelve ")
				print ("apostles. Some believe this is unlucky because one of those thirteen, Judas Iscariot, was the betrayer of Jesus Christ. From ")
				print ("the 1890s, a number of English language sources relate the ''unlucky'' thirteen to an idea that at the Last Supper, Judas, the") 
				print ("disciple who betrayed Jesus, was the 13th to sit at the table.[14]")
				print ("Knights Templar: On Friday 13 October 1307, King Philip IV of France ordered the arrest of the Knights Templar,[11] and most") 
				print ("of the knights were tortured and killed.")
				print ("Full Moons: A year with 13 full moons instead of 12 posed problems for the monks in charge of the calendars. ")
				print ("This was considered a very unfortunate circumstance, especially by the monks who had charge of the calendar of thirteen ")
				print ("months for that year, and it upset the regular arrangement of church festivals. For this reason thirteen came to be considered")
				print ("an unlucky number.[15] However, a typical century has about 37 years that have 13 full moons, compared to 63 years with 12 full") 
				print ("moons, and typically every third or fourth year has 13 full moons.[16]")
				print ("A Repressed Lunar Cult: In ancient cultures, the number 13 represented femininity, because it corresponded to the number of lunar ")
				print ("(menstrual) cycles in a year (13 x 28 = 364 days). The theory is that, as the solar calendar triumphed over the lunar, the ")
				print ("number thirteen became anathema.[11][17]")
				print ("Hammurabi's Code: There is a myth that the earliest reference to thirteen being unlucky or evil is in the Babylonian Code of ")
				print ("Hammurabi (circa 1780 BC), where the thirteenth law is said to be omitted. In fact, the original Code of Hammurabi has no ")
				print ("numeration. The translation by L.W. King (1910), edited by Richard Hooker, omitted one article: If the seller have gone to ")
				print ("(his) fate (i. e., have died), the purchaser shall recover damages in said case fivefold from the estate of the seller.") 
				print ("Other translations of the Code of Hammurabi, for example the translation by Robert Francis Harper, include the 13th ")
				print ("article.[18]")
				print ("\nLucky 13")
				print ("Excerpt from https://www.wikipedia.org/13_(number)_")
				print ("In some countries, such as Italy, 13 is considered a lucky number.[19] The expression fare tredici (''to do 13'') means hit the jackpot.") 
				print ("17 is considered an unlucky number instead.[20]")
				print ("\n666")
				print ("Excerpt from https://www.wikipedia.org/666_(number)_")
				print ("Number of the Beast")
				print ("666 is often associated with the devil.")
				print ("Main article: Number of the Beast")
				print ("In the Textus Receptus manuscripts of the New Testament, the Book of Revelation (13:17–18) cryptically asserts 666 to be ''man's number'' ")
				print ("or ''the number of a man'' (depending on how the text is translated) associated with the Beast, an antagonistic creature that") 
				print ("appears briefly about two-thirds into the apocalyptic vision. Some manuscripts of the original Greek use the symbols χξϛ ")
				print ("chi xi stigma (or χξϝ with a digamma), while other manuscripts spell out the number in words.")
				print ("In modern popular culture, 666 has become one of the most widely recognized symbols for the Antichrist or, alternatively, the devil. The")
				print ("number 666 is purportedly used to invoke Satan. Earnest references to the number occur both among apocalypticist Christian ")
				print ("groups and in explicitly anti-Christian subcultures. References in contemporary Western art or literature are, more ")
				print ("likely than not, intentional references to the Beast symbolism. Such popular references are therefore too numerous to list.")
				print ("It is common to see the symbolic role of the integer 666 transferred to the digit sequence 6-6-6. Some people take the Satanic associations") 
				print ("of 666 so seriously that they actively avoid things related to 666 or the digits 6-6-6. This is known as ")
				print ("hexakosioihexekontahexaphobia.")
				print ("The number is cited as 616 in some early biblical manuscripts, the earliest known instance being in Papyrus 115.[3][4]")
				print ("Other occurrences")
				print ("In the Bible, 666 is the number of talents of gold Solomon collected each year (see 1 Kings 10:14, 2 Chronicles 9:13 and also in Ezra 2:13).")
				print ("In the Bible, 666 is the number of Adonikam's descendants who return to Jerusalem and Judah from the Babylonian exile (see Ezra 2:13).")
				print ("In the Bible, there may be a latent reference to 666 in the name of the great sixth-century BC king of Babylon. Commonly spelled ")
				print ("Nebuchadnezzar, transliterating from the Book of Daniel, the name is Nebuchadrezzar or Nebuchadrezzur in the Book of ")
				print ("Jeremiah (see Jeremiah 49:28–30). The number of each name can be calculated, since Hebrew letters double as numbers ")
				print ("(see Gematria, Hebrew numerals). Nebuchadrezzar is 663, and Nebuchadrezzur, 669. Midway between the two variants is 666. ")
				print ("If the mysteries of Jeremiah are to be related to those of Revelation, Nebuchadrezzar, who came (though bidden by God) to ")
				print ("crush God's people, may prefigure the end-times beast.[5]")
				print ("Using gematria, Neron Caesar transliterated from Greek into Hebrew produces the number 666. The Latin spelling of ''Nero Caesar''") 
				print ("transliterated into Hebrew produces the number 616. Thus, in the Bible, 666 may have been a coded reference to Nero, the ")
				print ("Roman Emperor from 55 to 68 AD.[6]")