WikIDSelect = int(20017)
if WikIDSelect == 20017:
	if WikIDSelect == 20017:
		if WikIDSelect == 20017:
			if WikIDSelect == 20017:
				print (" ")
				print ("In computer architecture, 256-bit integers, memory addresses, or other data units are those that are 256 bits (32 octets) ")
				print ("wide. Also, 256-bit CPU and ALU architectures are those that are based on registers, address buses, or data buses of that size.")
				print (" ")
				print ("There are currently no mainstream general-purpose processors built to operate on 256-bit integers or addresses, though a ")
				print ("number of processors do operate on 256-bit data. CPUs feature SIMD instruction sets (Advanced Vector Extensions and the ")
				print ("FMA instruction set etc.) where 256-bit vector registers are used to store several smaller numbers, such as eight 32-bit ")
				print ("floating-point numbers, and a single instruction can operate on all these values in parallel. However, these processors do ")
				print ("not operate on individual numbers that are 256 binary digits in length, only their registers have the size of 256-bits. ")
				print ("Binary digits are found together in 128-bit collections.")
				more1 = input("Contents")
				print (" ")
				print ("1 Uses")
				print ("2 History")
				print ("3 See also")
				print ("4 References")
				print (" ")
				more1 = input("Uses")
				print ("Laptop computer using an Efficeon processor")
				print (" ")
				print ("256 bits is a common key size for symmetric ciphers in cryptography, such as Advanced Encryption Standard.")
				print ("Modern GPU chips move data across a 256-bit memory bus.")
				print ("256-bit processors could be used for addressing directly up to 2256 bytes. Already 2128 (128-bit) would greatly exceed the") 
				print ("total data stored on Earth as of 2010, which has been estimated to be around 1.2 zettabytes (over 270 bytes).[1]")
				print ("The Efficeon processor was Transmeta's second-generation 256-bit VLIW design which employed a software engine to convert code ")
				print ("written for x86 processors to the native instruction set of the chip.[2][3]")
				print ("Increasing the word size can accelerate multiple precision mathematical libraries. Applications include cryptography.")
				print ("Researchers at the University of Cambridge use a 256-bit capability pointer, which includes capability and addressing ")
				print ("information, on their CHERI capability system.[4]")
				print (" ")
				more1 = input("History")
				print (" ")
				print ("The DARPA funded Data-Intensive Architecture (DIVA) system incorporated processor-in-memory (PIM) 5-stage pipelined 256-bit ")
				print ("datapath, complete with register file and ALU blocks in a ''WideWord'' processor in 2002.[5] ")
				noMore = input("Press [ENTER] key to exit")