print (" ")
print (" ")
print (" ____  __  __  ____    __   ____  ____  _____  _  _  ")            
print ("(  _ \\(  )(  )(  _ \\  /__\\ (_  _)(_  _)(  _  )( \\( )")             
print (" )(_) ))(__)(  )   / /(__)\\  )(   _)(_  )(_)(  )  (      ")        
print ("(____/(______)(_)\\_)(__)(__)(__) (____)(_____)(_)\\_)      ")       
print ("  ___    __    __    ___  __  __  __      __   ____  _____  ____") 
print (" / __)  /__\\  (  )  / __)(  )(  )(  )    /__\\ (_  _)(  _  )(  _ \\")
print ("( (__  /(__)\\  )(__( (__  )(__)(  )(__  /(__)\\  )(   )(_)(  )   /")
print (" \\___)(__)(__)(____)\\___)(______)(____)(__)(__)(__) (_____)(_)\\_)")
print (" ")
print (" ")
enterToEnter = input("Press [ENTER] key to start! ")
uCalcIDSes = int(68)
if (uCalcIDSes == 68):
	print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
	print ("Mode selection")
	print ("\nChoose a clock mode: ")
	print ("\n[Standard Time] (AM-PM) ID: 1")
	print ("\n[Military time] (00:00) ID: 2")
	print ("\n[Minecraft time]        ID: 3")
	print ("\n[Sim time]              ID: 4")
	print ("\n[GTA time]              ID: 5")
	print ("\n[Yandere Sim time]      ID: 6")
	enterMode1ID = str(input("Enter a clock mode ID to start: "))
	if (enterMode1ID == "1"):
		print ("Standard time selected")
		print ("\nSelect second mode")
		print ("\nReal time      ID: 1")
		print ("\nSlow motion    ID: 2")
		print ("\nTime lapse     ID: 3")
		enterMode2ID = str(input("Enter a mode ID to continue: "))
		if (enterMode2ID == "1"):
			print ("Real time selected")
			print ("\n\n\n")
			more1 = input("New sorting options available! ")
			sortOptions = str(input("| A-Z [ID: 1] | Z-A [ID: 2] | shortest to longest [ID: 3] | longest to shortest [ID: 4]"))
			if (sortOptions == "1"):
				print ("Sorting by A-Z")
				print ("\nTime unit list")
				print ("Century")
				print ("Days")
				print ("Decade")
				print ("Femtosecond")
				print ("Fortnight")
				print ("Hours")
				print ("Microseconds")
				print ("Millennium")
				print ("Milliseconds")
				print ("Minutes")
				print ("Months")
				print ("Nanoseconds")
				print ("Picoseconds")
				print ("Seconds")
				print ("Sidereal year")
				print ("Weeks")
				print ("Years")
				entUnitStr = str(input("Enter a measurement unit to continue: "))
				if (entUnitStr == "Century"):
					centuryCalc = float(0.0)
					centuryCalc = float(input("Enter an amount in centuries: "))
					print ("Choose a way to calculate: ")
					print ("End calculation      [ID: 0]")
					print ("Addition             [ID: 1]")
					print ("Subtraction          [ID: 2]")
					print ("Multiplication       [ID: 3]")
					print ("Division             [ID: 4]")
					print ("Modular division     [ID: 5]")
					entUnitToUnitID = str(input("Enter an ID to continue: "))
					if (entUnitToUnitID == "0"):
						dayCalc = float(centuryCalc * 36525)
						decadeCalc = float(centuryCalc * 10)
						femtosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000000)
						fortnightCalc = float(centuryCalc * 2608.929)
						hourCalc = float(centuryCalc * 876600)
						microsecondCalc = float(centuryCalc * 3155760000000000)
						millenniumCalc = float(centuryCalc * 0.1)
						millisecondCalc = float(centuryCalc * 3155760000000)
						minuteCalc = float(centuryCalc * 52596000)
						monthCalc = float(centuryCalc * 1200)
						nanosecondCalc = float(centuryCalc * 3155760000000000000)
						picosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000)
						secondCalc = float(centuryCalc * 3155760000)
						siderealYearCalc = float(centuryCalc * 99.99826)
						weekCalc = float(centuryCalc * 5217.857)
						yearCalc = float(centuryCalc * 100)
						print ("The answer is " + str(centuryCalc) + " Centuries")
						print ("This is equal to: ")
						print ("\nDays: " + str(dayCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")
					if (entUnitToUnitID == "1"):
						centuryCalc2 = float(input("Enter a number to add: "))
						centuryCount = float(centuryCalc + centuryCalc2)
						dayCalc = float(centuryCalc * 36525)
						decadeCalc = float(centuryCalc * 10)
						femtosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000000)
						fortnightCalc = float(centuryCalc * 2608.929)
						hourCalc = float(centuryCalc * 876600)
						microsecondCalc = float(centuryCalc * 3155760000000000)
						millenniumCalc = float(centuryCalc * 0.1)
						millisecondCalc = float(centuryCalc * 3155760000000)
						minuteCalc = float(centuryCalc * 52596000)
						monthCalc = float(centuryCalc * 1200)
						nanosecondCalc = float(centuryCalc * 3155760000000000000)
						picosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000)
						secondCalc = float(centuryCalc * 3155760000)
						siderealYearCalc = float(centuryCalc * 99.99826)
						weekCalc = float(centuryCalc * 5217.857)
						yearCalc = float(centuryCalc * 100)
						print ("The answer is " + str(centuryCount) + " Centuries")
						print ("This is equal to: ")
						print ("\nDays: " + str(dayCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")
					if (entUnitToUnitID == "2"):
						centuryCalc2 = float(input("Enter a number to subtract by: "))
						centuryCount = float(centuryCalc - centuryCalc2)
						dayCalc = float(centuryCalc * 36525)
						decadeCalc = float(centuryCalc * 10)
						femtosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000000)
						fortnightCalc = float(centuryCalc * 2608.929)
						hourCalc = float(centuryCalc * 876600)
						microsecondCalc = float(centuryCalc * 3155760000000000)
						millenniumCalc = float(centuryCalc * 0.1)
						millisecondCalc = float(centuryCalc * 3155760000000)
						minuteCalc = float(centuryCalc * 52596000)
						monthCalc = float(centuryCalc * 1200)
						nanosecondCalc = float(centuryCalc * 3155760000000000000)
						picosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000)
						secondCalc = float(centuryCalc * 3155760000)
						siderealYearCalc = float(centuryCalc * 99.99826)
						weekCalc = float(centuryCalc * 5217.857)
						yearCalc = float(centuryCalc * 100)
						print ("The answer is " + str(centuryCount) + " Centuries")
						print ("This is equal to: ")
						print ("\nDays: " + str(dayCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")
					if (entUnitToUnitID == "3"):
						centuryCalc2 = float(input("Enter a number to multiply by: "))
						centuryCount = float(centuryCalc * centuryCalc2)
						dayCalc = float(centuryCalc * 36525)
						decadeCalc = float(centuryCalc * 10)
						femtosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000000)
						fortnightCalc = float(centuryCalc * 2608.929)
						hourCalc = float(centuryCalc * 876600)
						microsecondCalc = float(centuryCalc * 3155760000000000)
						millenniumCalc = float(centuryCalc * 0.1)
						millisecondCalc = float(centuryCalc * 3155760000000)
						minuteCalc = float(centuryCalc * 52596000)
						monthCalc = float(centuryCalc * 1200)
						nanosecondCalc = float(centuryCalc * 3155760000000000000)
						picosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000)
						secondCalc = float(centuryCalc * 3155760000)
						siderealYearCalc = float(centuryCalc * 99.99826)
						weekCalc = float(centuryCalc * 5217.857)
						yearCalc = float(centuryCalc * 100)
						print ("The answer is " + str(centuryCount) + " Centuries")
						print ("This is equal to: ")
						print ("\nDays: " + str(dayCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")
					if (entUnitToUnitID == "4"):
						centuryCalc2 = float(input("Enter a number to divide by: "))
						centuryCount = float(centuryCalc / centuryCalc2)
						dayCalc = float(centuryCalc * 36525)
						decadeCalc = float(centuryCalc * 10)
						femtosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000000)
						fortnightCalc = float(centuryCalc * 2608.929)
						hourCalc = float(centuryCalc * 876600)
						microsecondCalc = float(centuryCalc * 3155760000000000)
						millenniumCalc = float(centuryCalc * 0.1)
						millisecondCalc = float(centuryCalc * 3155760000000)
						minuteCalc = float(centuryCalc * 52596000)
						monthCalc = float(centuryCalc * 1200)
						nanosecondCalc = float(centuryCalc * 3155760000000000000)
						picosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000)
						secondCalc = float(centuryCalc * 3155760000)
						siderealYearCalc = float(centuryCalc * 99.99826)
						weekCalc = float(centuryCalc * 5217.857)
						yearCalc = float(centuryCalc * 100)
						print ("The answer is " + str(centuryCount) + " Centuries")
						print ("This is equal to: ")
						print ("\nDays: " + str(dayCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")
					if (entUnitToUnitID == "5"):
						centuryCalc2 = float(input("Enter a number to mod: "))
						centuryCount = float(centuryCalc % centuryCalc2)
						dayCalc = float(centuryCalc * 36525)
						decadeCalc = float(centuryCalc * 10)
						femtosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000000)
						fortnightCalc = float(centuryCalc * 2608.929)
						hourCalc = float(centuryCalc * 876600)
						microsecondCalc = float(centuryCalc * 3155760000000000)
						millenniumCalc = float(centuryCalc * 0.1)
						millisecondCalc = float(centuryCalc * 3155760000000)
						minuteCalc = float(centuryCalc * 52596000)
						monthCalc = float(centuryCalc * 1200)
						nanosecondCalc = float(centuryCalc * 3155760000000000000)
						picosecondCalc = float((centuryCalc / 0.0001) * 315576000000000000)
						secondCalc = float(centuryCalc * 3155760000)
						siderealYearCalc = float(centuryCalc * 99.99826)
						weekCalc = float(centuryCalc * 5217.857)
						yearCalc = float(centuryCalc * 100)
						print ("The answer is " + str(centuryCount) + " Centuries")
						print ("This is equal to: ")
						print ("\nDays: " + str(dayCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")
				if (entUnitStr == "Day"):
					dayCalc = float(0.0)
					dayCalc = float(input("Enter an amount in days: "))
					print ("Choose a way to calculate: ")
					print ("End calculation      [ID: 0]")
					print ("Addition             [ID: 1]")
					print ("Subtraction          [ID: 2]")
					print ("Multiplication       [ID: 3]")
					print ("Division             [ID: 4]")
					print ("Modular division     [ID: 5]")
					entUnitToUnitID = str(input("Enter an ID to continue: "))
					if (entUnitToUnitID == "0"):
						centuryCalc = float(dayCalc * 0.00002737851)
						decadeCalc = float(dayCalc * 0.0002737851)
						femtosecondCalc = float(dayCalc * 86400000000000000000)
						fortnightCalc = float(dayCalc * 0.07142857)
						hourCalc = float(dayCalc * 24)
						microsecondCalc = float(dayCalc * 86400000000)
						millenniumCalc = float(dayCalc * 0.000002737851)
						millisecondCalc = float(dayCalc * 86400000)
						minuteCalc = float(dayCalc * 1440)
						monthCalc = float(dayCalc * 0.03285421)
						nanosecondCalc = float(dayCalc * 86400000000000)
						picosecondCalc = float(dayCalc * 86400000000000000)
						secondCalc = float(dayCalc * 86400)
						siderealYearCalc = float(dayCalc * 0.002737803)
						weekCalc = float(dayCalc * 0.1428571)
						yearCalc = float(dayCalc * 0.002737851)
						print ("The answer is " + str(dayCalc) + " days")
						print ("This is equal to: ")
						print ("\nCenturies: " + str(centuryCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")
					if (entUnitToUnitID == "1"):
						dayCalc2 = float(input("Enter a number to add: "))
						dayCount = float(dayCalc + dayCalc2)
						centuryCalc = float(dayCalc * 0.00002737851)
						decadeCalc = float(dayCalc * 0.0002737851)
						femtosecondCalc = float(dayCalc * 86400000000000000000)
						fortnightCalc = float(dayCalc * 0.07142857)
						hourCalc = float(dayCalc * 24)
						microsecondCalc = float(dayCalc * 86400000000)
						millenniumCalc = float(dayCalc * 0.000002737851)
						millisecondCalc = float(dayCalc * 86400000)
						minuteCalc = float(dayCalc * 1440)
						monthCalc = float(dayCalc * 0.03285421)
						nanosecondCalc = float(dayCalc * 86400000000000)
						picosecondCalc = float(dayCalc * 86400000000000000)
						secondCalc = float(dayCalc * 86400)
						siderealYearCalc = float(dayCalc * 0.002737803)
						weekCalc = float(dayCalc * 0.1428571)
						yearCalc = float(dayCalc * 0.002737851)
						print ("The answer is " + str(dayCount) + " days")
						print ("This is equal to: ")
						print ("\nCenturies: " + str(centuryCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")
					if (entUnitToUnitID == "1"):
						dayCalc2 = float(input("Enter a number to add: "))
						dayCount = float(dayCalc + dayCalc2)
						centuryCalc = float(dayCalc * 0.00002737851)
						decadeCalc = float(dayCalc * 0.0002737851)
						femtosecondCalc = float(dayCalc * 86400000000000000000)
						fortnightCalc = float(dayCalc * 0.07142857)
						hourCalc = float(dayCalc * 24)
						microsecondCalc = float(dayCalc * 86400000000)
						millenniumCalc = float(dayCalc * 0.000002737851)
						millisecondCalc = float(dayCalc * 86400000)
						minuteCalc = float(dayCalc * 1440)
						monthCalc = float(dayCalc * 0.03285421)
						nanosecondCalc = float(dayCalc * 86400000000000)
						picosecondCalc = float(dayCalc * 86400000000000000)
						secondCalc = float(dayCalc * 86400)
						siderealYearCalc = float(dayCalc * 0.002737803)
						weekCalc = float(dayCalc * 0.1428571)
						yearCalc = float(dayCalc * 0.002737851)
						print ("The answer is " + str(dayCount) + " days")
						print ("This is equal to: ")
						print ("\nCenturies: " + str(centuryCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")
					if (entUnitToUnitID == "2"):
						dayCalc2 = float(input("Enter a number to subtract from: "))
						dayCount = float(dayCalc - dayCalc2)
						centuryCalc = float(dayCalc * 0.00002737851)
						decadeCalc = float(dayCalc * 0.0002737851)
						femtosecondCalc = float(dayCalc * 86400000000000000000)
						fortnightCalc = float(dayCalc * 0.07142857)
						hourCalc = float(dayCalc * 24)
						microsecondCalc = float(dayCalc * 86400000000)
						millenniumCalc = float(dayCalc * 0.000002737851)
						millisecondCalc = float(dayCalc * 86400000)
						minuteCalc = float(dayCalc * 1440)
						monthCalc = float(dayCalc * 0.03285421)
						nanosecondCalc = float(dayCalc * 86400000000000)
						picosecondCalc = float(dayCalc * 86400000000000000)
						secondCalc = float(dayCalc * 86400)
						siderealYearCalc = float(dayCalc * 0.002737803)
						weekCalc = float(dayCalc * 0.1428571)
						yearCalc = float(dayCalc * 0.002737851)
						print ("The answer is " + str(dayCount) + " days")
						print ("This is equal to: ")
						print ("\nCenturies: " + str(centuryCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")
					if (entUnitToUnitID == "3"):
						dayCalc2 = float(input("Enter a number to multiply by: "))
						dayCount = float(dayCalc * dayCalc2)
						centuryCalc = float(dayCalc * 0.00002737851)
						decadeCalc = float(dayCalc * 0.0002737851)
						femtosecondCalc = float(dayCalc * 86400000000000000000)
						fortnightCalc = float(dayCalc * 0.07142857)
						hourCalc = float(dayCalc * 24)
						microsecondCalc = float(dayCalc * 86400000000)
						millenniumCalc = float(dayCalc * 0.000002737851)
						millisecondCalc = float(dayCalc * 86400000)
						minuteCalc = float(dayCalc * 1440)
						monthCalc = float(dayCalc * 0.03285421)
						nanosecondCalc = float(dayCalc * 86400000000000)
						picosecondCalc = float(dayCalc * 86400000000000000)
						secondCalc = float(dayCalc * 86400)
						siderealYearCalc = float(dayCalc * 0.002737803)
						weekCalc = float(dayCalc * 0.1428571)
						yearCalc = float(dayCalc * 0.002737851)
						print ("The answer is " + str(dayCount) + " days")
						print ("This is equal to: ")
						print ("\nCenturies: " + str(centuryCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")		
					if (entUnitToUnitID == "4"):
						dayCalc2 = float(input("Enter a number to divide by: "))
						dayCount = float(dayCalc / dayCalc2)
						centuryCalc = float(dayCalc * 0.00002737851)
						decadeCalc = float(dayCalc * 0.0002737851)
						femtosecondCalc = float(dayCalc * 86400000000000000000)
						fortnightCalc = float(dayCalc * 0.07142857)
						hourCalc = float(dayCalc * 24)
						microsecondCalc = float(dayCalc * 86400000000)
						millenniumCalc = float(dayCalc * 0.000002737851)
						millisecondCalc = float(dayCalc * 86400000)
						minuteCalc = float(dayCalc * 1440)
						monthCalc = float(dayCalc * 0.03285421)
						nanosecondCalc = float(dayCalc * 86400000000000)
						picosecondCalc = float(dayCalc * 86400000000000000)
						secondCalc = float(dayCalc * 86400)
						siderealYearCalc = float(dayCalc * 0.002737803)
						weekCalc = float(dayCalc * 0.1428571)
						yearCalc = float(dayCalc * 0.002737851)
						print ("The answer is " + str(dayCount) + " days")
						print ("This is equal to: ")
						print ("\nCenturies: " + str(centuryCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")	
					if (entUnitToUnitID == "5"):
						dayCalc2 = float(input("Enter a number to mod: "))
						dayCount = float(dayCalc % dayCalc2)
						centuryCalc = float(dayCalc * 0.00002737851)
						decadeCalc = float(dayCalc * 0.0002737851)
						femtosecondCalc = float(dayCalc * 86400000000000000000)
						fortnightCalc = float(dayCalc * 0.07142857)
						hourCalc = float(dayCalc * 24)
						microsecondCalc = float(dayCalc * 86400000000)
						millenniumCalc = float(dayCalc * 0.000002737851)
						millisecondCalc = float(dayCalc * 86400000)
						minuteCalc = float(dayCalc * 1440)
						monthCalc = float(dayCalc * 0.03285421)
						nanosecondCalc = float(dayCalc * 86400000000000)
						picosecondCalc = float(dayCalc * 86400000000000000)
						secondCalc = float(dayCalc * 86400)
						siderealYearCalc = float(dayCalc * 0.002737803)
						weekCalc = float(dayCalc * 0.1428571)
						yearCalc = float(dayCalc * 0.002737851)
						print ("The answer is " + str(dayCount) + " days")
						print ("This is equal to: ")
						print ("\nCenturies: " + str(centuryCalc))
						print ("Decades: " + str(decadeCalc))
						print ("Femtoseconds: " + str(femtosecondCalc))
						print ("Fortnights: " + str(fortnightCalc))
						print ("Hours: " + str(hourCalc))
						print ("Microseconds: " + str(microsecondCalc))
						print ("Millenniums: " + str(millenniumCalc))
						print ("Milliseconds: " + str(millisecondCalc))
						print ("Minutes: " + str(minuteCalc))
						print ("Months: " + str(monthCalc))
						print ("Nanoseconds: " + str(nanosecondCalc))
						print ("Picoseconds: " + str(picosecondCalc))
						print ("Seconds: " + str(secondCalc))
						print ("Sidereal years: " + str(siderealYearCalc))
						print ("Weeks: " + str(weekCalc))
						print ("Years: " + str(yearCalc))
						noMore = input("Press [ENTER] key to exit")			
		if (enterMode2ID == "2"):
			print ("Slow motion")
			print ("\n\n\n")
			print ("Select a framerate type: ")
			print ("Frames per second")
			print ("Frames per minute")
			print ("Frames per hour")
			enterAFrameRate = str(input("Enter a framerate to begin: "))
			if (enterAFrameRate == "Frames per second"):
				print ("Slow motion in frames per second")
				print (" ")
noMore = input("Press [ENTER] key to quit")			