WikIDSelect = int(20008)
if WikIDSelect == 20008:
	if WikIDSelect == 20008:
		if WikIDSelect == 20008:
			if WikIDSelect == 20008:
				print ("In computer architecture, 24-bit integers, memory addresses, or other data units are those that are 24 bits (3 octets) ")
				print ("wide. Also, 24-bit CPU and ALU architectures are those that are based on registers, address buses, or data buses of that size.")
				print (" ")
				print ("Notable 24-bit machines include the CDC 924 – a 24-bit version of the CDC 1604, CDC lower 3000 series, SDS 930 and SDS 940, ")
				print ("the ICT 1900 series, and the Datacraft minicomputers/Harris H series.[1]")
				print (" ")
				print ("The term SWORD is sometimes used to describe a 24-bit data type with the S prefix referring to sesqui.[citation needed]")
				print (" ")
				print ("The IBM System/360, announced in 1964, was a popular computer system with 24-bit addressing and 32-bit general registers and ")
				print ("arithmetic. The early 1980s saw the first popular personal computers, including the IBM PC/AT with an Intel 80286 processor ")
				print ("using 24-bit addressing and 16-bit general registers and arithmetic, and the Apple Macintosh 128K with a Motorola 68000 ")
				print ("processor featuring 24-bit addressing and 32-bit registers.")
				print (" ")
				print ("The eZ80 is a microprocessor and microcontroller family, with 24-bit registers and therefore 24-bit linear addressing, ")
				print ("that is binary compatible with the 8/16-bit Z80.[citation needed]")
				print (" ")
				print ("The 65816 is a microprocessor and microcontroller family with 16-bit registers and 24-bit bank switched addressing. It is ")
				print ("binary compatible with the 8-bit 6502.[2]")
				print (" ")
				print ("The range of unsigned integers that can be represented in 24 bits is 0 to 16,777,215 (FFFFFF16 in hexadecimal). The range of")
				print ("signed integers that can be represented in 24 bits is −8,388,608 to 8,388,607.")
				print (" ")
				print ("Several fixed-point digital signal processors have a 24-bit data bus, selected as the basic word length because it gave the ")
				print ("system a reasonable precision for the processing audio (sound). In particular, the Motorola 56000 series has three parallel ")
				print ("24-bit data buses, one connected to each memory space: program memory, data memory X, and data memory Y.[3]")
				print (" ")
				print ("Engineering Research Associates (later merged into UNIVAC) designed a series of 24-bit drum memory machines including the ")
				print ("Atlas, its commercial version the UNIVAC 1101, the ATHENA computer, the UNIVAC 1824 guidance computer, etc. Those designers ")
				print ("selected a 24-bit word length because the Earth is roughly 40 million feet in diameter, and an intercontinental ballistic ")
				print ("missile guidance computer needs to do the Earth-centered inertial navigation calculations to an accuracy of a few feet.")
				print ("[4][not in citation given] ")
				print (" ")
				noMore = input("Press [ENTER] key to exit")