holidaypowersetup1name = str("Untitled1")
holidaypowersetup2name = str("Untitled2")
holidaypowersetup3name = str("Untitled3")
holidaypowersetup4name = str("Untitled4")
holidaypowersetup5name = str("Untitled5")
holidaypowersetup6name = str("Untitled6")
holidaypowersetup7name = str("Untitled7")
holidaypowersetup8name = str("Untitled8")
holidaypowersetup9name = str("Untitled9")
holidaypowersetup10name = str("Untitled10")
holidaypowersetup11name = str("Untitled11")
holidaypowersetup12name = str("Untitled12")
holidaypowersetup13name = str("Untitled13")
holidaypowersetup14name = str("Untitled14")
holidaypowersetup15name = str("Untitled15")
holidaypowersetup16name = str("Untitled16")
holidaypowersetup17name = str("Untitled17")
holidaypowersetup18name = str("Untitled18")
holidaypowersetup19name = str("Untitled19")
holidaypowersetup20name = str("Untitled20")
holidaypowersetup21name = str("Untitled21")
holidaypowersetup22name = str("Untitled22")
holidaypowersetup23name = str("Untitled23")
holidaypowersetup24name = str("Untitled24")
holidaypowersetup25name = str("Untitled25")
print (" ")
print (" ")
print (" ____  _____  _    _  ____  ____    ")                             
print ("(  _ \\(  _  )( \\/\\/ )( ___)(  _ \\ ")                               
print (" )___/ )(_)(  )    (  )__)  )   /      ")                          
print ("(__)  (_____)(__/\\__)(____)(_)\\_)     ")                           
print ("  ___    __    __    ___  __  __  __      __   ____  _____  ____ ")
print (" / __)  /__\\  (  )  / __)(  )(  )(  )    /__\\ (_  _)(  _  )(  _ \\")
print ("( (__  /(__)\\  )(__( (__  )(__)(  )(__  /(__)\\  )(   )(_)(  )   /")
print (" \\___)(__)(__)(____)\\___)(______)(____)(__)(__)(__) (_____)(_)\\_)")
print (" ")
enterToEnter = input("Press [ENTER] key to start!")
calcIDSes = int(67)
if calcIDSes == 67:
	loop1 = int(1)
	while loop1 == 1:
		print ("Energy calculator")
		print ("\n\n\nSelect a mode: ")
		print ("Default power\t\t\t[ID: 1]")
		print ("The default power converter")
		print ("\nHoliday power\t\t\t[ID: 2]")
		print ("Manage holiday lighting and power costs")
		print ("\nStructure power\t\t\t[ID: 3]")
		print ("Manage the power consumption and cost of an entire building")
		print ("\nMobile power\t\t\t[ID: 4]")
		print ("Manage the power consumption of other electronic devices")
		getAnID = int(input("\n\n\n[Enter an ID to start]>> "))
		if getAnID == 1:
			print ("Default power calculator")
			more1 = input("New sorting options are available!")
			sortopt = str(input("| A-Z [1] | Z-A [2] | Small to Large [3] | Large to Small [4]: "))
			if sortopt == ("1"):
				print ("Sorting from A-Z")
				print ("\n")
				print ("Exawatt")
				print ("Gigawatt")
				print ("HP")
				print ("Kilowatt")
				print ("Megawatt")
				print ("Petawatt")
				print ("Terawatt")
				print ("Watt")
				wattType = str(input("Enter a unit: "))
				if (wattType == "Exawatt"):
					exaWattCalc = float(input("Enter an amount in exawatts: "))
					print ("\n\n")
					print ("How do you want to use the units? ")
					print ("Addition [ID: 1]")
					print ("Subtraction [ID: 2]")
					print ("Multiplication [ID: 3]")
					print ("Division [ID: 4]")
					print ("Modular division [ID: 5]")
					print ("1 unit only [ID: 6]")
					unitByUnit = int(input("Enter an ID to continue: >> "))
					if unitByUnit == 1:
						exaWatt2 = float(input("Enter an exawatt amount to add: "))
						curanswer = float(exaWattCalc + exaWatt2)
						hpcalc = float(curanswer * 1341022000000000)
						wattCalc = float(curanswer * 1000000000000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float(curanswer * 1000)
						print ("The answer is " + str(curanswer) + " exawatts")
						print ("\nThis is equal to: ")
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 2:
						exaWatt2 = float(input("Enter an exawatt amount to subtract: "))
						curanswer = float(exaWattCalc - exaWatt2)
						hpcalc = float(curanswer * 1341022000000000)
						wattCalc = float(curanswer * 1000000000000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float(curanswer * 1000)
						print ("The answer is " + str(curanswer) + " exawatts")
						print ("\nThis is equal to: ")
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 3:
						exaWatt2 = float(input("Enter an exawatt amount to multiply: "))
						curanswer = float(exaWattCalc * exaWatt2)
						hpcalc = float(curanswer * 1341022000000000)
						wattCalc = float(curanswer * 1000000000000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float(curanswer * 1000)
						print ("The answer is " + str(curanswer) + " exawatts")
						print ("\nThis is equal to: ")
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 4:
						exaWatt2 = float(input("Enter an exawatt amount to divide by: "))
						curanswer = float(exaWattCalc / exaWatt2)
						hpcalc = float(curanswer * 1341022000000000)
						wattCalc = float(curanswer * 1000000000000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float(curanswer * 1000)
						print ("The answer is " + str(curanswer) + " exawatts")
						print ("\nThis is equal to: ")
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 5:
						exaWatt2 = float(input("Enter an exawatt amount to mod: "))
						curanswer = float(exaWattCalc % exaWatt2)
						hpcalc = float(curanswer * 1341022000000000)
						wattCalc = float(curanswer * 1000000000000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float(curanswer * 1000)
						print ("The answer is " + str(curanswer) + " exawatts")
						print ("\nThis is equal to: ")
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 6:
						curanswer = float(exaWattCalc)
						hpcalc = float(curanswer * 1341022000000000)
						wattCalc = float(curanswer * 1000000000000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float(curanswer * 1000)
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
				if (wattType == "Gigawatt"):
					gigaWattCalc = float(input("Enter an amount in gigawatts: "))
					print ("\n\n")
					print ("How do you want to use the units? ")
					print ("Addition [ID: 1]")
					print ("Subtraction [ID: 2]")
					print ("Multiplication [ID: 3]")
					print ("Division [ID: 4]")
					print ("Modular division [ID: 5]")
					print ("1 unit only [ID: 6]")
					unitByUnit = int(input("Enter an ID to continue: >> "))
					if unitByUnit == 1:
						gigaWatt2 = float(input("Enter a gigawatt amount to add: "))
						curanswer = float(gigaWattCalc + gigaWatt2)
						hpcalc = float(curanswer * 1341022)
						wattCalc = float(curanswer * 1000000000)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float(curanswer * 0.000000001)
						print ("The answer is " + str(curanswer) + " gigawatts")
						print ("\nThis is equal to: ")
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 2:
						gigaWatt2 = float(input("Enter a gigawatt amount to subtract: "))
						curanswer = float(gigaWattCalc - gigaWatt2)
						hpcalc = float(curanswer * 1341022)
						wattCalc = float(curanswer * 1000000000)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float(curanswer * 0.000000001)
						print ("The answer is " + str(curanswer) + " gigawatts")
						print ("\nThis is equal to: ")
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 3:
						gigaWatt2 = float(input("Enter a gigawatt amount to multiply: "))
						curanswer = float(gigaWattCalc * gigaWatt2)
						hpcalc = float(curanswer * 1341022)
						wattCalc = float(curanswer * 1000000000)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float(curanswer * 0.000000001)
						print ("The answer is " + str(curanswer) + " gigawatts")
						print ("\nThis is equal to: ")
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 4:
						gigaWatt2 = float(input("Enter a gigawatt amount to divide: "))
						curanswer = float(gigaWattCalc / gigaWatt2)
						hpcalc = float(curanswer * 1341022)
						wattCalc = float(curanswer * 1000000000)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float(curanswer * 0.000000001)
						print ("The answer is " + str(curanswer) + " gigawatts")
						print ("\nThis is equal to: ")
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 5:
						gigaWatt2 = float(input("Enter a gigawatt amount to mod: "))
						curanswer = float(gigaWattCalc % gigaWatt2)
						hpcalc = float(curanswer * 1341022)
						wattCalc = float(curanswer * 1000000000)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float(curanswer * 0.000000001)
						print ("The answer is " + str(curanswer) + " gigawatts")
						print ("\nThis is equal to: ")
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 6:
						curanswer = float(gigaWattCalc)
						hpcalc = float(curanswer * 1341022)
						wattCalc = float(curanswer * 1000000000)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float(curanswer * 0.000000001)
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
				if (wattType == "HP"):
					hpcalc = float(input("Enter an amount in HP: "))
					print ("\n\n")
					print ("How do you want to use the units? ")
					print ("Addition [ID: 1]")
					print ("Subtraction [ID: 2]")
					print ("Multiplication [ID: 3]")
					print ("Division [ID: 4]")
					print ("Modular division [ID: 5]")
					print ("1 unit only [ID: 6]")
					unitByUnit = int(input("Enter an ID to continue: >> "))
					if unitByUnit == 1:
						hp2 = float(input("Enter a HP amount to add: "))
						curanswer = float(hpcalc + hp2)
						wattCalc = float(curanswer * 745.6999)
						kiloWattCalc = float(curanswer * 0.7456999)
						megaWattCalc = float(curanswer * 0.0007456999)
						gigaWattCalc = float(curanswer * 0.0000007456999)
						teraWattCalc = float(curanswer * 0.0000000007456999)
						petaWattCalc = float(curanswer * 0.0000000000007456999)
						exaWattCalc = float(curanswer * 0.0000000000000007456999)
						print ("The answer is " + str(curanswer) + " hp")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 2:
						hp2 = float(input("Enter a HP amount to subtract: "))
						curanswer = float(hpcalc - hp2)
						wattCalc = float(curanswer * 745.6999)
						kiloWattCalc = float(curanswer * 0.7456999)
						megaWattCalc = float(curanswer * 0.0007456999)
						gigaWattCalc = float(curanswer * 0.0000007456999)
						teraWattCalc = float(curanswer * 0.0000000007456999)
						petaWattCalc = float(curanswer * 0.0000000000007456999)
						exaWattCalc = float(curanswer * 0.0000000000000007456999)
						print ("The answer is " + str(curanswer) + " hp")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 3:
						hp2 = float(input("Enter a HP amount to multiply: "))
						curanswer = float(hpcalc * hp2)
						wattCalc = float(curanswer * 745.6999)
						kiloWattCalc = float(curanswer * 0.7456999)
						megaWattCalc = float(curanswer * 0.0007456999)
						gigaWattCalc = float(curanswer * 0.0000007456999)
						teraWattCalc = float(curanswer * 0.0000000007456999)
						petaWattCalc = float(curanswer * 0.0000000000007456999)
						exaWattCalc = float(curanswer * 0.0000000000000007456999)
						print ("The answer is " + str(curanswer) + " hp")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 4:
						hp2 = float(input("Enter a HP amount to divide by: "))
						curanswer = float(hpcalc / hp2)
						wattCalc = float(curanswer * 745.6999)
						kiloWattCalc = float(curanswer * 0.7456999)
						megaWattCalc = float(curanswer * 0.0007456999)
						gigaWattCalc = float(curanswer * 0.0000007456999)
						teraWattCalc = float(curanswer * 0.0000000007456999)
						petaWattCalc = float(curanswer * 0.0000000000007456999)
						exaWattCalc = float(curanswer * 0.0000000000000007456999)
						print ("The answer is " + str(curanswer) + " hp")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 5:
						hp2 = float(input("Enter a HP amount to mod: "))
						curanswer = float(hpcalc % hp2)
						wattCalc = float(curanswer * 745.6999)
						kiloWattCalc = float(curanswer * 0.7456999)
						megaWattCalc = float(curanswer * 0.0007456999)
						gigaWattCalc = float(curanswer * 0.0000007456999)
						teraWattCalc = float(curanswer * 0.0000000007456999)
						petaWattCalc = float(curanswer * 0.0000000000007456999)
						exaWattCalc = float(curanswer * 0.0000000000000007456999)
						print ("The answer is " + str(curanswer) + " hp")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 6:
						curanswer = float(hpcalc)
						wattCalc = float(curanswer * 1000000000)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						gigaWattCalc = float(curanswer * 1341022)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float(curanswer * 0.000000001)
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
				if (wattType == "Kilowatt"):
					kiloWattCalc = float(input("Enter an amount in Kilowatts: "))
					print ("\n\n")
					print ("How do you want to use the units? ")
					print ("Addition [ID: 1]")
					print ("Subtraction [ID: 2]")
					print ("Multiplication [ID: 3]")
					print ("Division [ID: 4]")
					print ("Modular division [ID: 5]")
					print ("1 unit only [ID: 6]")
					unitByUnit = int(input("Enter an ID to continue: >> "))
					if unitByUnit == 1:
						kiloWatt2 = float(input("Enter a Kilowatt amount to add: "))
						curanswer = float(kiloWattCalc + kiloWatt2)
						wattCalc = float(curanswer * 1000)
						hpcalc = float(curanswer * 1.341022)
						megaWattCalc = float(curanswer * 0.001)
						gigaWattCalc = float(curanswer * 0.000001)
						teraWattCalc = float(curanswer * 0.000000001)
						petaWattCalc = float(curanswer * 0.000000000001)
						exaWattCalc = float(curanswer * 0.000000000000001)
						print ("The answer is " + str(curanswer) + " Kilowatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")				
					if unitByUnit == 2:
						kiloWatt2 = float(input("Enter a Kilowatt amount to subtract: "))
						curanswer = float(kiloWattCalc - kiloWatt2)
						wattCalc = float(curanswer * 1000)
						hpcalc = float(curanswer * 1.341022)
						megaWattCalc = float(curanswer * 0.001)
						gigaWattCalc = float(curanswer * 0.000001)
						teraWattCalc = float(curanswer * 0.000000001)
						petaWattCalc = float(curanswer * 0.000000000001)
						exaWattCalc = float(curanswer * 0.000000000000001)
						print ("The answer is " + str(curanswer) + " Kilowatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 3:
						kiloWatt2 = float(input("Enter a Kilowatt amount to multiply by: "))
						curanswer = float(kiloWattCalc + kiloWatt2)
						wattCalc = float(curanswer * 1000)
						hpcalc = float(curanswer * 1.341022)
						megaWattCalc = float(curanswer * 0.001)
						gigaWattCalc = float(curanswer * 0.000001)
						teraWattCalc = float(curanswer * 0.000000001)
						petaWattCalc = float(curanswer * 0.000000000001)
						exaWattCalc = float(curanswer * 0.000000000000001)
						print ("The answer is " + str(curanswer) + " Kilowatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 4:
						kiloWatt2 = float(input("Enter a Kilowatt amount to divide by: "))
						curanswer = float(kiloWattCalc + kiloWatt2)
						wattCalc = float(curanswer / 1000)
						hpcalc = float(curanswer * 1.341022)
						megaWattCalc = float(curanswer * 0.001)
						gigaWattCalc = float(curanswer * 0.000001)
						teraWattCalc = float(curanswer * 0.000000001)
						petaWattCalc = float(curanswer * 0.000000000001)
						exaWattCalc = float(curanswer * 0.000000000000001)
						print ("The answer is " + str(curanswer) + " Kilowatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 5:
						kiloWatt2 = float(input("Enter a Kilowatt amount to mod: "))
						curanswer = float(kiloWattCalc % kiloWatt2)
						wattCalc = float(curanswer * 1000)
						hpcalc = float(curanswer * 1.341022)
						megaWattCalc = float(curanswer * 0.001)
						gigaWattCalc = float(curanswer * 0.000001)
						teraWattCalc = float(curanswer * 0.000000001)
						petaWattCalc = float(curanswer * 0.000000000001)
						exaWattCalc = float(curanswer * 0.000000000000001)
						print ("The answer is " + str(curanswer) + " Kilowatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 6:
						curanswer = float(kiloWattCalc)
						hpcalc = float(curanswer * 1.341022)
						wattCalc = float(curanswer * 1000)
						megaWattCalc = float(curanswer * 0.001)
						gigaWattCalc = float(curanswer * 0.000001)
						teraWattCalc = float(curanswer * 0.000000001)
						petaWattCalc = float(curanswer * 0.000000000001)
						exaWattCalc = float(curanswer * 0.000000000000001)
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
				if (wattType == "Megawatt"):
					megaWattCalc = float(input("Enter an amount in Megawatts: "))
					print ("\n\n")
					print ("How do you want to use the units? ")
					print ("Addition [ID: 1]")
					print ("Subtraction [ID: 2]")
					print ("Multiplication [ID: 3]")
					print ("Division [ID: 4]")
					print ("Modular division [ID: 5]")
					print ("1 unit only [ID: 6]")
					unitByUnit = int(input("Enter an ID to continue: >> "))
					if unitByUnit == 1:
						megaWatt2 = float(input("Enter a Megawatt amount to add: "))
						curanswer = float(megaWattCalc + megaWatt2)
						wattCalc = float(curanswer * 1000000)
						hpcalc = float(curanswer * 1341.022)
						kiloWattCalc = float(curanswer * 1000)
						gigaWattCalc = float(curanswer * 0.001)
						teraWattCalc = float(curanswer * 0.000001)
						petaWattCalc = float(curanswer * 0.000000001)
						exaWattCalc = float (curanswer * 0.000000000001)
						print ("The answer is " + str(curanswer) + " Megawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")			
					if unitByUnit == 2:
						megaWatt2 = float(input("Enter a Megawatt amount to subtract: "))
						curanswer = float(megaWattCalc - megaWatt2)
						wattCalc = float(curanswer * 1000000)
						hpcalc = float(curanswer * 1341.022)
						kiloWattCalc = float(curanswer * 1000)
						gigaWattCalc = float(curanswer * 0.001)
						teraWattCalc = float(curanswer * 0.000001)
						petaWattCalc = float(curanswer * 0.000000001)
						exaWattCalc = float (curanswer * 0.000000000001)
						print ("The answer is " + str(curanswer) + " Megawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 3:
						megaWatt2 = float(input("Enter a Megawatt amount to multiply by: "))
						curanswer = float(megaWattCalc * megaWatt2)
						wattCalc = float(curanswer * 1000000)
						hpcalc = float(curanswer * 1341.022)
						kiloWattCalc = float(curanswer * 1000)
						gigaWattCalc = float(curanswer * 0.001)
						teraWattCalc = float(curanswer * 0.000001)
						petaWattCalc = float(curanswer * 0.000000001)
						exaWattCalc = float (curanswer * 0.000000000001)
						print ("The answer is " + str(curanswer) + " Megawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 4:
						megaWatt2 = float(input("Enter a Megawatt amount to divide by: "))
						curanswer = float(megaWattCalc / megaWatt2)
						wattCalc = float(curanswer * 1000000)
						hpcalc = float(curanswer * 1341.022)
						kiloWattCalc = float(curanswer * 1000)
						gigaWattCalc = float(curanswer * 0.001)
						teraWattCalc = float(curanswer * 0.000001)
						petaWattCalc = float(curanswer * 0.000000001)
						exaWattCalc = float (curanswer * 0.000000000001)
						print ("The answer is " + str(curanswer) + " Megawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 5:
						megaWatt2 = float(input("Enter a Megawatt amount to mod: "))
						curanswer = float(megaWattCalc + megaWatt2)
						wattCalc = float(curanswer * 1000000)
						hpcalc = float(curanswer * 1341.022)
						kiloWattCalc = float(curanswer * 1000)
						gigaWattCalc = float(curanswer * 0.001)
						teraWattCalc = float(curanswer * 0.000001)
						petaWattCalc = float(curanswer * 0.000000001)
						exaWattCalc = float (curanswer * 0.000000000001)
						print ("The answer is " + str(curanswer) + " Megawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 6:
						curanswer = float(megaWattCalc)
						hpcalc = float(curanswer * 1341.022)
						wattCalc = float(curanswer * 1000000)
						kiloWattCalc = float(curanswer * 1000)
						gigaWattCalc = float(curanswer * 0.001)
						teraWattCalc = float(curanswer * 0.000001)
						petaWattCalc = float(curanswer * 0.000000001)
						exaWattCalc = float(curanswer * 0.000000000001)
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
				if (wattType == "Gigawatt"):
					gigaWattCalc = float(input("Enter an amount in Gigawatts: "))
					print ("\n\n")
					print ("How do you want to use the units? ")
					print ("Addition [ID: 1]")
					print ("Subtraction [ID: 2]")
					print ("Multiplication [ID: 3]")
					print ("Division [ID: 4]")
					print ("Modular division [ID: 5]")
					print ("1 unit only [ID: 6]")
					unitByUnit = int(input("Enter an ID to continue: >> "))
					if unitByUnit == 1:
						gigaWatt2 = float(input("Enter a Gigawatt amount to add: "))
						curanswer = float(gigaWattCalc + gigaWatt2)
						wattCalc = float(curanswer * 1000000000)
						hpcalc = float(curanswer * 1341022)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float (curanswer * 0.000000001)
						print ("The answer is " + str(curanswer) + " Gigawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")									
					if unitByUnit == 2:
						gigaWatt2 = float(input("Enter a Gigawatt amount to subtract: "))
						curanswer = float(gigaWattCalc - gigaWatt2)
						wattCalc = float(curanswer * 1000000000)
						hpcalc = float(curanswer * 1341022)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float (curanswer * 0.000000001)
						print ("The answer is " + str(curanswer) + " Gigawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 3:
						gigaWatt2 = float(input("Enter a Gigawatt amount to multiply: "))
						curanswer = float(gigaWattCalc * gigaWatt2)
						wattCalc = float(curanswer * 1000000000)
						hpcalc = float(curanswer * 1341022)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float (curanswer * 0.000000001)
						print ("The answer is " + str(curanswer) + " Gigawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 4:
						gigaWatt2 = float(input("Enter a Gigawatt amount to divide by: "))
						curanswer = float(gigaWattCalc / gigaWatt2)
						wattCalc = float(curanswer * 1000000000)
						hpcalc = float(curanswer * 1341022)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float (curanswer * 0.000000001)
						print ("The answer is " + str(curanswer) + " Gigawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 5:
						gigaWatt2 = float(input("Enter a Gigawatt amount to mod: "))
						curanswer = float(gigaWattCalc + gigaWatt2)
						wattCalc = float(curanswer * 1000000000)
						hpcalc = float(curanswer * 1341022)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float (curanswer * 0.000000001)
						print ("The answer is " + str(curanswer) + " Gigawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 6:
						curanswer = float(gigaWattCalc)
						hpcalc = float(curanswer * 1341022)
						wattCalc = float(curanswer * 1000000000)
						kiloWattCalc = float(curanswer * 1000000)
						megaWattCalc = float(curanswer * 1000)
						teraWattCalc = float(curanswer * 0.001)
						petaWattCalc = float(curanswer * 0.000001)
						exaWattCalc = float(curanswer * 0.000000001)
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
				if (wattType == "Terawatt"):
					teraWattCalc = float(input("Enter an amount in Terawatts: "))
					print ("\n\n")
					print ("How do you want to use the units? ")
					print ("Addition [ID: 1]")
					print ("Subtraction [ID: 2]")
					print ("Multiplication [ID: 3]")
					print ("Division [ID: 4]")
					print ("Modular division [ID: 5]")
					print ("1 unit only [ID: 6]")
					unitByUnit = int(input("Enter an ID to continue: >> "))
					if unitByUnit == 1:
						teraWatt2 = float(input("Enter a Terawatt amount to add: "))
						curanswer = float(teraWattCalc + teraWatt2)
						wattCalc = float(curanswer * 1000000000000)
						hpcalc = float(curanswer * 1341022000)
						kiloWattCalc = float(curanswer * 1000000000)
						megaWattCalc = float(curanswer * 1000000)
						gigaWattCalc = float(curanswer * 1000)
						petaWattCalc = float(curanswer * 0.001)
						exaWattCalc = float (curanswer * 0.000001)
						print ("The answer is " + str(curanswer) + " Terawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")		
					if unitByUnit == 2:
						teraWatt2 = float(input("Enter a Terawatt amount to subtract by: "))
						curanswer = float(teraWattCalc - teraWatt2)
						wattCalc = float(curanswer * 1000000000000)
						hpcalc = float(curanswer * 1341022000)
						kiloWattCalc = float(curanswer * 1000000000)
						megaWattCalc = float(curanswer * 1000000)
						gigaWattCalc = float(curanswer * 1000)
						petaWattCalc = float(curanswer * 0.001)
						exaWattCalc = float (curanswer * 0.000001)
						print ("The answer is " + str(curanswer) + " Terawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 3:
						teraWatt2 = float(input("Enter a Terawatt amount to multiply by: "))
						curanswer = float(teraWattCalc * teraWatt2)
						wattCalc = float(curanswer * 1000000000000)
						hpcalc = float(curanswer * 1341022000)
						kiloWattCalc = float(curanswer * 1000000000)
						megaWattCalc = float(curanswer * 1000000)
						gigaWattCalc = float(curanswer * 1000)
						petaWattCalc = float(curanswer * 0.001)
						exaWattCalc = float (curanswer * 0.000001)
						print ("The answer is " + str(curanswer) + " Terawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 4:
						teraWatt2 = float(input("Enter a Terawatt amount to divide by: "))
						curanswer = float(teraWattCalc / teraWatt2)
						wattCalc = float(curanswer * 1000000000000)
						hpcalc = float(curanswer * 1341022000)
						kiloWattCalc = float(curanswer * 1000000000)
						megaWattCalc = float(curanswer * 1000000)
						gigaWattCalc = float(curanswer * 1000)
						petaWattCalc = float(curanswer * 0.001)
						exaWattCalc = float (curanswer * 0.000001)
						print ("The answer is " + str(curanswer) + " Terawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 5:
						teraWatt2 = float(input("Enter a Terawatt amount to mod: "))
						curanswer = float(teraWattCalc % teraWatt2)
						wattCalc = float(curanswer * 1000000000000)
						hpcalc = float(curanswer * 1341022000)
						kiloWattCalc = float(curanswer * 1000000000)
						megaWattCalc = float(curanswer * 1000000)
						gigaWattCalc = float(curanswer * 1000)
						petaWattCalc = float(curanswer * 0.001)
						exaWattCalc = float (curanswer * 0.000001)
						print ("The answer is " + str(curanswer) + " Terawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 6:
						curanswer = float(teraWattCalc)
						hpcalc = float(curanswer * 1341022000)
						wattCalc = float(curanswer * 1000000000000)
						kiloWattCalc = float(curanswer * 1000000000)
						megaWattCalc = float(curanswer * 1000000)
						gigaWattCalc = float(curanswer * 1000)
						petaWattCalc = float(curanswer * 0.001)
						exaWattCalc = float(curanswer * 0.000001)
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
				if (wattType == "Petawatt"):
					petaWattCalc = float(input("Enter an amount in Petawatts: "))
					print ("\n\n")
					print ("How do you want to use the units? ")
					print ("Addition [ID: 1]")
					print ("Subtraction [ID: 2]")
					print ("Multiplication [ID: 3]")
					print ("Division [ID: 4]")
					print ("Modular division [ID: 5]")
					print ("1 unit only [ID: 6]")
					unitByUnit = int(input("Enter an ID to continue: >> "))
					if unitByUnit == 1:
						petaWatt2 = float(input("Enter a petawatt amount to add: "))
						curanswer = float(petaWattCalc + petaWatt2)
						wattCalc = float(curanswer * 1000000000000000)
						hpcalc = float(curanswer * 1341022000000)
						kiloWattCalc = float(curanswer * 1000000000000)
						megaWattCalc = float(curanswer * 1000000000)
						gigaWattCalc = float(curanswer * 1000000)
						teraWattCalc = float(curanswer * 1000)
						exaWattCalc = float (curanswer * 0.001)
						print ("The answer is " + str(curanswer) + " Petawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 2:
						petaWatt2 = float(input("Enter a petawatt amount to subtract by: "))
						curanswer = float(petaWattCalc - petaWatt2)
						wattCalc = float(curanswer * 1000000000000000)
						hpcalc = float(curanswer * 1341022000000)
						kiloWattCalc = float(curanswer * 1000000000000)
						megaWattCalc = float(curanswer * 1000000000)
						gigaWattCalc = float(curanswer * 1000000)
						teraWattCalc = float(curanswer * 1000)
						exaWattCalc = float (curanswer * 0.001)
						print ("The answer is " + str(curanswer) + " Petawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 3:
						petaWatt2 = float(input("Enter a petawatt amount to multiply by: "))
						curanswer = float(petaWattCalc * petaWatt2)
						wattCalc = float(curanswer * 1000000000000000)
						hpcalc = float(curanswer * 1341022000000)
						kiloWattCalc = float(curanswer * 1000000000000)
						megaWattCalc = float(curanswer * 1000000000)
						gigaWattCalc = float(curanswer * 1000000)
						teraWattCalc = float(curanswer * 1000)
						exaWattCalc = float (curanswer * 0.001)
						print ("The answer is " + str(curanswer) + " Petawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 4:
						petaWatt2 = float(input("Enter a petawatt amount to divide by: "))
						curanswer = float(petaWattCalc / petaWatt2)
						wattCalc = float(curanswer * 1000000000000000)
						hpcalc = float(curanswer * 1341022000000)
						kiloWattCalc = float(curanswer * 1000000000000)
						megaWattCalc = float(curanswer * 1000000000)
						gigaWattCalc = float(curanswer * 1000000)
						teraWattCalc = float(curanswer * 1000)
						exaWattCalc = float (curanswer * 0.001)
						print ("The answer is " + str(curanswer) + " Petawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 5:
						petaWatt2 = float(input("Enter a petawatt amount to mod: "))
						curanswer = float(petaWattCalc % petaWatt2)
						wattCalc = float(curanswer * 1000000000000000)
						hpcalc = float(curanswer * 1341022000000)
						kiloWattCalc = float(curanswer * 1000000000000)
						megaWattCalc = float(curanswer * 1000000000)
						gigaWattCalc = float(curanswer * 1000000)
						teraWattCalc = float(curanswer * 1000)
						exaWattCalc = float (curanswer * 0.001)
						print ("The answer is " + str(curanswer) + " Petawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 6:
						curanswer = float(petaWattCalc)
						hpcalc = float(curanswer * 1341022000000)
						wattCalc = float(curanswer * 1000000000000000)
						kiloWattCalc = float(curanswer * 1000000000000)
						megaWattCalc = float(curanswer * 1000000000)
						gigaWattCalc = float(curanswer * 1000000)
						teraWattCalc = float(curanswer * 1000)
						exaWattCalc = float(curanswer * 0.001)
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
				if (wattType == "Exawatt"):
					exaWattCalc = float(input("Enter an amount in Exawatts: "))
					print ("\n\n")
					print ("How do you want to use the units? ")
					print ("Addition [ID: 1]")
					print ("Subtraction [ID: 2]")
					print ("Multiplication [ID: 3]")
					print ("Division [ID: 4]")
					print ("Modular division [ID: 5]")
					print ("1 unit only [ID: 6]")
					unitByUnit = int(input("Enter an ID to continue: >> "))
					if unitByUnit == 1:
						exaWatt2 = float(input("Enter an exawatt amount to add: "))
						curanswer = float(exaWattCalc + exaWatt2)
						wattCalc = float(curanswer * 1000000000000000000)
						hpcalc = float(curanswer * 1341022000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float (curanswer * 1000)
						print ("The answer is " + str(curanswer) + " Exawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 2:
						exaWatt2 = float(input("Enter an exawatt amount to subtract by: "))
						curanswer = float(exaWattCalc - exaWatt2)
						wattCalc = float(curanswer * 1000000000000000000)
						hpcalc = float(curanswer * 1341022000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float (curanswer * 1000)
						print ("The answer is " + str(curanswer) + " Exawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 3:
						exaWatt2 = float(input("Enter an exawatt amount to multiply by: "))
						curanswer = float(exaWattCalc * exaWatt2)
						wattCalc = float(curanswer * 1000000000000000000)
						hpcalc = float(curanswer * 1341022000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float (curanswer * 1000)
						print ("The answer is " + str(curanswer) + " Exawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")	
					if unitByUnit == 4:
						exaWatt2 = float(input("Enter an exawatt amount to divide by: "))
						curanswer = float(exaWattCalc / exaWatt2)
						wattCalc = float(curanswer * 1000000000000000000)
						hpcalc = float(curanswer * 1341022000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float (curanswer * 1000)
						print ("The answer is " + str(curanswer) + " Exawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 5:
						exaWatt2 = float(input("Enter an exawatt amount to mod: "))
						curanswer = float(exaWattCalc % exaWatt2)
						wattCalc = float(curanswer * 1000000000000000000)
						hpcalc = float(curanswer * 1341022000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float (curanswer * 1000)
						print ("The answer is " + str(curanswer) + " Exawatts")
						print ("\nThis is equal to: ")
						print ("Watts: " + str(wattCalc))
						print ("HP: " + str(hpcalc))
						print ("kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")
					if unitByUnit == 6:
						curanswer = float(exaWattCalc)
						hpcalc = float(curanswer * 1341022000000000)
						wattCalc = float(curanswer * 1000000000000000000)
						kiloWattCalc = float(curanswer * 1000000000000000)
						megaWattCalc = float(curanswer * 1000000000000)
						gigaWattCalc = float(curanswer * 1000000000)
						teraWattCalc = float(curanswer * 1000000)
						petaWattCalc = float(curanswer * 1000)
						print ("HP: " + str(hpcalc))
						print ("Watts: " + str(wattCalc))
						print ("Kilowatts: " + str(kiloWattCalc))
						print ("Megawatts: " + str(megaWattCalc))
						print ("Gigawatts: " + str(gigaWattCalc))
						print ("Terawatts: " + str(teraWattCalc))
						print ("Petawatts: " + str(petaWattCalc))
						print ("Exawatts: " + str(exaWattCalc))
						more1 = input("\n\n\nPress [ENTER] key to exit ")						
			if sortopt == ("2"):
				print ("Sorting from Z-A")
				print ("\n")
				print ("Watt")
				print ("Terawatt")
				print ("Petawatt")
				print ("Megawatt")
				print ("Kilowatt")
				print ("HP")
				print ("Gigawatt")
				print ("Exawatt")
				more1 = input("Press [ENTER] key to start")
			if sortopt == ("3"):
				print ("Sorting from small to large amounts of power")
				print ("\n")
				print ("HP")
				print ("Watt")
				print ("Kilowatt")
				print ("Megawatt")
				print ("Gigawatt")
				print ("Terawatt")
				print ("Petawatt")
				print ("Exawatt")
				more1 = input("Press [ENTER] key to start")
			if sortopt == ("4"):
				print ("Sorting from large to small amounts of power")
				print ("\n")
				print ("Exawatt")
				print ("Petawatt")
				print ("Terawatt")
				print ("Gigawatt")
				print ("Megawatt")
				print ("Kilowatt")
				print ("Watt")
				print ("HP")
				more1 = input("Press [ENTER] key to start")
		if getAnID == 2:
			print ("|~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~O~o~|")
			print ("Holiday power calculator")
			more1 = input("Press [ENTER] key to start")
			print ("\n\n\n\n\n\nMy setups: ")
			print (holidaypowersetup1name + " ID: 1")
			print (holidaypowersetup2name + " ID: 2")
			print (holidaypowersetup3name + " ID: 3")
			print (holidaypowersetup4name + " ID: 4")
			print (holidaypowersetup5name + " ID: 5")
			print (holidaypowersetup6name + " ID: 6")
			print (holidaypowersetup7name + " ID: 7")
			print (holidaypowersetup8name + " ID: 8")
			print (holidaypowersetup9name + " ID: 9")
			print (holidaypowersetup10name + " ID: 10")	
			print (holidaypowersetup11name + " ID: 11")
			print (holidaypowersetup12name + " ID: 12")
			print (holidaypowersetup13name + " ID: 13")
			print (holidaypowersetup14name + " ID: 14")
			print (holidaypowersetup15name + " ID: 15")
			print (holidaypowersetup16name + " ID: 16")
			print (holidaypowersetup17name + " ID: 17")
			print (holidaypowersetup18name + " ID: 18")
			print (holidaypowersetup19name + " ID: 19")
			print (holidaypowersetup20name + " ID: 20")	
			print (holidaypowersetup21name + " ID: 21")
			print (holidaypowersetup22name + " ID: 22")
			print (holidaypowersetup23name + " ID: 23")
			print (holidaypowersetup24name + " ID: 24")
			print (holidaypowersetup25name + " ID: 25")	
			print ("NEW!  [ID: 0]")
			selectHolSetID = int(input("Enter an ID for a setup to begin. If no setups exist, use 0 to create a new setup"))
			if selectHolSetID == 1:
				print (holidaypowersetup1name + " - Setup")
				print ("\n\n\n\n|-----|")
				print ("Settings ")
				print ("Rename             [ID: 1]")
				print ("Edit light strands [ID: 2]")
				print ("Configure power    [ID: 3]")
				holpow1ID = int(input("Enter an ID to start>>"))
				if holpow1ID == 1:
					print ("The current name for this setup is " + holidaypowersetup1name)
					print ("You can now change it!")
					confirmChange = int(input("Type 1 to continue, type 0 to exit"))
					if confirmChange == 1:
						print ("Rename " + holidaypowersetup1name)
						holidaypowersetup1name = str(input("Enter a new name here: "))
						print ("Rename successful1")
					if not confirmChange == 1:
						print ("Rename operaton aborted")
print ("Your power calculator has run into an unexpected error and stopped looping")
noMore = input("Press [ENTER] to exit power calculator")