		if calcIDSes == 33:
					print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
					print ("Division (with decimals)")
					div1dec1 = float(input("Enter number 1: "))
					div2dec2 = float(input("Enter number 2: "))
					curanswer = (div1dec1 / div2dec2)
					print ("The current answer is: " + str(curanswer))
					div3dec3 = float(input("Enter number 3: "))
					curanswer = (div1dec1 / div2dec2 / div3dec3)
					print ("The current answer is: " + str(curanswer))
					bloat1 = input("| FAIL! SETUP RESTARTING (we can't fix the bug right now, we are porting features in. Stabilizing later, my bad)")