		if calcIDSes == 32:
					print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
					print ("Multiplication (with decimals)")
					multiply1dec1 = float(input("Enter number 1: "))
					multiply2dec2 = float(input("Enter number 2: "))
					curanswer = (multiply1dec1 * multiply2dec2)
					print ("The current answer is: " + str(curanswer))
					multiply3dec3 = float(input("Enter number 3: "))
					curanswer = (multiply1dec1 * multiply2dec2 * multiply3dec3)
					print ("The current answer is: " + str(curanswer))
					bloat1 = input("| FAIL! SETUP RESTARTING (we can't fix the bug right now, we are porting features in. Stabilizing later, my bad)")