print (" ")
print ("      ___           ___           ___           ___           ___              ")
print ("     /\\  \\         /\\  \\         /\\  \\         /\\__\\         /\\  \\             ")
print ("    /::\\  \\       /::\\  \\       /::\\  \\       /:/  /         \\:\\  \\            ")
print ("   /:/\\:\\  \\     /:/\\:\\  \\     /:/\\:\\  \\     /:/  /           \\:\\  \\           ")
print ("  /::\\~\\:\\  \\   /::\\~\\:\\__\\   /:/  \\:\\  \\   /:/  /  ___       /::\\  \\          ")
print (" /:/\\:\\ \\:\\__\\ /:/\\:\\ \\:|__| /:/__/ \\:\\__\\ /:/__/  /\\__\\     /:/\\:\\__\\    ")     
print (" \\/__\\:\\/:/  / \\:\\~\\:\\/:/  / \\:\\  \\ /:/  / \\:\\  \\ /:/  /    /:/  \\/__/    ")     
print ("      \\::/  /   \\:\\ \\::/  /   \\:\\  /:/  /   \\:\\  /:/  /    /:/  /             ") 
print ("      /:/  /     \\:\\/:/  /     \\:\\/:/  /     \\:\\/:/  /     \\/__/             ")  
print ("     /:/  /       \\::/__/       \\::/  /       \\::/  /                          ")
print ("     \\/__/         ~~            \\/__/         \\/__/                          ") 
print ("      ___           ___           ___           ___       ___                  ")
print ("     /\\__\\         /\\  \\         /\\  \\         /\\__\\     /\\  \\               ")  
print ("    /:/  /        /::\\  \\       /::\\  \\       /:/  /    /::\\  \\                ")
print ("   /:/  /        /:/\\:\\  \\     /:/\\:\\  \\     /:/  /    /:/\\:\\  \\               ")
print ("  /:/  /  ___   /:/  \\:\\  \\   /::\\~\\:\\  \\   /:/  /    /:/  \\:\\  \\            ")  
print (" /:/__/  /\\__\\ /:/__/ \\:\\__\\ /:/\\:\\ \\:\\__\\ /:/__/    /:/__/ \\:\\__\\      ")       
print (" \\:\\  \\ /:/  / \\:\\  \\  \\/__/ \\/__\\:\\/:/  / \\:\\  \\    \\:\\  \\  \\/__/")             
print ("  \\:\\  /:/  /   \\:\\  \\            \\::/  /   \\:\\  \\    \\:\\  \\        ")           
print ("   \\:\\/:/  /     \\:\\  \\           /:/  /     \\:\\  \\    \\:\\  \\      ")            
print ("    \\::/  /       \\:\\__\\         /:/  /       \\:\\__\\    \\:\\__\\    ")             
print ("     \\/__/         \\/__/         \\/__/         \\/__/     \\/__/       ")          
print (" ")
print (" ")
print (" ____  _____  ____    _   _  _____  ___  ____  ____  ____   __    __    ___ ")
print ("( ___)(  _  )(  _ \\  ( )_( )(  _  )/ __)(  _ \\(_  _)(_  _) /__\\  (  )  / __)")
print (" )__)  )(_)(  )   /   ) _ (  )(_)( \\__ \\ )___/ _)(_   )(  /(__)\\  )(__ \\__ \\")
print ("(__)  (_____)(_)\\_)  (_) (_)(_____)(___/(__)  (____) (__)(__)(__)(____)(___/")
print ("This is the hospital edition of UCALC. It is designed for medical-based calculations and for saving precious lives. It does not contain all the features. If you want to have more features, choose a different version. This is free software and you have the write to use, modify, and share this program with anybody")
print ("This is free, open-source software made for everyone")
print ("Version type: Windows Executable (.exe)")
print ("Platform: 86x64x128")
print ("(c) Copyleft, Sean Walla Walla 2015-2019")
noMore = input("Press [ENTER] key to exit")