print ("Chatbot chatrooms")
print ("\n\n")
enterToEnter = input("Press [ENTER] key to get started")
print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSelect a group")
print ("Famous Scientists")
print ("Tech experts")
print ("US presidents")
print ("Global tech support")
groupID = str(input("Enter an ID to start"))
noMore = input("Press [ENTER] key to quit")