print (" ")
print (" ")
print ("   _,.----.                  ,----.   ,---.   ,--.--------.    ,----. ")                      
print (" .. .. -   \\  .-.,.---.   ,-.--. , \\.--..  \\ /==/,  -   , -\\,-.--. , \\    ")                    
print ("/==/  ,  ,-. /==/  .   \\ |==|-  _.-.\\==\\-/\\ \\\\==\\.-.  - ,-./==|-  _.-.      ")                  
print ("|==|-   |  .|==|-, .=., ||==|   ..-./==/-|_\\ |.--.\\==\\- \\  |==|   ..-.             ")           
print ("|==|_   .-. \\==|   .=.  /==/_ ,    /\\==\\,   - \\    \\==\\_ \\/==/_ ,    /              ")          
print ("|==|   _  , |==|- ,   ..|==|    .-. /==/ -   ,|    |==|- ||==|    .-.                       ")  
print ("\\==\\.       /==|_  . ,..|==|_  ,.-./==/-  /\\ - \\   |==|, ||==|_  ,.-._                      ")  
print (" .-...___.-./==/  /\\ ,  )==/ ,     |==\\ _.\\=\\.-.   /==/ -//==/ ,     /                      ")  
print ("            .--.-.--.--..--.-----.. .--.           .--.--..--.-----..                       ")  
print ("   ,---.      .-._                                                                          ")  
print (" .--..  \\    /==/ \\  .-._                                                                   ")  
print (" \\==\\-/\\ \\   |==|, \\/ /, /                                                                ")  
print (" /==/-|_\\ |  |==|-  \\|  |                                                                   ")  
print (" \\==\\,   - \\ |==| ,  | -|                                                                   ")  
print (" /==/ -   ,| |==| -   _ |                                                                   ")  
print ("/==/-  /\\ - \\|==|  /\\ , |                                                                   ")  
print ("\\==\\ _.\\=\\.-./==/, | |- |                                                                   ")  
print (" .--.        .--../  .--.                                                                   ")  
print ("   ,---.       _,.----.    _,.----.     _,.---._                 .-._        ,--.--------.  ")  
print (" .--..  \\    .. .. -   \\ .. .. -   \\  ,-.. , -  ..  .--.-. .-.-./==/ \\  .-._/==/,  -   , -\\ ")  
print (" \\==\\-/\\ \\  /==/  ,  ,-./==/  ,  ,-. /==/_,  ,  - \\/==/ -|/=/  ||==|, \\/ /, |==\\.-.  - ,-./ ")  
print (" /==/-|_\\ | |==|-   |  .|==|-   |  .|==|   .=.     |==| ,||=| -||==|-  \\|  | .--.\\==\\- \\    ")  
print (" \\==\\,   - \\|==|_   .-. \\==|_   .-. \\==|_ : ;=:  - |==|- | =/  ||==| ,  | -|      \\==\\_ \\   ")  
print (" /==/ -   ,||==|   _  , |==|   _  , |==| , .=.     |==|,  \\/ - ||==| -   _ |      |==|- |   ")  
print ("/==/-  /\\ - \\==\\.       |==\\.       /\\==\\ -    ,_ /|==|-   ,   /|==|  /\\ , |      |==|, | ")    
print ("\\==\\ _.\\=\\.-..-...___.-. .-...___.-.  ..=.. -   .. /==/ , _  .. /==/, | |- |      /==/ -/   ")  
print (" .--.                                     .--.--..   .--...---.   .--../  .--.      .--.--.   ")  
print (" ")  
enterToEnter = input("Press [ENTER] key to continue: ")
print ("\n\n\n\n")
print ("[]---------------------------------------------------------------[]")
print ("|                                                                 |")
print ("| C R E A T E - A - L O C A L - A C C O U N T ( O F F L I N E )   |")
print ("|                                                                 |")
print ("[]---------------------------------------------------------------[]")
print ("\n")
print ("[]---------------------------------------------------------------[]")
print ("|                                                                 |")
print ("| C R E A T E - A - W E B - A C C O U N T ( O N L I N E )         |")
print ("|                                                                 |")
print ("[]---------------------------------------------------------------[]")
print ("\n\n\n")
print ("Local account:")
print ("Portable offline account for productivity. It is HIGHLY recommended to ALWAYS have a local account ready")
print ("ID: 1")
print ("\n")
print ("Web account:")
print ("Online account for UCALC. View online communities, make and join servers, share your work, and have emergency backup of all your data through the internet")
print ("ID: 2")
print ("\n\n")
accountCreateID = str(input("Enter an ID to create an account: "))
if (accountCreateID == "1"):
	print ("Checking to make sure you have enough memory...")
	print ("Memory required: 1.20 MB")
	print ("Memory available: 95.75 MB")
if (accountCreateID == "2"):
	print ("Searching for connections...")
	print ("\n\nAccount plan")
	print ("You are attempting to create an online UCALC account. We would like to show you the benefits and features that come with a UCALC account: ")
	print ("Memory: ")
	print ("1.00 Gigabyte of online storage starter (10.00 MB added per day)")
	print ("Connection type: ")
	print ("HTTPS")
	print ("We can store: ")
	print ("<*> Calculation history")
	print ("<*> posts")
	print ("<*> liked posts")
	print ("<*> profile info, history, and changes")
	print ("<*> your UCALC passwords and usernames (delete account to remove)")
	print ("You can manage what info we hold on your account. If you need to remove data, you can easily remove it.")
	areYouSure = str(input("Are you OK with this? (Y/N): "))
	if (areYouSure == "Y"):
		print ("Alright, we are getting your account ready")
		account1username = str(input("Enter a username: "))
		account1password = str(input("Enter a password: "))
		retypepassword = str(input("Retype your password: "))
		if (account1password == retypepassword):
			print ("Step 2: NULL")
		else:
			print ("Invalid password entered! > Passwords do not match < aborting!")
noMore = input("Press [ENTER] key to quit")