			if WikIDSelect == 10007:
				print ("C R E D I T S")
				print (" ")
				print (" ")
				more1 = input("Press [ENTER] key to start")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("Programmers")
				print ("\nSean P. Myrick")
				more1 = input("Press [ENTER] key for more")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("Beta testers")
				print ("\nSean P. Myrick")
				print ("Michael Whitney")
				print ("Colleen P. Myrick")
				more1 = input("Press [ENTER] key for more")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("Inspirations")
				print ("\nWindows 3.1 - Microsoft")
				print ("Windows 1.01 - Microsoft")
				print ("Wikipedia - Wikimedia foundation")
				print ("NASA - National American Space Agency")
				more1 = input("Press [ENTER] key for more")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("Sound producers")
				print ("\nSean Myrick")
				more1 = input("Press [ENTER] key for more")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
				print ("Special thanks to")
				print ("\nMichael Whitney - for showing interest")
				print ("Carrie Delfino - for teaching me how to program in python")
				print ("Colleen and Vern Myrick - for supporting me through my life")
				noMore = input("Press [ENTER] key to quit")