			if WikIDSelect == 10014:
				print ("Common math errors")
				print ("Part 1: Common Fraction Errors")
				print ("Fractions are a useful form of measurement for many types of math formulas and equations")
				print ("However, sometimes things can be confusing, and when it doesn't work, you can get a little frustrated")
				print ("Here, we will go over some common fraction mistakes, and how you can fix them:")
				print ("\n 1/3 + 2/4")
				fraction1answ1 = str(input("What does that make?"))
				print ("If you entered 1, that would be incorrect. For these types of equations, you have to look closely")
				print ("You just assumed that 1 plus 2 is three. That is correct, but notice how the second fraction has a 4 instead of a 3?")
				print ("")
				print ("Here is another one, pretty easy: ")
				print ("1/3 + 1/3 + 1/3")
				fraction2answ1 = str(input("What does that make?"))
				print ("This one is is a whole number")