WikIDSelect = int(20005)
if WikIDSelect == 20005:
	if WikIDSelect == 20005:
		if WikIDSelect == 20005:
			if WikIDSelect == 20005:
				print ("In computer architecture, 12-bit integers, memory addresses, or other data units are those that are 12 bits (1.5 octets) wide. ")
				print ("Also, 12-bit CPU and ALU architectures are those that are based on registers, address buses, or data buses of that size.")
				print (" ")
				print ("Possibly the best-known 12-bit CPU is the PDP-8 and its relatives, such as the Intersil 6100 microprocessor produced in ")
				print ("various incarnations from August 1963 to mid-1990. Many analog to digital converters (ADCs) have a 12-bit resolution. Some") 
				print ("PIC microcontrollers use a 12-bit word size.")
				print (" ")
				print ("12 binary digits, or 3 nibbles (a 'tribble'), have 4096 (10000 octal, 1000 hexadecimal) distinct combinations. Hence, a ")
				print ("microprocessor with 12-bit memory addresses can directly access 4096 words (4 Kw) of word-addressable memory. At a time ")
				print ("when six-bit character codes were common a 12-bit word, which could hold two characters, was a convenient size. ")
				print ("IBM System/360 instruction formats use a 12-bit displacement field which, added to the contents of a base register, can") 
				print ("address 4096 bytes of memory.")
				more1 = input("List of 12-bit computer systems")
				print (" ")
				print ("Digital Equipment Corporation")
				print ("PDP-5")
				print ("PDP-8")
				print ("DECmate, a personal computer based on the Intersil 6100")
				print ("PDP-12")
				print ("PDP-14")
				print ("Intersil IM6100 microprocessor (PDP-8-compatible)")
				print ("Control Data Corporation")
				print ("CDC 6600 - Peripheral Processor (PP)")
				print ("CDC 160 series computers")
				print ("National Cash Register NCR 315")
				print ("Scientific Data Systems SDS 92")
				print ("Ford Motor Company EEC I Automotive engine control unit")
				print ("PC12 minicomputer")
				print ("Ferranti Argus")
				print ("LINC, later commercialized by DEC as the LINC-8")
				print ("Electronic Arrays 9002 (12-bit addressing but 8-bit byte)")
				noMore = input("Press [ENTER] key to exit")