calcIDSes = int(53)
if calcIDSes == 53:
	if calcIDSes == 53:
		if calcIDSes == 53:
			if calcIDSes == 53:
				if calcIDSes == 53:
					print ("Memory calculator")
					basenum = int(input("Base 2 binary (0) Base 10 binary (1) "))
					print ("Byte (0) Kilobyte (1) Megabyte (2) Gigabyte (3) Terabyte (4) Petabyte (5) Exabyte (6) Zettabyte (7) Yottabyte (8)")
					byteID = int(input("Enter an ID (0-8) "))
					if byteID == 0:
						print ("Byte calculator")
						bytecount = int(input("Enter an amount: "))
						bitcount = int(bytecount * 8)
						print ("Total bits: " + str(bitcount))
					if byteID == 1:
						print ("Kilobyte calculator")
						kbytecount = int(input("Enter an amount: "))
						if basenum == 0:
							bytecount = int(kbytecount * 1024)
							bitcount = int(bytecount * 8)
						if basenum == 1:
							bytecount = int(kbytecount * 1000)
							bitcount = int(bytecount * 8)
						print ("Total bytes: " + str(bytecount))
						print ("Total bits: " + str(bitcount))
					if byteID == 2:
						print ("Megabyte calculator")
						mbytecount = int(input("Enter an amount: "))
						if basenum == 0:
							kbytecount = int(mbytecount * 1024)
							bytecount = int(kbytecount * 1024)
							bitcount = int(bytecount * 8)
						if basenum == 1:
							kbytecount = int(mbytecount * 1000)
							bytecount = int(kbytecount * 1000)
							bitcount = int(bytecount * 8)
						print ("Total Kilobytes: " + str(kbytecount))
						print ("Total bytes: " + str(bytecount))
						print ("Total bits: " + str(bitcount))
					if byteID == 3:
						print ("Gigabyte calculator")
						gbytecount = int(input("Enter an amount: "))
						if basenum == 0:
							mbytecount = int(gbytecount * 1024)
							kbytecount = int(mbytecount * 1024)
							bytecount = int(kbytecount * 1024)
							bitcount = int(bytecount * 8)
						if basenum == 1:
							mbytecount = int(gbytecount * 1000)
							kbytecount = int(mbytecount * 1000)
							bytecount = int(kbytecount * 1000)
							bitcount = int(bytecount * 8)
						print ("Total Megabytes: " + str(mbytecount))
						print ("Total Kilobytes: " + str(kbytecount))
						print ("Total bytes: " + str(bytecount))
						print ("Total bits: " + str(bitcount))
					if byteID == 4:
						print ("Terabyte calculator")
						tbytecount = int(input("Enter an amount: "))
						if basenum == 0:
							gbytecount = int(tbytecount * 1024)
							mbytecount = int(gbytecount * 1024)
							kbytecount = int(mbytecount * 1024)
							bytecount = int(kbytecount * 1024)
							bitcount = int(bytecount * 1024)
						if basenum == 1:
							gbytecount = int(tbytecount * 1000)
							mbytecount = int(gbytecount * 1000)
							kbytecount = int(mbytecount * 1000)
							bytecount = int(kbytecount * 1000)
							bitcount = int(bytecount * 1000)
						print ("Total Gigabytes: " + str(gbytecount))
						print ("Total Megabytes: " + str(mbytecount))
						print ("Total Kilobytes: " + str(kbytecount))
						print ("Total bytes: " + str(bytecount))
						print ("Total bits: " + str(bitcount))
					if byteID == 5:
						print ("Petabyte calculator")
						pbytecount = int(input("Enter an amount: "))
						if basenum == 0:
							tbytecount = int(pbytecount * 1024)
							gbytecount = int(tbytecount * 1024)
							mbytecount = int(gbytecount * 1024)
							kbytecount = int(mbytecount * 1024)
							bytecount = int(kbytecount * 1024)
							bitcount = int(bytecount * 8)
						if basenum == 1:
							tbytecount = int(pbytecount * 1000)
							gbytecount = int(tbytecount * 1000)
							mbytecount = int(gbytecount * 1000)
							kbytecount = int(mbytecount * 1000)
							bytecount = int(kbytecount * 1000)
							bitcount = int(bytecount * 8)
						print ("Total Terabytes: " + str(tbytecount))
						print ("Total Gigabytes: " + str(gbytecount))
						print ("Total Megabytes: " + str(mbytecount))
						print ("Total Kilobytes: " + str(kbytecount))
						print ("Total Bytes: " + str(bytecount))
						print ("Total bits: " + str(bitcount))
					if byteID == 6:
						print ("Exabyte calculator")
						exbytecount = int(input("Enter an amount: "))
						if basenum == 0:
							pbytecount = int(exbytecount * 1024)
							tbytecount = int(pbytecount * 1024)
							gbytecount = int(tbytecount * 1024)
							mbytecount = int(gbytecount * 1024)
							kbytecount = int(mbytecount * 1024)
							bytecount = int(kbytecount * 1024)
							bitcount = int(bytecount * 8)
						if basenum == 1:
							pbytecount = int(exbytecount * 1000)
							tbytecount = int(pbytecount * 1000)
							gbytecount = int(tbytecount * 1000)
							mbytecount = int(gbytecount * 1000)
							kbytecount = int(mbytecount * 1000)
							bytecount = int(kbytecount * 1000)
							bitcount = int(bytecount * 8)
						print ("Total Petabytes: " + str(pbytecount))
						print ("Total Terabytes: " + str(tbytecount))
						print ("Total Gigabytes: " + str(gbytecount))
						print ("Total Megabytes: " + str(mbytecount))
						print ("Total Kilobytes: " + str(kbytecount))
						print ("Total bytes: " + str(bytecount))
						print ("Total bits: " + str(bitcount))
					if byteID == 7:
						print ("Zettabyte calculator")
						zbytecount = int(input("Enter an amount: "))
						if basenum == 0:
							exbytecount = int(zbytecount * 1024)
							pbytecount = int(exbytecount * 1024)
							tbytecount = int(pbytecount * 1024)
							gbytecount = int(tbytecount * 1024)
							mbytecount = int(gbytecount * 1024)
							kbytecount = int(mbytecount * 1024)
							bytecount = int(kbytecount * 1024)
							bitcount = int(bytecount * 8)
						if basenum == 1:
							exbytecount = int(zbytecount * 1000)
							pbytecount = int(exbytecount * 1000)
							tbytecount = int(pbytecount * 1000)
							gbytecount = int(tbytecount * 1000)
							mbytecount = int(gbytecount * 1000)
							kbytecount = int(mbytecount * 1000)
							bytecount = int(kbytecount * 1000)
							bitcount = int(bytecount * 8)
						print ("Total Exabytes: " + str(exbytecount))
						print ("Total Petabytes: " + str(pbytecount))
						print ("Total Terabytes: " + str(tbytecount))
						print ("Total Gigabytes: " + str(gbytecount))
						print ("Total Megabytes: " + str(mbytecount))
						print ("Total Kilobytes: " + str(kbytecount))
						print ("Total bytes: " + str(bytecount))
						print ("Total bits: " + str(bitcount))
					if byteID == 8:
						print ("Yottabyte calculator")
						ybytecount = int(input("Enter an amount: "))
						if basenum == 0:
							zbytecount = int(ybytecount * 1024)
							exbytecount = int(zbytecount * 1024)
							pbytecount = int(exbytecount * 1024)
							tbytecount = int(pbytecount * 1024)
							gbytecount = int(tbytecount * 1024)
							mbytecount = int(gbytecount * 1024)
							kbytecount = int(mbytecount * 1024)
							bytecount = int(kbytecount * 1024)
							bitcount = int(bytecount * 8)
						if basenum == 1:
							zbytecount = int(ybytecount * 1000)
							exbytecount = int(zbytecount * 1000)
							pbytecount = int(exbytecount * 1000)
							tbytecount = int(pbytecount * 1000)
							gbytecount = int(tbytecount * 1000)
							mbytecount = int(gbytecount * 1000)
							kbytecount = int(mbytecount * 1000)
							bytecount = int(kbytecount * 1000)
							bitcount = int(bytecount * 8)	
						print ("Total Zettabytes: " + str(zbytecount))
						print ("Total Exabytes: " + str(exbytecount))
						print ("Total Petabytes: " + str(pbytecount))
						print ("Total Terabytes: " + str(tbytecount))
						print ("Total Gigabytes: " + str(gbytecount))
						print ("Total Megabytes: " + str(mbytecount))
						print ("Total Kilobytes: " + str(kbytecount))
						print ("Total bytes: " + str(bytecount))
						print ("Total bits: " + str(bitcount))
					noMore = input("Press [ENTER] key to quit")