	if uCMainConsole == 6:
		print ("============================================================")
		print (" ")
		print ("  ___    __    __  __  ____  ___ ")
		print (" / __)  /__\\  (  \\/  )( ___)/ __)")
		print ("( (_-. /(__)\\  )    (  )__) \\__ \\")
		print (" \\___/(__)(__)(_/\\/\\_)(____)(___/")
		print ("\n\nThis area requires administrator access to prevent distraction")
		entadminam = str(input("Enter an administrative username: "))
		if (entadminam == adminusr):
			print ("Admin name entered successfully!")
			entadminpas = str(input("Enter the administrators password: "))
			if (entadminpas == adminpas):
				print ("Password entry confirmed!")
				print ("Logging in...\nPlease wait")
				gameLoop = int(1)
				while gameLoop == 1:
					print ("===================================================")
					print ("Game catalog")
					print ("2048  | ID: 10")
					print ("Launch the X  | ID: 11")
					print ("Rock! Paper! Scissors!  | ID: 12")
					print ("Tic-Tac-Toe | ID: 13")
					print ("Pig [ID: 14]")
					print ("Pimun [ID: 15]")
					print ("X cups [ID: 16] ")
					print ("Yahtzee! [ID: 17]")
					print ("Solitaire [ID: 18]")
					print ("Bingo! [ID: 19]")
					print ("Minesweeper [ID: 20]")
					print ("===================================================")
					gameselectID = int(input("Enter an ID to start: "))