# some required modules
import math
import random
# classes
# print ("ANSI Number Scale") # note: this script was ripped from another program I made. The original file is 'classtest.py' 
# 1 is english
print ("==================================================")
print (" ")
print ("  _     ____  ____  _     ____ ")
print (" / \\ /\\/   _\\/  _ \\/ \\   /   _\\")
print (" | | |||  /  | / \|| |   |  /  ")
print (" | \_/||  \_ | |-||| |_/\|  \_ ")
print (" \____/\____/\_/ \|\____/\____/")
print ("  ")                            
print ("")
print (" ")
print ("               `:+shdmNMMMMNmdhs+:`               ") 
print ("           `:smMmyo/:.``` ``.:/oymMms:`           ") 
print ("         :yMmyyo```-.`--`         `:smNy:       ")   
print ("       +mMMmoyymmssNoy+yMs            -yMm+       ") 
print ("     :mMMMMNdMMMmo-.:yy:/           ` :dMNMm:     ") 
print ("   `yMMMMMMMMNhMNy:/hMMMm-        :oh--shsyMMy`   ") 
print ("  `dMNMMMMMMMMMsymNMMs:/o:          odMMNNMMMMd`  ") 
print (" `mMMMMMMMMMMMMyhhh+.`.           omdh/-+/oNddMd` ") 
print (" yMsdMMMMMMMMMMMNs                +dhyyy`- -`/yMy ") 
print ("-Mm .hhMMMms++sh                 +MMMMMMMmdMmyhMM-") 
print ("yM+  /:dMN` .                  /NMMMMMMMMMMMMMMMMy") 
print ("NM.    -yhodN+                 /MMMMMMMMMMMMMMMMMm") 
print ("MM`        `:d:-ody/o.         -dMMMMMMMMMMMMMMMMM") 
print ("NM.            oMMMMMNds         /o+/-+yMMMMMMMMMN") 
print ("yM+           sMMMMMMMMMy++/           -MMMMMMMMMy") 
print (":Mm           /NMMMMMMMMMMMMd           :NMMMMMMM-") 
print (" yMo           `yNMMMMMMMMMN`           :MMMMMMMy ") 
print (" `mM/             mMMMMMMMNs            .NMMMMMm` ") 
print ("  `dMo            dMMMMMM-               sMMMMd`  ") 
print ("   `yMh.          oMMMMMy`                dMMy`   ") 
print ("     :mMs`        -NMdy:                `sMm:     ") 
print ("      +mMy-       mMy`               -yMm+      ")  
print ("         :yNms:`   .hM:           `:smNy:    ")      
print ("           `:smMmyo/::-` ```.:/oymMms:`   ")        
print ("               `-+shdmNMMMMNmdhs+-`     ")          
print ("\n             =======================")
print ("            =========================")
print ("English (1) | Español (2) | français (3) | Deutsche (4) |")
print ("svenska (5) | 日本人 (6)  | 中文 (7)      |  русский (8) |")
lansupportint = int(input(">>"))