	if uCMainConsole == 9:	
		print ("UCalc settings")
		print ("\nFont: [Calibri]")
		print ("[Courier] [Comic Sans] [Times new roman] [Scratch]")
		print ("\nResolution: [EXPANDABLE: (1360x730) ]")
		print ("[1280x720] [1920x1080] [2560x1440] [3840x2160]")
		print ("\nColor type: [MONOCHROME (2 color) ]")
		print ("[16 color] [8 bit] [16 bit] [24 bit] [32 bit]")
		print ("Language: [Python 3.6]")
		print ("[Python 2.7] [Python 3.0] [Python 3.1] [Python 3.2] [Python 3.3] [Python 3.4] [Python 3.5] [Python 3.7] [Python 3.8]")
		print ("Text color")
		print ("Background: [Black]")
		print ("[White] [Grey] [Red] [Blue] [Green] [Orange] [Pink] [Brown] [Purple]")
		print ("Main text: [White]")
		print ("[Black] [Grey] [Red] [Blue] [Green] [Orange] [Pink] [Brown] [Purple]")
		print ("Answer text: [White]")
		print ("[Black] [Grey] [Red] [Blue] [Green] [Orange] [Pink] [Brown] [Purple]")
		print ("Encoding [UTF-8]")
		print ("[No other options available]")
		print (" ")
		IDSelect = int(input("Enter an ID to change a setting: "))