print ("Reggie - Registery Viewer")
print (" ")
print ("Version 1.00")
startReggie = input("Press [ENTER] key to start")
print ("\n\n\n\n\n\n\n\n\n\n\nSelect a letter")
print ("\n[#] [a] [b] [c] [d]")
print ("[e] [f] [g] [h] [i]")
print ("[j] [k] [l] [m] [n]")
print ("[o] [p] [q] [r] [s]")
print ("[t] [u] [v] [w] [x]")
print ("[y] [z]")
print ("\n")
startReggie2 = str(input("Enter a letter to start, type REG to view reggies properties: "))
if (startReggie2 == "#"):
	print ("Registry Error! No items exist under this letter")
if (startReggie2 == "a" or startReggie2 == "A"):
	print ("[A] Registry explorer")
	print (" ")
	print ("ADDITION_CALC.py [ID: 1]")
	print ("ADDITION_CALC_WITH_DEC.py [ID: 2]")
	print ("ALB_EIN_BACKUP1.py [ID: 3]")
	print ("ALB_EIN_METADAT.py [ID: 4]")
	print ("ANSI_CLASS.py [ID: 5]")
	print ("ANSI_TRANSLATOR.py [ID: 6]")
	print ("ASCII_CALC_3BIT.py [ID: 7]")
	print ("ASCII_CALC_4BIT.py [ID: 8]")
	print ("ASCII_CALC_5BIT.py [ID: 9]")
	print ("ASCII_CALC_6BIT.py [ID: 10]")
	print ("ASCII_CALC_7BIT.py [ID: 11]")
	print ("ASCII_CALC_8BIT.py [ID: 12]")
	print ("ASCII_CALC_9BIT.py [ID: 13]")
	print ("ASCII_CALC_10BIT.py [ID: 14]")
	print ("ASCII_CALC_11BIT.py [ID: 15]")
	print ("ASCII_CALC_12BIT.py [ID: 16]")
	print ("ASCII_CALC_13BIT.py [ID: 17]")
	print ("ASCII_CALC_14BIT.py [ID: 18]")
	print ("ASCII_CALC_15BIT.py [ID: 19]")
	print ("ASCII_CALC_16BIT.py [ID: 20]")
	print ("ASCII_CALC_MODE_SELECTION.py [ID: 21]")
	searchRegistryA = int(input("Enter an ID to continue: "))
	if (searchRegistryA == 1):
		print ("Registry A > ADDITION_CALC.py ")
		print ("ID: 1\n\n\n")
		print ("=====================================================================================================================================")
		print ("\nAttributes: ")
		print ("2x [str]")
		print ("10x [int]")
		print ("0x [float]")
		print ("2x [input]")
		print ("=====================================================================================================================================")
		print ("\nInternal variables: ")
		print ("[enterToEnter] type: [input] purpose: pausing the main menu, waiting for keyboard input to start program ocurrences: 1")
		print ("[calcIDSes] type: [int] purpose: old frame replacement occurences: 4")
		print ("[add1] type: [int] purpose: taking the first number for calculation occurences: 2")
		print ("[add2] type: [int] purpose: taking the first number for calculation occurences: 2")
		print ("[add3] type: [int] purpose: taking the first number for calculation occurences: 2")
		print ("[add4] type: [int] purpose: taking the first number for calculation occurences: 2")
		print ("[add5] type: [int] purpose: taking the first number for calculation occurences: 2")
		print ("[curanswer] type: [str] purpose: calculating and displaying the answer occurences: 2")
		print ("[noMore] type: [input] purpose: requiring keyboard input to exit the program")
		print ("=====================================================================================================================================")
		print ("Size: 1776 bytes (1.77 Kilobyres | 1.73 Kilobytes)")
		print ("Type: .py (Python file)")
		print ("Python version: 3.7.1")
		print ("=====================================================================================================================================")
		exit1 = input("Press [ENTER] key to exit")
	if (searchRegistryA == 2):
		print ("Registry A > ADDITION_CALC_WITH_DEC.py ")
		print ("ID: 2\n\n\n")
		print ("=====================================================================================================================================")
		print ("\nAttributes: ")
		print ("4x [str]")
		print ("4x [int]")
		print ("9x [float]")
		print ("2x [input]")
		print ("=====================================================================================================================================")
		print ("\nInternal variables: ")
		print ("[enterToEnter] type: [input] purpose: pausing the main menu, waiting for keyboard input to start program ocurrences: 1")
		print ("[calcIDSes] type: [int] purpose: old frame replacement | occurences: 4")
		print ("[add1dec1] type: [float] purpose: holding the first float value | occurences: 3")
		print ("[add2dec2] type: [float] purpose: holding the second float value | occurences: 3")
		print ("[add3dec3] type: [float] purpose: holding the third float value | occurences: 3")
		print ("[curanswer] type: [str] purpose: calculating and displaying the answer | occurences: 4")
		print ("[noMore] type: [input] purpose: requiring keyboard input to exit the program | occurences: 1")
		print ("=====================================================================================================================================")
		print ("Size: 1370 bytes (1.37 Kilobyres | 1.33 Kilobytes)")
		print ("Type: .py (Python file)")
		print ("Python version: 3.7.1")
		print ("=====================================================================================================================================")
		exit1 = input("Press [ENTER] key to exit")
if (startReggie2 == "reg" or startReggie2 == "Reg" or startReggie2 == "REG"):
	print ("Reggie attributes")
	print ("\n\n\n")
	print ("[str]")
	print ("[int]")
	print ("[float]")
	print ("[input]")
	print ("=====================================================================================================================================")
	print ("\nInternal variables: ")
	print ("[startReggie] type: [input] purpose: input to start Reggie occurences: | 1 ")
	print ("[startReggie2] type: [str] purpose: registry alphabetical input section selection | occurences: 4") 
	print ("[searchRegistryA] type: [int] purpose: ID entering variable for the A registry | occurences: #")
	print ("[exit1] type: [input] purpose: exiting out of a registry | occurences: #")
	print ("[noMore] type: [input] purpose: keyboard input roadblock to exit the program | occurences: 1")
	print ("=====================================================================================================================================")
	print ("Size: 1370 bytes (1.37 Kilobyres | 1.33 Kilobytes)")
	print ("Type: .py (Python file)")
	print ("Python version: 3.7.1")
	print ("=====================================================================================================================================")
	exit1 = input("Press [ENTER] key to exit")
noMore = input("Press [ENTER] key to exit")