WikIDSelect = int(10002)
if WikIDSelect == 10002:
	if WikIDSelect == 10002:
		if WikIDSelect == 10002:
			if WikIDSelect == 10002:
				print ("READ_ME.TXT | Calculator Notepad |")
				print ("''''''''''''''''''''''''''''''''''")
				print ("DevData subdirectory |")
				print ("=====================/")
				print (" ")
				print ("=========================================================================\\")
				print ("                                                                         |")
				print ("As a joke referrring to the old 8:3 file system, and the calculators     |")
				print ("we are succeeding in this project, during the pre-alpha phase, we        |")
				print ("made several .DAT files. These aren't used by anything, they are just    |")
				print ("notes. Try looking inside them with notepad, notepad++ or other text     |")
				print ("editors. Don't worry, simple modifications or overwrites to the contents |")
				print ("of the files will have NO effect on UCALC they are simply just notes     |")
				print ("                                                                 - Sean  |")
				print ("=========================================================================/")
				print (" ")
				print ("========================================\\")
				print ("N I C E _ A S C I I _ A R T _ S E A N   |")
				print ("A E T H E T I C _ B O T T O M _ T E X T |")
				print ("========================================/")
				print (" ")
				print ("===================================================================================\\")
				print ("Copyleft (>) Sean Walla Walla 2015-2018                                            |")
				print ("Modifications are allowed to the program as long as credit is given                |")
				print ("===================================================================================/")
				print (" ")
				noMore = input("Press [ENTER] key to close this file")
				print ("Closing document")
				print ("Please wait...")