WikIDSelect = int(20000)
if WikIDSelect == 20000:
	if WikIDSelect == 20000:
		if WikIDSelect == 20000:
			if WikIDSelect == 20000:
				print ("Processor setup")
				print ("In computer science and engineering, the processor is one of the main parts of a computer")
				print ("The CPU (Central Processing Unit) works with information on your computer")
				print ("There are processors with different integer caps, such as 4 bit, 8 bit, 16 bit, 32 bit, etc")
				print ("These integer caps hold their own limits")
				print ("Here is a chart on how it works:")
				print ("|-----------------------------------------------------------------------|")
				print ("| CPU Integers                                                          |")
				print ("| 4 bit   | max = 16                                                    |")
				print ("| 8 bit   | max = 255                                                   |")
				print ("| 12 bit  | max = 4096                                                  |")
				print ("| 16 bit  | max = 65,535                                                |")
				print ("| 18 bit  | max = 262,144                                               |")
				print ("| 24 bit  | max = 8,388,607                                             |")
				print ("| 26 bit  | max = UNKNOWN                                               |")
				print ("| 31 bit  | max = UNKNOWN                                               |")
				print ("| 32 bit  | max = 4,294,967,295                                         |")
				print ("| 36 bit  | max = UNKNOWN                                               |")
				print ("| 48 bit  | max = 140,737,488,355,327                                   |")
				print ("| 60 bit  | max = UNKNOWN                                               |")
				print ("| 64 bit  | max = 9,223,372,036,854,775,807                             |")
				print ("| 128 bit | max = 170,141,183,460,469,231,731,687,303,715,884,105,728   |")
				print ("| 256 bit | max = UNKNOWN                                               |")
				print ("| 512 bit | max = UNKNOWN                                               |")
				print ("|-----------------------------------------------------------------------|")
				print ("Which brings us to the Weak Calculators section")
				noMore = input("Press [ENTER] key to exit")
				print ("Exiting")
				print ("Please wait...")