WikIDSelect = int(20007)
if WikIDSelect == 20007:
	if WikIDSelect == 20007:
		if WikIDSelect == 20007:
			if WikIDSelect == 20007:
				print ("In computer architecture, 18-bit integers, memory addresses, or other data units are those that are 18 bits (2.25 octets) ")
				print ("wide. Also, 18-bit CPU and ALU architectures are those that are based on registers, address buses, or data buses of that size.")
				print (" ")
				print ("18 binary digits have 262144 (1000000 octal, 40000 hexadecimal) distinct combinations.")
				print (" ")
				print ("18 bits was a common word size for smaller computers in the 1960s, when large computers often used 36 bit words and ")
				print ("6-bit character sets were the norm.")
				more1 = input("Example computer architectures")
				print (" ")
				print ("Possibly the most well-known 18-bit computer architectures are the PDP-1, PDP-4, PDP-7, PDP-9 and PDP-15 minicomputers ")
				print ("produced by Digital Equipment Corporation from 1960 to 1975.")
				print (" ")
				print ("The UNIVAC produced several 18-bit computers, including the UNIVAC 418 and several military systems.")
				print (" ")
				print ("The IBM 7700 Data Acquisition System was announced by IBM on December 2, 1963.")
				print (" ")
				print ("The BCL Molecular 18 was a group of systems designed and manufactured in the UK in the 1970s and 1980s.")
				print (" ")
				print ("The NASA Standard Spacecraft Computer NSSC-1 was developed as a standard component for the MultiMission Modular Spacecraft at ")
				print ("the Goddard Space Flight Center (GSFC) in 1974.")
				print (" ")
				print ("The flying-spot store digital memory in the first experimental electronic switching systems used nine plates of optical memory ")
				print ("that were read and written two bits at a time, producing a word size of 18 bits.")
				more1 = input("Character encoding")
				print (" ")
				print ("18-bit machines use a variety of character encodings.")
				print (" ")
				print ("The DEC Radix-50, called Radix 508 format, packs three characters plus two bits in each 18-bit word.[1]")
				print (" ")
				print ("The Teletype packs three characters in each 18-bit word; each character a 5-bit Baudot code and an upper-case bit.[2]")
				print (" ")
				print ("The DEC SIXBIT format packs three characters in each 18-bit word,[2] each 6-bit character obtained by stripping the high bits ")
				print ("from the 7-bit ASCII code, which folds lowercase to uppercase letters. ")
				print (" ")
				noMore = input("Press [ENTER] key to exit")