print ("          _____                    _____                    _____                    _____                    _____                    _____      ")    
print ("         /\\    \\                  /\\    \\                  /\\    \\                  /\\    \\                  /\\    \\                  /\\    \\")         
print ("        /::\\    \\                /::\\    \\                /::\\____\\                /::\\    \\                /::\\    \\                /::\\    \\  ")      
print ("       /::::\\    \\              /::::\\    \\              /::::|   |               /::::\\    \\              /::::\\    \\              /::::\\    \\     ")  
print ("      /::::::\\    \\            /::::::\\    \\            /:::::|   |              /::::::\\    \\            /::::::\\    \\            /::::::\\    \\      ")
print ("     /:::/\\:::\\    \\          /:::/\\:::\\    \\          /::::::|   |             /:::/\\:::\\    \\          /:::/\\:::\\    \\          /:::/\\:::\\    \\  ")   
print ("    /:::/__\\:::\\    \\        /:::/__\\:::\\    \\        /:::/|::|   |            /:::/  \\:::\\    \\        /:::/__\\:::\\    \\        /:::/__\\:::\\    \\   ") 
print ("   /::::\\   \\:::\\    \\      /::::\\   \\:::\\    \\      /:::/ |::|   |           /:::/    \\:::\\    \\      /::::\\   \\:::\\    \\       \\:::\\   \\:::\\    \\")   
print ("  /::::::\\   \\:::\\    \\    /::::::\\   \\:::\\    \\    /:::/  |::|___|______    /:::/    / \\:::\\    \\    /::::::\\   \\:::\\    \\    ___\\:::\\   \\:::\\    \\ ") 
print (" /:::/\\:::\\   \\:::\\____\\  /:::/\\:::\\   \\:::\\    \\  /:::/   |::::::::\\    \\  /:::/    /   \\:::\\ ___\\  /:::/\\:::\\   \\:::\\    \\  /\\   \\:::\\   \\:::\\    \\") 
print ("/:::/  \\:::\\   \\:::|    |/:::/__\\:::\\   \\:::\\____\\/:::/    |:::::::::\\____\\/:::/____/     \\:::|    |/:::/  \\:::\\   \\:::\\____\\/::\\   \\:::\\   \\:::\\____\\")
print ("\\::/    \\:::\\  /:::|____|\\:::\\   \\:::\\   \\::/    /\\::/    / ~~~~~/:::/    /\\:::\\    \\     /:::|____|\\::/    \\:::\\  /:::/    /\\:::\\   \\:::\\   \\::/    /")
print (" \\/_____/\\:::\\/:::/    /  \\:::\\   \\:::\\   \\/____/  \\/____/      /:::/    /  \\:::\\    \\   /:::/    /  \\/____/ \\:::\\/:::/    /  \\:::\\   \\:::\\   \\/____/ ")
print ("          \\::::::/    /    \\:::\\   \\:::\\    \\                  /:::/    /    \\:::\\    \\ /:::/    /            \\::::::/    /    \\:::\\   \\:::\\    \\     ")
print ("           \\::::/    /      \\:::\\   \\:::\\____\\                /:::/    /      \\:::\\    /:::/    /              \\::::/    /      \\:::\\   \\:::\\____\\    ")
print ("            \\::/____/        \\:::\\   \\::/    /               /:::/    /        \\:::\\  /:::/    /               /:::/    /        \\:::\\  /:::/    /    ")
print ("             ~~               \\:::\\   \\/____/               /:::/    /          \\:::\\/:::/    /               /:::/    /          \\:::\\/:::/    /     ")
print ("                               \\:::\\    \\                  /:::/    /            \\::::::/    /               /:::/    /            \\::::::/    /      ")
print ("                                \\:::\\____\\                /:::/    /              \\::::/    /               /:::/    /              \\::::/    /       ")
print ("                                 \\::/    /                \\::/    /                \\::/____/                \\::/    /                \\::/    /        ")
print ("                                  \\/____/                  \\/____/                  ~~                       \\/____/                  \\/____/         ")
print ("    ")                                                                                                                                                   
print (" ")
enterToEnter = input("Press [ENTER] key to start! ")
print (" ")
print ("PEMDAS")
print ("Parantheses")
print ("Exponent")
print ("Multiplication")
print ("or")
print ("Division")
print ("Addition")
print ("Subtraction")
explainMore = str(input("Do you want an in depth explanation? (Y/N) "))
if (explainMore == "Y"):
	print ("Excerpt from Wikipedia | https://www,wikipedia.org/Order_Of_Operations")
	print ("In mathematics and computer programming, the order of operations (or operator precedence) is a collection of rules that reflect conventions about which ")
	print ("procedures to perform first in order to evaluate a given mathematical expression.")
	print (" ")
	print ("For example, in mathematics and most computer languages, multiplication is granted a higher precedence than addition, and it has been this way since the  ")
	print ("introduction of modern algebraic notation.[1][2] Thus, the expression 2 + 3 × 4 is interpreted to have the value 2 + (3 × 4) = 14, not (2 + 3) × 4 = 20. ")
	print ("With the introduction of exponents in the 16th and 17th centuries, they were given precedence over both addition and multiplication and could be placed only as a ")
	print ("superscript to the right of their base.[1] Thus 3 + 52 = 28 and 3 × 52 = 75.")
	print (" ")
	print ("These conventions exist to eliminate ambiguity while allowing notation to be as brief as possible. Where it is desired to override the precedence conventions, or") 
	print ("even simply to emphasize them, parentheses ( ) (sometimes replaced by brackets [ ] or braces { } for readability) can indicate an alternate order or reinforce ")
	print ("the default order to avoid confusion. For example, (2 + 3) × 4 = 20 forces addition to precede multiplication, and (3 + 5)2 = 64 forces addition to precede ")
	print ("exponentiation.")
	print ("Contents")
	print (" ")
	print ("    1 Definition")
	print ("        1.1 Examples")
	print ("        1.2 Exceptions")
	print ("        1.3 Unary minus sign")
	print ("        1.4 Mixed division and multiplication")
	print ("    2 Mnemonics")
	print ("    3 Special cases")
	print ("        3.1 Serial exponentiation")
	print ("        3.2 Serial division")
	print ("    4 Calculators")
	print ("    5 Programming languages")
	print ("    6 See also")
	print ("    7 Notes")
	print ("    8 References")
	print ("    9 External links")
	print (" ")
	print ("Definition")
	print (" ")
	print ("The order of operations used throughout mathematics, science, technology and many computer programming languages is expressed here:[1]")
	print (" ")
	print ("    exponents and roots")
	print ("    multiplication and division")
	print ("    addition and subtraction")
	print (" ")
	print ("This means that if a mathematical expression is preceded by one binary operator and followed by another, the operator higher on the list should be applied first.")
	print (" ")
	print ("The commutative and associative laws of addition and multiplication allow adding terms in any order, and multiplying factors in any order—but mixed operations ")
	print ("must obey the standard order of operations.")
	print (" ")
	print ("In some contexts, it is helpful to replace a division by multiplication by the reciprocal (multiplicative inverse) and a subtraction by addition of the opposite ")
	print ("(additive inverse). For example, in computer algebra, this allows manipulating fewer binary operations and makes it easier to use commutativity and associativity ")
	print ("when simplifying large expressions – for more details, see Computer algebra § Simplification. Thus 3 ÷ 4 = 3 × ¼; in other words, the quotient of 3 and 4 equals ")
	print ("the product of 3 and ¼. Also 3 − 4 = 3 + (−4); in other words the difference of 3 and 4 equals the sum of 3 and −4. Thus, 1 − 3 + 7 can be thought of as the sum ")
	print ("of 1 + (−3) + 7, and the three summands may be added in any order, in all cases giving 5 as the result.")
	print (" ")
	print ("The root symbol √ requires a symbol of grouping around the radicand. The usual symbol of grouping is a bar (called vinculum) over the radicand. Other ")
	print ("functions use parentheses around the input to avoid ambiguity. The parentheses are sometimes omitted if the input is a monomial. Thus, sin 3x = sin(3x), ")
	print ("but sin x + y = sin(x) + y, because x + y is not a monomial.[1] Some calculators and programming languages require parentheses around function inputs, some do not.")
	print (" ")
	print ("Symbols of grouping can be used to override the usual order of operations.[1] Grouped symbols can be treated as a single expression.[1] Symbols of grouping can be") 
	print ("removed using the associative and distributive laws, also they can be removed if the expression inside the symbol of grouping is sufficiently simplified so no ")
	print ("ambiguity results from their removal.")
	print ("Examples")
	print (" ")
	print ("    1 + 3 + 5 = 4 + 5 = 2 + 5 = 7. {\\displaystyle {\\sqrt {1+3}}+5={\\sqrt {4}}+5=2+5=7.} {\\displaystyle {\\sqrt {1+3}}+5={\\sqrt {4}}+5=2+5=7.}")
	print (" ")
	print ("A horizontal fractional line also acts as a symbol of grouping:")
	print (" ")
	print ("    1 + 2 3 + 4 + 5 = 3 7 + 5. {\\displaystyle {\\frac {1+2}{3+4}}+5={\\frac {3}{7}}+5.} {\\displaystyle {\\frac {1+2}{3+4}}+5={\\frac {3}{7}}+5.}")
	print (" ")
	print ("For ease in reading, other grouping symbols, such as curly braces { } or square brackets [ ], are often used along with parentheses ( ). For example:")
	print (" ")
	print ("    [ ( 1 + 2 ) − 3 ] − ( 4 − 5 ) = [ 3 − 3 ] − ( − 1 ) = 1. {\\displaystyle [(1+2)-3]-(4-5)=[3-3]-(-1)=1.} {\\displaystyle [(1+2)-3]-(4-5)=[3-3]-(-1)=1.}")
	print (" ")
	print ("Exceptions")
	print ("Unary minus sign")
	print (" ")
	print ("There are differing conventions concerning the unary operator − (usually read ''minus''). In written or printed mathematics, the expression −32 is interpreted ")
	print ("to mean 0 − (32) = − 9,[1][3]")
	print (" ")
	print ("Some applications and programming languages, notably Microsoft Excel (and other spreadsheet applications) and the programming language bc, unary operators have a ")
	print ("higher priority than binary operators, that is, the unary minus has higher precedence than exponentiation, so in those languages −32 will be interpreted as ")
	print ("(−3)2 = 9.[4] This does not apply to the binary minus operator −; for example while the formulas =-2^2 and =0+-2^2 return 4 in Microsoft Excel, the formula ")
	print ("=0-2^2 returns −4. In cases where there is the possibility that the notation might be misinterpreted, a binary minus operation can be enforced by explicitly ")
	print ("specifying a leading 0 (as in 0-2^2 instead of just -2^2), or parentheses can be used to clarify the intended meaning.")
	print ("Mixed division and multiplication")
	print (" ")
	print ("Similarly, there can be ambiguity in the use of the slash symbol / in expressions such as 1/2x.[5] If one rewrites this expression as 1 ÷ 2x and then interprets ")
	print ("the division symbol as indicating multiplication by the reciprocal, this becomes:")
	print (" ")
	print ("    1 ÷ 2 × x = 1 × ½ × x = ½ × x.")
	print (" ")
	print ("With this interpretation 1 ÷ 2x is equal to (1 ÷ 2)x.[1][6] However, in some of the academic literature, multiplication denoted by juxtaposition (also known as") 
	print ("implied multiplication) is interpreted as having higher precedence than division, so that 1 ÷ 2x equals 1 ÷ (2x), not (1 ÷ 2)x.")
	print (" ")
	print ("For example, the manuscript submission instructions for the Physical Review journals state that multiplication is of higher precedence than division with a slash,[7]") 
	print ("and this is also the convention observed in prominent physics textbooks such as the Course of Theoretical Physics by Landau and Lifshitz and the Feynman Lectures ")
	print ("on Physics.[a]")
	print ("Mnemonics")
	print (" ")
	print ("Mnemonics are often used to help students remember the rules, involving the first letters of words representing various operations. Different mnemonics are in ")
	print ("use in different countries.[8][9][10]")
	print (" ")
	print ("    In the United States, the acronym PEMDAS is common. It stands for Parentheses, Exponents, Multiplication/Division, Addition/Subtraction. PEMDAS is often ")
	print ("	expanded to the mnemonic ''Please Excuse My Dear Aunt Sally''.[5]")
	print ("    Canada and New Zealand use BEDMAS, standing for Brackets, Exponents, Division/Multiplication, Addition/Subtraction.")
	print ("    Most common in the UK, India, Bangladesh and Australia[11] and some other English-speaking countries are BODMAS meaning Brackets, Order,") 
	print ("	Division/Multiplication, Addition/Subtraction. Nigeria and some other West African countries also use BODMAS. Similarly in the UK, BIDMAS is used, standing for ")
	print ("	Brackets, Indices, Division/Multiplication, Addition/Subtraction.")
	print (" ")
	print ("These mnemonics may be misleading when written this way.[5] For example, misinterpreting any of the above rules to mean ''addition first, subtraction afterward''") 
	print ("would incorrectly evaluate the expression[5]")
	print (" ")
	print ("    10 − 3 + 2.")
	print (" ")
	print ("The correct value is 9 (and not 5, as if the addition would be carried out first and the result used with the subtraction afterwards).")
	print ("Special cases")
	print ("Serial exponentiation")
	print (" ")
	print ("If exponentiation is indicated by stacked symbols, the usual rule is to work from the top down, because exponentiation is right-associative in mathematics ")
	print ("thus:[1][12]")
	print (" ")
	print ("    abc = a(bc)")
	print (" ")
	print ("which typically is not equal to (ab)c.")
	print (" ")
	print ("However, some computer systems may resolve the ambiguous expression differently.[13] For example, Microsoft Excel evaluates a^b^c as (ab)c, which is opposite ")
	print ("of normally accepted convention of top-down order of execution for exponentiation. Thus 4^3^2 is evaluated to 4,096 instead of 262,144.")
	print (" ")
	print ("Another difference in Microsoft Excel is -a^b which is evaluated as (-a)^b instead of -(a^b). For compatibility, the same behavior is observed on LibreOffice.") 
	print ("The computational programming language MATLAB is another example of a computer system resolving the stacked exponentiation in the non-standard way.")
	print ("Serial division")
	print (" ")
	print ("A similar ambiguity exists in the case of serial division, for example, the expression 10 ÷ 5 ÷ 2 can either be interpreted as")
	print (" ")
	print ("    10 ÷ ( 5 ÷ 2 ) = 4 ")
	print (" ")
	print ("or as")
	print (" ")
	print ("	( 10 ÷ 5 ) ÷ 2 = 1 ")
	print (" ")
	print ("The left-to-right operation convention would resolve the ambiguity in favor of the last expression. Further, the mathematical habit of combining factors and ")
	print ("representing division as multiplication by a reciprocal both greatly reduce the frequency of ambiguous division. However, when two long expressions are combined ")
	print ("by division, the correct order of operations can be lost in the notation.")
	print ("Calculators")
	print ("Main article: Calculator input methods")
	print (" ")
	print ("Different calculators follow different orders of operations. Many simple calculators without a stack implement chain input working left to right without any ")
	print ("priority given to different operators, for example typing")
	print (" ")
	print ("    1 + 2 × 3 yields 9,")
	print (" ")
	print ("while more sophisticated calculators will use a more standard priority, for example typing")
	print (" ")
	print ("    1 + 2 × 3 yields 7.")
	print (" ")
	print ("The Microsoft Calculator program uses the former in its standard view and the latter in its scientific and programmer views.")
	print (" ")
	print ("Chain input expects two operands and an operator. When the next operator is pressed, the expression is immediately evaluated and the answer becomes the left ")
	print ("hand of the next operator. Advanced calculators allow entry of the whole expression, grouped as necessary, and evaluates only when the user uses the equals sign.")
	print (" ")
	print ("Calculators may associate exponents to the left or to the right depending on the model or the evaluation mode. For example, the expression a^b^c is interpreted ")
	print ("as a(bc) on the TI-92 and the TI-30XS MultiView in ''Mathprint mode'', whereas it is interpreted as (ab)c on the TI-30XII and the TI-30XS MultiView in ")
	print ("''Classic mode''.")
	print (" ")
	print ("An expression like 1/2x is interpreted as 1/(2x) by TI-82, but as (1/2)x by TI-83 and every other TI calculator released since 1996,[14] as well as by all ")
	print ("Hewlett-Packard calculators with algebraic notation. While the first interpretation may be expected by some users, only the latter is in agreement with the ")
	print ("standard rule that multiplication and division are of equal precedence,[15][16] so 1/2x is read one divided by two and the answer multiplied by x.")
	print (" ")
	print ("When the user is unsure how a calculator will interpret an expression, it is a good idea to use parentheses so there is no ambiguity.")
	print (" ")
	print ("Calculators that utilize reverse Polish notation (RPN), also known as postfix notation, use a stack to enter formulas without the need for parentheses.[5]")
	print ("Programming languages")
	print (" ")
	print ("Some programming languages use precedence levels that conform to the order commonly used in mathematics,[13] though others, such as APL, Smalltalk or ")
	print ("Occam, have no operator precedence rules (in APL, evaluation is strictly right to left; in Smalltalk and Occam, it is strictly left to right).")
	print (" ")
	print ("In addition, because many operators are not associative, the order within any single level is usually defined by grouping left to right so that 16/4/4 is ")
	print ("interpreted as (16/4)/4 = 1 rather than 16/(4/4) = 16; such operators are perhaps misleadingly referred to as ''left associative''. Exceptions exist; for ")
	print ("example, languages with operators corresponding to the cons operation on lists usually make them group right to left (''right associative''), e.g. in ")
	print ("Haskell, 1:2:3:4:[] == 1:(2:(3:(4:[]))) == [1,2,3,4].")
	print (" ")
	print ("The logical bitwise operators in C (and all programming languages that borrow precedence rules from C, for example, C++, Perl and PHP) have a precedence level ")
	print ("that the creator of the C language considered unsatisfactory.[17] However, many programmers have become accustomed to this order. The relative precedence levels ")
	print ("of operators found in many C-style languages are as follows:")
	print ("1 	()   []   ->   .   :: 	Function call, scope, array/member access")
	print ("2 	!   ~   -   +   *   &   sizeof   type cast   ++   --   	(most) unary operators, sizeof and type casts (right to left)")
	print ("3 	*   /   % MOD 	Multiplication, division, modulo")
	print ("4 	+   - 	Addition and subtraction")
	print ("5 	<<   >> 	Bitwise shift left and right")
	print ("6 	<   <=   >   >= 	Comparisons: less-than and greater-than")
	print ("7 	==   != 	Comparisons: equal and not equal")
	print ("8 	& 	Bitwise AND")
	print ("9 	^ 	Bitwise exclusive OR (XOR)")
	print ("10 	| 	Bitwise inclusive (normal) OR")
	print ("11 	&& 	Logical AND")
	print ("12 	|| 	Logical OR")
	print ("13 	? : 	Conditional expression (ternary)")
	print ("14 	=   +=   -=   *=   /=   %=   &=   |=   ^=   <<=   >>= 	Assignment operators (right to left)")
	print ("15 	, 	Comma operator")
	print (" ")
	print ("Examples: (Note: in the examples below, '≡' is used to mean ''is equivalent to'', and not to be interpreted as an actual assignment operator used as part of the ")
	print ("example expression.)")
	print (" ")
	print ("    !A + !B ≡ (!A) + (!B)")
	print ("    ++A + !B ≡ (++A) + (!B)")
	print ("    A + B * C ≡ A + (B * C)")
	print ("    A || B && C ≡ A || (B && C)")
	print ("    A && B == C ≡ A && (B == C)")
	print ("    A & B == C ≡ A & (B == C)")
	print (" ")
	print ("Source-to-source compilers that compile to multiple languages need to explicitly deal with the issue of different order of operations across languages. Haxe for ")
	print ("example standardizes the order and enforces it by inserting brackets where it is appropriate.[18]")
	print (" ")
	print ("The accuracy of software developer knowledge about binary operator precedence has been found to closely follow their frequency of occurrence in source code.[19]")
noMore = input("Press [ENTER] key to exit")