print (" ")
print ("      ___           ___           ___           ___           ___              ")
print ("     /\\  \\         /\\  \\         /\\  \\         /\\__\\         /\\  \\             ")
print ("    /::\\  \\       /::\\  \\       /::\\  \\       /:/  /         \\:\\  \\            ")
print ("   /:/\\:\\  \\     /:/\\:\\  \\     /:/\\:\\  \\     /:/  /           \\:\\  \\           ")
print ("  /::\\~\\:\\  \\   /::\\~\\:\\__\\   /:/  \\:\\  \\   /:/  /  ___       /::\\  \\          ")
print (" /:/\\:\\ \\:\\__\\ /:/\\:\\ \\:|__| /:/__/ \\:\\__\\ /:/__/  /\\__\\     /:/\\:\\__\\    ")     
print (" \\/__\\:\\/:/  / \\:\\~\\:\\/:/  / \\:\\  \\ /:/  / \\:\\  \\ /:/  /    /:/  \\/__/    ")     
print ("      \\::/  /   \\:\\ \\::/  /   \\:\\  /:/  /   \\:\\  /:/  /    /:/  /             ") 
print ("      /:/  /     \\:\\/:/  /     \\:\\/:/  /     \\:\\/:/  /     \\/__/             ")  
print ("     /:/  /       \\::/__/       \\::/  /       \\::/  /                          ")
print ("     \\/__/         ~~            \\/__/         \\/__/                          ") 
print ("      ___           ___           ___           ___       ___                  ")
print ("     /\\__\\         /\\  \\         /\\  \\         /\\__\\     /\\  \\               ")  
print ("    /:/  /        /::\\  \\       /::\\  \\       /:/  /    /::\\  \\                ")
print ("   /:/  /        /:/\\:\\  \\     /:/\\:\\  \\     /:/  /    /:/\\:\\  \\               ")
print ("  /:/  /  ___   /:/  \\:\\  \\   /::\\~\\:\\  \\   /:/  /    /:/  \\:\\  \\            ")  
print (" /:/__/  /\\__\\ /:/__/ \\:\\__\\ /:/\\:\\ \\:\\__\\ /:/__/    /:/__/ \\:\\__\\      ")       
print (" \\:\\  \\ /:/  / \\:\\  \\  \\/__/ \\/__\\:\\/:/  / \\:\\  \\    \\:\\  \\  \\/__/")             
print ("  \\:\\  /:/  /   \\:\\  \\            \\::/  /   \\:\\  \\    \\:\\  \\        ")           
print ("   \\:\\/:/  /     \\:\\  \\           /:/  /     \\:\\  \\    \\:\\  \\      ")            
print ("    \\::/  /       \\:\\__\\         /:/  /       \\:\\__\\    \\:\\__\\    ")             
print ("     \\/__/         \\/__/         \\/__/         \\/__/     \\/__/       ")          
print (" ")
print (" ")
print (" ____  _____  ____    ____  ____  ____  ____  _  _  ____   ___ ")
print ("( ___)(  _  )(  _ \\  ( ___)(  _ \\(_  _)( ___)( \\( )(  _ \\ / __)")
print (" )__)  )(_)(  )   /   )__)  )   / _)(_  )__)  )  (  )(_) )\\__ \\")
print ("(__)  (_____)(_)\\_)  (__)  (_)\\_)(____)(____)(_)\\_)(____/ (___/")
print ("This is the friend edition of UCALC. It is designed for group activities, and mathmatical conversations. It contains chatbots, and basic calculation modes. It does not contain all the features. If you want to have more features, choose a different version. This is free software and you have the write to use, modify, and share this program with anybody")
print ("This is free, open-source software made for everyone")
print ("Version type: Android Package (.apk)")
print ("Platform: 86x64x128")
print ("(c) Copyleft, Sean Walla Walla 2015-2019")
noMore = input("Press [ENTER] key to exit")