			if WikIDSelect == 10006:
				print ("Terms of usage")
				print ("Please read and accept these conditions to use UCalc")
				more1 = input("Press [ENTER] for more")
				print ("Distribution")
				print ("You are allowed to download, modify, and share this software if you give credit. You can give it publically, to a friend, co-worker, neighbor, or anyone as long as you follow the TOU")
				print ("You cannot charge royalties for this product. It is free open-source software, and must remain free")
				print ("We do not want inappropriate builds. If you are to do that, distribute them privately. No racism, sexism, supremacy, or other bad stuff")
				more1 = input("Press [ENTER] for more")
				print ("Manufacturing")
				print ("You are allowed to manufacture your own versions of the hardware as long as you give credit and reach minimum system requirement")
				more1 = input("Press [ENTER] for more")
				print ("Credit")
				print ("Credit must be given to the original creators, even if you were to just make a minor edit. Plagiarism is NOT allowed")
				nomore = input("Press [ENTER] to agree and exit")