WikIDSelect = int(20015)
if WikIDSelect == 20015:
	if WikIDSelect == 20015:
		if WikIDSelect == 20015:
			if WikIDSelect == 20015:
				print ("In computer architecture, 64-bit computing is the use of processors that have datapath widths, integer size, and memory ")
				print ("address widths of 64 bits (eight octets). Also, 64-bit computer architectures for central processing units (CPUs) and ")
				print ("arithmetic logic units (ALUs) are those that are based on processor registers, address buses, or data buses of that size. ")
				print ("From the software perspective, 64-bit computing means the use of code with 64-bit virtual memory addresses. However, not all ")
				print ("64-bit instruction sets support full 64-bit virtual memory addresses; x86-64 and ARMv8, for example, support only 48 bits of") 
				print ("virtual address, with the remaining 16 bits of the virtual address required to be all 0's or all 1's, and several 64-bit ")
				print ("instruction sets support fewer than 64 bits of physical memory address.")
				print (" ")
				print ("The term 64-bit describes a generation of computers in which 64-bit processors are the norm. 64 bits is a word size ")
				print ("that defines certain classes of computer architecture, buses, memory and CPUs, and by extension the software that ")
				print ("runs on them. 64-bit CPUs have been used in supercomputers since the 1970s (Cray-1, 1975) and in reduced instruction ")
				print ("set computing (RISC) based workstations and servers since the early 1990s, notably the MIPS R4000, R8000, and R10000,") 
				print ("the DEC Alpha, the Sun UltraSPARC, and the IBM RS64 and POWER3 and later POWER microprocessors. In 2003, 64-bit") 
				print ("CPUs were introduced to the (formerly 32-bit) mainstream personal computer market in the form of x86-64 ")
				print ("processors and the PowerPC G5, and were introduced in 2012[1] into the ARM architecture targeting smartphones ")
				print ("and tablet computers, first sold on September 20, 2013, in the iPhone 5S powered by the ARMv8-A Apple A7 system on a chip (SoC).")
				print (" ")
				print ("A 64-bit register can store 264 (over 18 quintillion or 1.8×1019) different values. The range of integer values that can be") 
				print ("stored in 64 bits depends on the integer representation used. With the two most common representations, the range is 0 ")
				print ("through 18,446,744,073,709,551,615 (264 − 1) for representation as an (unsigned) binary number, and −9,223,372,036,854,775,808 ")
				print ("(−263) through 9,223,372,036,854,775,807 (263 − 1) for representation as two's complement. Hence, a processor with ")
				print ("64-bit memory addresses can directly access 264 bytes (=16 exabytes) of byte-addressable memory.")
				print (" ")
				print ("With no further qualification, a 64-bit computer architecture generally has integer and addressing processor ")
				print ("registers that are 64 bits wide, allowing direct support for 64-bit data types and addresses. However, a CPU ")
				print ("might have external data buses or address buses with different sizes from the registers, even larger ")
				print ("(the 32-bit Pentium had a 64-bit data bus, for instance[2]). The term may also refer to the size of ")
				print ("low-level data types, such as 64-bit floating-point numbers.")
				more1 = input("Contents")
				print (" ")
				print ("1 Architectural implications")
				print ("2 History")
				print ("3 Limits of processors")
				print ("4 64-bit data timeline")
				print ("5 64-bit address timeline")
				print ("6 64-bit operating system timeline")
				print ("7 64-bit applications")
				print ("7.1 32-bit vs 64-bit")
				print ("7.2 Pros and cons")
				print ("7.3 Software availability")
				print ("8 64-bit data models")
				print ("9 Current 64-bit architectures")
				print ("10 See also")
				print ("11 Notes")
				print ("12 References")
				print ("13 External links")
				print (" ")
				more1 = input("Architectural implications")
				print (" ")
				print ("Processor registers are typically divided into several groups: integer, floating-point, single instruction, multiple data ")
				print ("(SIMD), control, and often special registers for address arithmetic which may have various uses and names such as address, ")
				print ("index, or base registers. However, in modern designs, these functions are often performed by more general purpose integer ")
				print ("registers. In most processors, only integer or address-registers can be used to address data in memory; the other types ")
				print ("of registers cannot. The size of these registers therefore normally limits the amount of directly addressable memory, ")
				print ("even if there are registers, such as floating-point registers, that are wider.")
				print (" ")
				print ("Most high performance 32-bit and 64-bit processors (some notable exceptions are older or embedded ARM architecture ")
				print ("(ARM) and 32-bit MIPS architecture (MIPS) CPUs) have integrated floating point hardware, which is often, but not")
				print ("always, based on 64-bit units of data. For example, although the x86//x87 architecture has instructions able to ")
				print ("load and store 64-bit (and 32-bit) floating-point values in memory, the internal floating point data and register format ")
				print ("is 80 bits wide, while the general-purpose registers are 32 bits wide. In contrast, the 64-bit Alpha family uses a") 
				print ("64-bit floating-point data and register format, and 64-bit integer registers.")
				more1 = input("History")
				print (" ")
				print ("Many computer instruction sets are designed so that a single integer register can store the memory address to any ")
				print ("location in the computer's physical or virtual memory. Therefore, the total number of addresses to memory is often") 
				print ("determined by the width of these registers. The IBM System//360 of the 1960s was an early 32-bit computer; it ")
				print ("had 32-bit integer registers, although it only used the low order 24 bits of a word for addresses, ")
				print ("resulting in a 16 MiB [16 × 10242 bytes] address space. 32-bit superminicomputers, such as the DEC VA")
				print ("became common in the 1970s, and 32-bit microprocessors, such as the Motorola 68000 family and the 32-bit members of the") 
				print ("x86 family starting with the Intel 80386, appeared in the mid-1980s, making 32 bits something of a de facto consensus as a")			
				print ("convenient register size.")
				print (" ")
				print ("A 32-bit address register meant that 232 addresses, or 4 GiB of random-access memory (RAM), could be referenced.") 
				print ("When these architectures were devised, 4 GB of memory was so far beyond the typical amounts (4 MB) in ")
				print ("installations, that this was considered to be enough headroom for addressing. 4.29 billion addresses were ")
				print ("considered an appropriate size to work with for another important reason: 4.29 billion integers are enough to assign") 
				print ("unique references to most entities in applications like databases.")
				print (" ")
				print ("Some supercomputer architectures of the 1970s and 1980s, such as the Cray-1,[3] used registers up to 64 bits wide, and ")
				print ("supported 64-bit integer arithmetic, although they did not support 64-bit addressing. In the mid-1980s, Intel i860[4] ")
				print ("development began culminating in a (too late[5] for Windows NT) 1989 release; the i860 had 32-bit integer registers and ")
				print ("32-bit addressing, so it was not a fully 64-bit processor, although its graphics unit supported 64-bit integer arithmetic.[6]") 
				print ("However, 32 bits remained the norm until the early 1990s, when the continual reductions in the cost of memory led to") 
				print ("installations with amounts of RAM approaching 4 GB, and the use of virtual memory spaces exceeding the 4 GB ")
				print ("ceiling became desirable for handling certain types of problems. In response, MIPS and DEC developed 64-bit microprocessor")			
				print ("architectures, initially for high-end workstation and server machines. By the mid-1990s, HAL Computer Systems, Sun ")
				print ("Microsystems, IBM, Silicon Graphics, and Hewlett Packard had developed 64-bit architectures for their workstation and ")
				print ("server systems. A notable exception to this trend were mainframes from IBM, which then used 32-bit data and 31-bit address") 
				print ("sizes; the IBM mainframes did not include 64-bit processors until 2000. During the 1990s, several low-cost 64-bit ")
				print ("microprocessors were used in consumer electronics and embedded applications. Notably, the Nintendo 64[7] and the PlayStation") 
				print ("2 had 64-bit microprocessors before their introduction in personal computers. High-end printers, network equipment, and ")
				print ("industrial computers, also used 64-bit microprocessors, such as the Quantum Effect Devices R5000.[citation needed] 64-bit ")
				print ("computing started to drift down to the personal computer desktop from 2003 onward, when some models in Apple's Macintosh ")
				print ("lines switched to PowerPC 970 processors (termed G5 by Apple), and AMD released its first 64-bit x86-64 processor.")
				more1 = input("Limits of processors")
				print (" ")
				print ("This section needs additional citations for verification. Please help improve this article by adding citations to ")
				print ("reliable sources. Unsourced material may be challenged and removed. (January 2010) (Learn how and when to remove ")
				print ("this template message)")
				print (" ")
				print ("In principle, a 64-bit microprocessor can address 16 EiBs (16 × 10246 = 264 = 18,446,744,073,709,551,616 bytes, or ")
				print ("about 18.4 exabytes) of memory. However, not all instruction sets, and not all processors implementing those instruction") 
				print ("sets, support a full 64-bit virtual or physical address space.")
				print (" ")
				print ("The x86-64 architecture (as of 2016) allows 48 bits for virtual memory and, for any given processor, up to 52 bits for ")
				print ("physical memory.[8][9] These limits allow memory sizes of 256 TiB (256 × 10244 bytes) and 4 PiB (4 × 10245 bytes), respectively.")
				print ("A PC cannot currently contain 4 pebibytes of memory (due to the physical size of the memory chips), but AMD envisioned ")
				print ("large servers, shared memory clusters, and other uses of physical address space that might approach this in the") 
				print ("foreseeable future. Thus the 52-bit physical address provides ample room for expansion while not incurring the ")
				print ("cost of implementing full 64-bit physical addresses. Similarly, the 48-bit virtual address space was designed to ")
				print ("provide more than 65,000 (216) times the 32-bit limit of 4 GiB (4 × 10243 bytes), allowing room for later ")
				print ("expansion and incurring no overhead of translating full 64-bit addresses.")
				print (" ")
				print ("The Power ISA v3.0 allows 64 bits for an effective address, mapped to a segmented address with between 65 and 78 bits ")
				print ("allowed, for virtual memory, and, for any given processor, up to 60 bits for physical memory.[10]")
				print (" ")
				print ("The Oracle SPARC Architecture 2015 allows 64 bits for virtual memory and, for any given processor, between 40 and 56 ")
				print ("bits for physical memory.[11]")
				print (" ")
				print ("The ARM AArch64 Virtual Memory System Architecture allows 48 bits for virtual memory and, for any given processor, ")
				print ("from 32 to 48 bits for physical memory.[12]")
				more1 = input("64-bit data timeline")
				print (" ")
				print ("1961")
				print ("IBM delivers the IBM 7030 Stretch supercomputer, which uses 64-bit data words and 32- or 64-bit instruction words.")
				print ("1974")
				print ("Control Data Corporation launches the CDC Star-100 vector supercomputer, which uses a 64-bit word architecture ")
				print ("(prior CDC systems were based on a 60-bit architecture).")
				print ("International Computers Limited launches the ICL 2900 Series with 32-bit, 64-bit, and 128-bit two's complement integers;") 
				print ("64-bit and 128-bit floating point; 32-bit, 64-bit, and 128-bit packed decimal and a 128-bit accumulator register. The ")
				print ("architecture has survived through a succession of ICL and Fujitsu machines. The latest is the Fujitsu Supernova, which") 
				print ("emulates the original environment on 64-bit Intel processors.")
				print ("1976")
				print ("Cray Research delivers the first Cray-1 supercomputer, which is based on a 64-bit word architecture and will form the ")
				print ("basis for later Cray vector supercomputers.")
				print ("1983")
				print ("Elxsi launches the Elxsi 6400 parallel minisupercomputer. The Elxsi architecture has 64-bit data registers but a 32-bit ")
				print ("address space.")
				print ("1989")
				print ("Intel introduces the Intel i860 reduced instruction set computing (RISC) processor. Marketed as a ''64-Bit Microprocessot'', ")
				print ("it had essentially a 32-bit architecture, enhanced with a 3D graphics unit capable of 64-bit integer operations.[13]")
				print ("1993")
				print ("Atari introduces the Atari Jaguar video game console, which includes some 64-bit wide data paths in its architecture.[14]")
				print (" ")
				more1 = input("64-bit address timeline")
				print (" ")
				print ("1991")
				print ("MIPS Computer Systems produces the first 64-bit microprocessor, the R4000, which implements the MIPS III architecture, ")
				print ("the third revision of its MIPS architecture.[15] The CPU is used in SGI graphics workstations starting with the IRIS Crimson.")
				print ("Kendall Square Research deliver their first KSR1 supercomputer, based on a proprietary 64-bit RISC processor architecture ")
				print ("running OSF//1.")
				print ("1992")
				print ("Digital Equipment Corporation (DEC) introduces the pure 64-bit Alpha architecture which was born from the Prism project.[16]")
				print ("1994")
				print ("Intel announces plans for the 64-bit IA-64 architecture (jointly developed with Hewlett-Packard) as a successor to its ")
				print ("32-bit IA-32 processors. A 1998 to 1999 launch date was targeted.")
				print ("1995")
				print ("Sun launches a 64-bit SPARC processor, the UltraSPARC.[17] Fujitsu-owned HAL Computer Systems launches workstations based ")
				print ("on a 64-bit CPU, HAL's independently designed first-generation SPARC64. IBM releases the A10 and A30 microprocessors, ")
				print ("the first 64-bit PowerPC AS processors.[18] IBM also releases a 64-bit AS//400 system upgrade, which can convert the ")
				print ("operating system, database and applications.")
				print ("1996")
				print ("Nintendo introduces the Nintendo 64 video game console, built around a low-cost variant of the MIPS R4000. HP") 
				print ("releases the first implementation of its 64-bit PA-RISC 2.0 architecture, the PA-8000.[19]")
				print ("1998")
				print ("IBM releases the POWER3 line of full-64-bit PowerPC//POWER processors.[20]")
				print ("1999")
				print ("Intel releases the instruction set for the IA-64 architecture. AMD publicly discloses its set of 64-bit extensions to IA-32, ")
				print ("called x86-64 (later branded AMD64).")
				print ("2000")
				print ("IBM ships its first 64-bit z//Architecture mainframe, the zSeries z900. z//Architecture is a 64-bit version of the 32-bit ESA//390 ")
				print ("architecture, a descendant of the 32-bit System//360 architecture.")
				print ("2001")
				print ("Intel ships its IA-64 processor line, after repeated delays in getting to market. Now branded Itanium and targeting ")
				print ("high-end servers, sales fail to meet expectations.")
				print ("2003")
				print ("AMD introduces its Opteron and Athlon 64 processor lines, based on its AMD64 architecture which is the first x86-based ")
				print ("64-bit processor architecture. Apple also ships the 64-bit ''G5'' PowerPC 970 CPU produced by IBM. Intel maintains ")
				print ("that its Itanium chips would remain its only 64-bit processors.")
				print ("2004")
				print ("Intel, reacting to the market success of AMD, admits it has been developing a clone of the AMD64 extensions named IA-32e") 
				print ("(later renamed EM64T, then yet again renamed to Intel 64). Intel ships updated versions of its Xeon and Pentium 4 ")
				print ("processor families supporting the new 64-bit instruction set.")
				print ("VIA Technologies announces the Isaiah 64-bit processor.[21]")
				print ("2006")
				print ("Sony, IBM, and Toshiba begin manufacturing the 64-bit Cell processor for use in the PlayStation 3, servers, workstations,") 
				print ("and other appliances. Intel released Core 2 Duo as the first mainstream x86-64 processor for its mobile, desktop, and") 
				print ("workstation line. Prior 64-bit extension processor lines were not widely available in the consumer retail market ")
				print ("(most of 64-bit Pentium 4//D were OEM), 64-bit Pentium 4, Pentium D, and Celeron were not into mass production until late") 
				print ("2006 due to poor yield issue (most of good yield wafers were targeted at server and mainframe while mainstream still") 
				print ("remain 130 nm 32-bit processor line until 2006) and soon became low end after Core 2 debuted. AMD released their") 
				print ("first 64-bit mobile processor and manufactured in 90 nm.")
				print ("2011")
				print ("ARM Holdings announces ARMv8-A, the first 64-bit version of the ARM architecture.[22]")
				print ("2012")
				print ("ARM Holdings announced their Cortex-A53 and Cortex-A57 cores, their first cores based on their 64-bit architecture, on")
				print ("30 October 2012.[1][23]")
				print ("2013")
				print ("Apple announces the iPhone 5S, the first 64‑bit smartphone, which uses their A7 ARMv8-A-based system-on-a-chip.")
				print ("2014")
				print ("Google announces the Nexus 9, the first Android device to run on a 64-bit Tegra K1 processor.")
				print (" ")
				more1 = input("64-bit operating system timeline")
				print (" ")
				print ("1985")
				print ("Cray releases UNICOS, the first 64-bit implementation of the Unix operating system.[24]")
				print ("1993")
				print ("DEC releases the 64-bit DEC OSF//1 AXP Unix-like operating system (later renamed Tru64 UNIX) for its systems based on the ")
				print ("Alpha architecture.")
				print ("1994")
				print ("Support for the R8000 processor is added by Silicon Graphics to the IRIX operating system in release 6.0.")
				print ("1995")
				print ("DEC releases OpenVMS 7.0, the first full 64-bit version of OpenVMS for Alpha. First 64-bit Linux distribution for the") 
				print ("Alpha architecture is released.[25]")
				print ("1996")
				print ("Support for the R4x00 processors in 64-bit mode is added by Silicon Graphics to the IRIX operating system in release 6.2.")
				print ("1998")
				print ("Sun releases Solaris 7, with full 64-bit UltraSPARC support.")
				print ("2000")
				print ("IBM releases z//OS, a 64-bit operating system descended from MVS, for the new zSeries 64-bit mainframes; 64-bit Linux on z ")
				print ("Systems follows the CPU release almost immediately.")
				print ("2001")
				print ("Linux becomes the first OS kernel to fully support x86-64 (on a simulator, as no x86-64 processors had been released yet).[26]")
				print ("2001")
				print ("Microsoft releases Windows XP 64-Bit Edition for the Itanium's IA-64 architecture, although it was able to run 32-bit") 
				print ("applications through an execution layer.")
				print ("2003")
				print ("Apple releases its Mac OS X 10.3 ''Panther'' operating system which adds support for native 64-bit integer arithmetic on ")
				print ("PowerPC 970 processors.[27] Several Linux distributions release with support for AMD64. FreeBSD releases with support for AMD64.")
				print ("2005")
				print ("On January 4, Microsoft discontinues Windows XP 64-Bit Edition, as no PCs with IA-64 processors had been available since the previous")
				print ("September, and announces that it is developing x86-64 versions of Windows to replace it.[28] On January 31, ")
				print ("Sun releases Solaris 10 with support for AMD64 and EM64T processors. On April 29, Apple releases Mac OS X 10.4 ''Tiger'' ")
				print ("which provides limited support for 64-bit command-line applications on machines with PowerPC 970 processors; later versions ")
				print ("for Intel-based Macs supported 64-bit command-line applications on Macs with EM64T processors. On April 30, Microsoft releases ")
				print ("Windows XP Professional x64 Edition and Windows Server 2003 x64 Edition for AMD64 and EM64T processors.[29]")
				print ("2006")
				print ("Microsoft releases Windows Vista, including a 64-bit version for AMD64//EM64T processors that retains 32-bit compatibility. ")
				print ("In the 64-bit version, all Windows applications and components are 64-bit, although many also have their 32-bit versions ")
				print ("included for compatibility with plug-ins.")
				print ("2007")
				print ("Apple releases Mac OS X 10.5 ''Leopard'', which fully supports 64-bit applications on machines with PowerPC 970 or EM64T ")
				print ("processors.")
				print ("2009")
				print ("Microsoft releases Windows 7, which, like Windows Vista, includes a full 64-bit version for AMD64//Intel 64 processors; most")
				print ("new computers are loaded by default with a 64-bit version. It also releases Windows Server 2008 R2, which is the first 64-bit")			
				print ("only operating system released by Microsoft. Apple releases Mac OS X 10.6, ''Snow Leopard'', which ships with a 64-bit kernel ")
				print ("for AMD64//Intel64 processors, although only certain recent models of Apple computers will run the 64-bit kernel by default. ")
				print ("Most applications bundled with Mac OS X 10.6 are now also 64-bit.[27]")
				print ("2011")
				print ("Apple releases Mac OS X 10.7, ''Lion'', which runs the 64-bit kernel by default on supported machines. Older machines that ")
				print ("are unable to run the 64-bit kernel run the 32-bit kernel, but, as with earlier releases, can still run 64-bit applications;") 
				print ("Lion does not support machines with 32-bit processors. Nearly all applications bundled with Mac OS X 10.7 are now also ")
				print ("64-bit, including iTunes.")
				print ("2013")
				print ("Apple releases iOS 7, which, on machines with AArch64 processors, has a 64-bit kernel that supports 64-bit applications.")
				print ("2014")
				print ("Google releases Android Lollipop, the first version of the Android operating system with support for 64-bit processors.")
				print ("2017")
				print ("Apple releases iOS 11, supporting only machines with AArch64 processors. It has a 64-bit kernel that only supports ")
				print ("64-bit applications. 32-bit applications are no longer compatible.")
				print (" ")
				more1 = input("64-bit applications")
				print ("32-bit vs 64-bit")
				print (" ")
				print ("A change from a 32-bit to a 64-bit architecture is a fundamental alteration, as most operating systems must be ")
				print ("extensively modified to take advantage of the new architecture, because that software has to manage the actual ")
				print ("memory addressing hardware.[30] Other software must also be ported to use the new abilities; older 32-bit software ")
				print ("may be supported either by virtue of the 64-bit instruction set being a superset of the 32-bit instruction set, so ")
				print ("that processors that support the 64-bit instruction set can also run code for the 32-bit instruction set, or through ")
				print ("software emulation, or by the actual implementation of a 32-bit processor core within the 64-bit processor, as with") 
				print ("some Itanium processors from Intel, which included an IA-32 processor core to run 32-bit x86 applications. ")
				print ("The operating systems for those 64-bit architectures generally support both 32-bit and 64-bit applications.[31]")
				print (" ")
				print ("One significant exception to this is the AS//400, software for which is compiled into a virtual instruction set ")
				print ("architecture (ISA) called Technology Independent Machine Interface (TIMI); TIMI code is then translated to native") 
				print ("machine code by low-level software before being executed. The translation software is all that must be rewritten to move the") 
				print ("full OS and all software to a new platform, as when IBM transitioned the native instruction set for AS//400 from the older") 
				print ("32//48-bit IMPI to the newer 64-bit PowerPC-AS, codenamed Amazon. The IMPI instruction set was quite different from even") 
				print ("32-bit PowerPC, so this transition was even bigger than moving a given instruction set from 32 to 64 bits.")
				print (" ")
				print ("On 64-bit hardware with x86-64 architecture (AMD64), most 32-bit operating systems and applications can run with no ")
				print ("compatibility issues. While the larger address space of 64-bit architectures makes working with large data sets in ")
				print ("applications such as digital video, scientific computing, and large databases easier, there has been considerable ")
				print ("debate on whether they or their 32-bit compatibility modes will be faster than comparably priced 32-bit systems for other tasks.")
				print (" ")
				print ("A compiled Java program can run on a 32- or 64-bit Java virtual machine with no modification. The lengths and precision of all")
				print ("the built-in types, such as char, short, int, long, float, and double, and the types that can be used as array indices, are ")
				print ("specified by the standard and are not dependent on the underlying architecture. Java programs that run on a 64-bit Java") 
				print ("virtual machine have access to a larger address space.[32]")
				print (" ")
				print ("Speed is not the only factor to consider in comparing 32-bit and 64-bit processors. Applications such as multi-tasking, ")
				print ("stress testing, and clustering – for high-performance computing (HPC) – may be more suited to a 64-bit architecture when ")
				print ("deployed appropriately. For this reason, 64-bit clusters have been widely deployed in large organizations, ")
				print ("such as IBM, HP, and Microsoft.")
				print (" ")
				more1 = input("Summary:")
				print (" ")
				print ("A 64-bit processor performs best with 64-bit software.")
				print ("A 64-bit processor has backward compatibility and will handle most 32-bit software.")
				print ("A 32-bit processor is incompatible with 64-bit software.")
				print (" ")
				more1 = input("Pros and cons")
				print (" ")
				print ("A common misconception is that 64-bit architectures are no better than 32-bit architectures unless the computer has more ")
				print ("than 4 GiB of random-access memory.[33] This is not entirely true:")
				print (" ")
				print ("Some operating systems and certain hardware configurations limit the physical memory space to 3 GiB on IA-32 systems, ")
				print ("due to much of the 3–4 GiB region being reserved for hardware addressing; see 3 GB barrier; 64-bit architectures can ")
				print ("address far more than 4 GiB. However, IA-32 processors from the Pentium Pro onward allow a 36-bit physical memory ")
				print ("address space, using Physical Address Extension (PAE), which gives a 64 GiB physical address range, of which up to ")
				print ("62 GiB may be used by main memory; operating systems that support PAE may not be limited to 4 GiB of physical memory,") 
				print ("even on IA-32 processors. However, drivers and other kernel mode software, more so older versions, may be ")
				print ("incompatible with PAE; this has been cited as the reason for 32-bit versions of Microsoft Windows being ")
				print ("limited to 4 GiB of physical RAM[34] (although the validity of this explanation has been disputed[35]).")
				print ("Some operating systems reserve portions of process address space for OS use, effectively reducing the total address space ")
				print ("available for mapping memory for user programs. For instance, 32-bit Windows reserves 1 or 2 GiB (depending on the settings) ")
				print ("of the total address space for the kernel, which leaves only 3 or 2 GiB (respectively) of the address space available for user ")
				print ("mode. This limit is much higher on 64-bit operating systems.")
				print ("Memory-mapped files are becoming more difficult to implement in 32-bit architectures as files of over 4 GiB become more common;") 
				print ("such large files cannot be memory-mapped easily to 32-bit architectures, as only part of the file can be mapped into the ")
				print ("address space at a time, and to access such a file by memory mapping, the parts mapped must be swapped into and out of the")
				print ("address space as needed. This is a problem, as memory mapping, if properly implemented by the OS, is one of the most efficient") 
				print ("disk-to-memory methods.")
				print ("Some 64-bit programs, such as encoders, decoders and encryption software, can benefit greatly from 64-bit registers,[citation needed]")
				print ("while the performance of other programs, such as 3D graphics-oriented ones, remains unaffected when switching from a ")
				print ("32-bit to a 64-bit environment.[citation needed]")
				print ("Some 64-bit architectures, such as x86-64, support more general-purpose registers than their 32-bit counterparts ")
				print ("(although this is not due specifically to the word length). This leads to a significant speed increase for tight ")
				print ("loops since the processor does not have to fetch data from the cache or main memory if the data can ")
				print ("fit in the available registers.")
				print (" ")
				print ("Example in C:")
				print (" ")
				print ("int a, b, c, d, e;")
				print ("for (a=0; a<100; a++)")
				print ("{")
				print ("b = a;")
				print ("c = b;")
				print ("d = c;")
				print ("e = d;")
				print ("}")
				print (" ")
				print ("If a processor only has the ability to keep two or three values or variables in registers, it would need to move some values") 
				print ("between memory and registers to be able to process variables d and e also; this is a process that takes many CPU cycles. ")
				print ("A processor that is able to hold all values and variables in registers can loop through them with no need to move data ")
				print ("between registers and memory for each iteration. This behavior can easily be compared with virtual memory, although any ")
				print ("effects are contingent on the compiler.")
				print (" ")
				print ("The main disadvantage of 64-bit architectures is that, relative to 32-bit architectures, the same data occupies more")
				print ("space in memory (due to longer pointers and possibly other types, and alignment padding). This increases the memory") 
				print ("requirements of a given process and can have implications for efficient processor cache use. Maintaining a") 
				print ("partial 32-bit model is one way to handle this, and is in general reasonably effective. For example, the") 
				print ("z//OS operating system takes this approach, requiring program code to reside in 31-bit address spaces")
				print ("(the high order bit is not used in address calculation on the underlying hardware platform) while data") 
				print ("objects can optionally reside in 64-bit regions. Not all such applications require a large address") 
				print ("space or manipulate 64-bit data items, so these applications do not benefit from these features.")
				more1 = input("Software availability")
				print (" ")
				print ("x86-based 64-bit systems sometimes lack equivalents of software that is written for 32-bit architectures. The most severe ")
				print ("problem in Microsoft Windows is incompatible device drivers for obsolete hardware. Most 32-bit application software can ")
				print ("run on a 64-bit operating system in a compatibility mode, also termed an emulation mode, e.g., Microsoft WoW64 Technology ")
				print ("for IA-64 and AMD64. The 64-bit Windows Native Mode[36] driver environment runs atop 64-bit NTDLL.DLL, which cannot call") 
				print ("32-bit Win32 subsystem code (often devices whose actual hardware function is emulated in user mode software, like ")
				print ("Winprinters). Because 64-bit drivers for most devices were unavailable until early 2007 (Vista x64), using a 64-bit ")
				print ("version of Windows was considered a challenge. However, the trend has since moved toward 64-bit computing, more so as ")
				print ("memory prices dropped and the use of more than 4 GB of RAM increased. Most manufacturers started to provide both 32-bit ")
				print ("and 64-bit drivers for new devices, so unavailability of 64-bit drivers ceased to be a problem. 64-bit drivers were not ")
				print ("provided for many older devices, which could consequently not be used in 64-bit systems.")
				print (" ")
				print ("Driver compatibility was less of a problem with open-source drivers, as 32-bit ones could be modified for 64-bit use. ")
				print ("Support for hardware made before early 2007, was problematic for open-source platforms,[citation needed] due to the ")
				print ("relatively small number of users.")
				print (" ")
				print ("64-bit versions of Windows cannot run 16-bit software. However, most 32-bit applications will work well. ")
				print ("64-bit users are forced to install a virtual machine of a 16- or 32-bit operating system to run 16-bit applications.[37]")
				print (" ")
				print ("Mac OS X 10.4 ''Tiger'' and Mac OS X 10.5 ''Leopard'' only had a 32-bit kernel, but they can run 64-bit user-mode code on ")
				print ("64-bit processors. Mac OS X 10.6 ''Snow Leopard'' had both 32- and 64-bit kernels, and, on most Macs, used the 32-bit kernel ")
				print ("even on 64-bit processors. This allowed those Macs to support 64-bit processes while still supporting 32-bit device drivers;") 
				print ("although not 64-bit drivers and performance advantages that can come with them. Mac OS X 10.7 ''Lion'' ran with a 64-bit ")
				print ("kernel on more Macs, and OS X 10.8 ''Mountain Lion'' and later macOS releases only have a 64-bit kernel. On systems with ")
				print ("64-bit processors, both the 32- and 64-bit macOS kernels can run 32-bit user-mode code, and all versions of macOS include") 
				print ("32-bit versions of libraries that 32-bit applications would use, so 32-bit user-mode software for macOS will ")
				print ("run on those systems.")
				print (" ")
				print ("Linux and most other Unix-like operating systems, and the C and C++ toolchains for them, have supported 64-bit ")
				print ("processors for many years. Many applications and libraries for those platforms are open source, written in C and ")
				print ("C++, so that if they are 64-bit-safe, they can be compiled into 64-bit versions. This source-based distribution model, ")
				print ("with an emphasis on frequent releases, makes availability of application software for those operating systems less of an issue.")
				more1 = input("64-bit data models")
				print (" ")
				print ("In 32-bit programs, pointers and data types such as integers generally have the same length. This is not necessarily true ") 
				print ("64-bit machines.[38][39][40] Mixing data types in programming languages such as C and its descendants such as C++ and ")
				print ("Objective-C may thus work on 32-bit implementations but not on 64-bit implementations.")
				print (" ")
				print ("In many programming environments for C and C-derived languages on 64-bit machines, int variables are still 32 bits wide, but ")
				print ("long integers and pointers are 64 bits wide. These are described as having an LP64 data model. Another alternative is the ")
				print ("ILP64 data model in which all three data types are 64 bits wide, and even SILP64 where short integers are also 64 ")
				print ("bits wide.[41] However, in most cases the modifications required are relatively minor and straightforward, and many ")
				print ("well-written programs can simply be recompiled for the new environment with no changes. Another alternative is the ")
				print ("LLP64 model, which maintains compatibility with 32-bit code by leaving both int and long as 32-bit. LL refers to the long") 
				print ("long integer type, which is at least 64 bits on all platforms, including 32-bit environments.")
				print ("64-bit data models Data model 	short (integer) 	int 	long (integer) 	long long 	pointers,")
				print ("size_t 	Sample operating systems")
				print ("LLP64,")
				print ("IL32P64 	16 	32 	32 	64 	64 	Microsoft Windows (x86-64 and IA-64) using Visual C++; and MinGW")
				print ("LP64")
				print ("I32LP64 	16 	32 	64 	64 	64 	Most Unix and Unix-like systems, e.g., Solaris, Linux, BSD, macOS. Windows when using Cygwin; z//OS")
				print ("ILP64 	16 	64 	64 	64 	64 	HAL Computer Systems port of Solaris to the SPARC64")
				print ("SILP64 	64 	64 	64 	64 	64 	Classic UNICOS[41] (versus UNICOS//mp, etc.)")
				print (" ")
				print ("Many 64-bit platforms today use an LP64 model (including Solaris, AIX, HP-UX, Linux, macOS, BSD, and IBM z//OS). ")
				print ("Microsoft Windows uses an LLP64 model. The disadvantage of the LP64 model is that storing a long into an int may overflow. ")
				print ("On the other hand, converting a pointer to a long will “work” in LP64. In the LLP64 model, the reverse is true. These are not ")
				print ("problems which affect fully standard-compliant code, but code is often written with implicit assumptions about the widths of") 
				print ("data types. C code should prefer (u)intptr_t instead of long when casting pointers into integer objects.")
				print (" ")
				print ("A programming model is a choice made to suit a given compiler, and several can coexist on the same OS. However, ")
				print ("the programming model chosen as the primary model for the OS application programming interface (API) typically dominates.")
				print (" ")
				print ("Another consideration is the data model used for device drivers. Drivers make up the majority of the operating system code ")
				print ("in most modern operating systems[citation needed] (although many may not be loaded when the operating system is running). ")
				print ("Many drivers use pointers heavily to manipulate data, and in some cases have to load pointers of a certain size into the")
				print ("hardware they support for direct memory access (DMA). As an example, a driver for a 32-bit PCI device asking the device to ")
				print ("DMA data into upper areas of a 64-bit machine's memory could not satisfy requests from the operating system to load data ")
				print ("from the device to memory above the 4 gibibyte barrier, because the pointers for those addresses would not fit into the ")
				print ("DMA registers of the device. This problem is solved by having the OS take the memory restrictions of the device into") 
				print ("account when generating requests to drivers for DMA, or by using an input–output memory management unit (IOMMU).")
				more1 = input("Current 64-bit architectures")
				print (" ")
				print ("As of May 2018, 64-bit architectures for which processors are being manufactured include:")
				print (" ")
				print ("The 64-bit extension created by AMD to Intel's x86 architecture (later licensed by Intel); commonly termed x86-64, AMD64,") 
				print ("or x64:")
				print ("AMD's AMD64 extensions (used in Athlon 64, Opteron, Sempron, Turion 64, Phenom, Athlon II, Phenom II, FX, Ryzen, and Epyc ")
				print ("processors)")
				print ("Intel's Intel 64 extensions, used in Intel Core 2-i3-i5-i7-i9, some Atom, and newer Celeron, Pentium, and Xeon processors")
				print ("Intel's K1OM architecture, a variant of Intel 64 with no CMOV, MMX, and SSE instructions, used in Xeon Phi coprocessors,") 
				print ("binary incompatible with x86-64 programs")
				print ("VIA Technologies' 64-bit extensions, used in the VIA Nano processors")
				print ("IBM's Power Architecture:")
				print ("IBM's POWER4, POWER5, POWER6, POWER7, POWER8, POWER9, and IBM A2 processors")
				print ("SPARC V9 architecture:")
				print ("Oracle's M8 and S7 processors")
				print ("Fujitsu's SPARC64 XII and SPARC64 XIfx processors")
				print ("IBM's z//Architecture, a 64-bit version of the ESA//390 architecture, used in IBM's eServer zSeries and System z mainframes:")
				print ("IBM z13 and z14")
				print ("Hitachi AP8000E")
				print ("HP-Intel's IA-64 architecture:")
				print ("Intel's Itanium processors")
				print ("MIPS Technologies' MIPS64 architecture")
				print ("ARM Holdings' AArch64 architecture")
				print ("Elbrus architecture:")
				print ("Elbrus-8S")
				print ("NEC SX architecture")
				print ("SX-Aurora TSUBASA")
				print ("RISC-V")
				print (" ")
				print ("Most architectures of 64 bits that are derived from the same architecture of 32 bits can execute code written for the ")
				print ("32-bit versions natively, with no performance penalty.[citation needed] This kind of support is commonly called bi-arch ")
				print ("support or more generally multi-arch support. ")
				print (" ")
				noMore = input("Press [ENTER] key to exit")