			if WikIDSelect == 10000:
				print ("Update log")
				print ("For Ucalc")
				more1 = input("Read more? [ENTER]")
				print ("UCalc pre-alpha CLI client 1")
				print ("\nThis is the very first version of the UCalc client")
				print ("It contains many features, but has some odd bugs")
				print ("There was only 1 pre-alpha version of this program, and was a simple private demonstration build to make sure all the added features workede")
				print ("It was moved to the alpha phase when it was deemed stable, and acquired a working update log")
				print ("Pre-alpha 1 added the following features:")
				print ("<*> Added Main Menu")
				print ("<*> Added language setup [ONLY ENGLISH]")
				print ("<*> processor setup")
				print ("<*> ID table for calculation operations")
				print ("<*> Random number generator (unstable, but still works)")
				print ("<*> Calculator room (unstable, but still runs)")
				print ("<*> Added modular division calculator")
				print ("<*> Added addition calculator")
				print ("<*> Added subtraction calculator")
				print ("<*> Added multiplication calculator")
				print ("<*> Added division calculator")
				print ("<*> Added greater than calculator")
				print ("<*> Added count 100,000 digits of Pi (easter egg)")
				print ("<*> Added RGB calculator")
				print ("<*> Added addition calculator")
				print ("<*> Added subtraction calculator")
				print ("<*> Added multiplication calculator")
				print ("<*> Added division calculator")
				print ("<*> Added wiki page (with no entries at the moment")
				print ("That is it for pre-alpha 1!")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha client 1")
				print ("\nUCalc jumped to the Alpha phase because of 2 reasons:")
				print ("<*> The program works in a stable state over 50% of the time")
				print ("<*> The update log was released")
				print ("<*> Added speed-dial calculator (the public calculator)")
				print ("<*> Increased documentation")
				print ("<*> Added more organized ID chart for math operations (it can now fit perfectly on a 1280x720 screen)")
				print ("<*> Fixed 3 critical bugs that prevent certain operations from running, and causing the program to crash")
				print ("<*> Added in new operaitons (Speed-dial only)")
				print ("<*> Added manufacturer list")
				print ("<*> Added boot-screens (modify to unlock)")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha client 2")
				print ("<*> increased documentation")
				print ("<*> added vote counter")
				print ("<*> added memory calculator")
				print ("<*> added game catalog")
				print ("Why didn't it go to beta? Not all the planned features are here yet, and it is still unstable at times")
				print ("Alpha 1 added the following features:")
				print ("<*> a working update log")
				print ("That is it for alpha 2!")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.00")
				print ("Created: November 12th 2018")
				print ("Last modified: November 13th 2018")
				print ("Total size:	385 KB (394,731 bytes) or 394 KB (394,731 bytes) ")
				print ("File type: .py (Python file)") 
				print ("Description:\nThis was supposed to be another huge build up until something really bad happened. During the development, our IDE crashed, and everything was lost. We") 
				print ("The development of Alpha 3 was abandoned, with very little change, and the UCalc team moved on to a new Alpha 3 series. To prevent future data loss, every")
				print ("Time the program was saved, we would create a new version. It was slightly memory consuming, but it helped development continue smoothly")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.01")
				print ("Alpha 3.01")
				print ("Created: November 13th 2018")
				print ("Last modified: November 13th 2018") 
				print ("Total size: 385 KB (394,904 bytes) OR 394 KB (394,904 bytes)") 
				print ("File type: .py (Python file) ")
				print ("Description:\nThis is the first version of the Alpha 3 series. It introduced minor changes and operates as a restore point in case the next version were to fail")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.02")
				print ("Alpha 3.02 ")
				print ("Created: November 13th 2018 ")
				print ("Last modified: November 13th 2018") 
				print ("Total size: 385 KB (395,117 bytes) or 395 KB (395,117 bytes) ")
				print ("File type: .py (Python file)  ")
				print ("Description: ")
				print ("Very brief changes to the design, acts as a restore point for the next version ")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.03")
				print ("Alpha 3.03")
				print ("Created: November 13th 2018")
				print ("Last modified: November 13th 2018 ")
				print ("Total size: 386 KB (395,578 bytes) or 395 KB (395,578 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Slowly adding back the lost features from an unexpected wipe")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.04")
				print ("Alpha 3.04")
				print ("Created: November 13th 2018")
				print ("Last modified: November 13th 2018")
				print ("Total size: 386 KB (395,852 bytes) or 395 KB (395,852 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Continuing to add back lost features")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.05")
				print ("Alpha 3.05")
				print ("Created: November 13th 2018")
				print ("Last modified: November 13th 2018")
				print ("Total size: 386 KB (395,962 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Added in file manager (not yet fully functional")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.06")
				print ("Alpha 3.06")
				print ("Created: November 13th 2018")
				print ("Last modified: November 13th 2018")
				print ("Total size: 387 KB (397,073 bytes) or 397 KB (397,073 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Added in a DNA screensaver, and updated the settings menu + updated the file manager")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.07")
				print ("Alpha 3.07")
				print ("Created: November 13th 2018 ")
				print ("Last modified: November 13th 2018")
				print ("Total size: 388 KB (398,202 bytes) or 398 KB (398,202 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Minor changes to script")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.08")
				print ("Alpha 3.08")
				print ("Created: November 13th 2018 ")
				print ("Last modified: November 13th 2018")
				print ("Total size: 390 KB (399,674 bytes) or 399 KB (399,674 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Added and started working on the Roman Numeral calculator")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.09")
				print ("Alpha 3.09")
				print ("Created: November 13th 2018")
				print ("Last modified: November 13th 2018 ")
				print ("Total size: 390 KB (400,210 bytes) or 400 KB (400,210 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Added the grade calculator, and started working on it ")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.10")
				print ("Alpha 3.10")
				print ("Created: November 13th 2018")
				print ("Last modified: November 13th 2018")
				print ("Total size: 392 KB (401,862 bytes) or 401 KB (401,862 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Updated Roman numeral calculator. It can now convert numbers to roman numerals up to 50. Added the IQ calculator (not yet functional) ")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.11")
				print ("Alpha 3.11")
				print ("Created: November 13th 2018")
				print ("Last modified: November 13th 2018")
				print ("Total size: 393 KB (403,016 bytes) or 403 KB (403,016 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Updated Roman Numeral calculator. It can now calculate Roman numerals up to 70")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.12")
				print ("Alpha 3.12")
				print ("Created: November 13th 2018 ")
				print ("Last modified: November 13th 2018")
				print ("Total size: 395 KB (404,788 bytes) or 404 KB (404,788 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Another update to the Roman numeral calculator. It can now calculate Roman numerals up to 100")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.13")
				print ("Alpha 3.13")
				print ("Created: November 13th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 395 KB (405,087 bytes) or 405 KB (405,087 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Minor changes to script")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.14")
				print ("Alpha 3.14")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 396 KB (405,515 bytes) or 405 KB (405,515 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Added more documentation")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.15")
				print ("Alpha 3.15")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 396 KB (405,521 bytes) or 405 KB (405,521 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Minor grammar & syntax fixes")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.16")
				print ("Alpha 3.16")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 396 KB (406,361 bytes) or 406 KB (406,361 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Added T.O.U (Terms Of Use) + Changes to the grade calculator")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.17")
				print ("Alpha 3.17")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 397 KB (406,551 bytes) or 406 KB (406,551 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Changes to the grade calculator")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.18")
				print ("Alpha 3.18")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 398 KB (408,286 bytes) or 408 KB (408,286 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Big update to the grade calculator")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.19")
				print ("Alpha 3.19")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 463 KB (474,608 bytes) or 474 KB (474,608 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Added in Wikipedia articles for certain topics, currently not python-ified, so the program doesn't work now")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.20")
				print ("Alpha 3.20")
				print ("Created: November 14th 2018 ")
				print ("Last modified: November 14th 2018")
				print ("Total size: 463 KB (474,840 bytes) or 474 KB (474,840 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Minor changes to the Roman numeral calculator. Boundaries have been set. The range is 1-255. Anything less or more than that will not work, and will be rejected")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.21")
				print ("Alpha 3.21")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018 ")
				print ("Total size: 467 KB (478,305 bytes) or 479 KB (478,305 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Changes to the roman numeral calculator. Can count in the 200-255 range, but lots of numbers are missing. The placeholders for the max value are coming in")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.22")
				print ("Alpha 3.22")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 469 KB (481,248 bytes) or 481 KB (481,248 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Changes to the roman numeral calculator. All values between 1-255 are accepted except for 151-199. Wiki pages have been commented out temporarily so the program can run")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.23")
				print ("Alpha 3.23")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018 ")
				print ("Total size: 471 KB (483,175 bytes) or 483 KB (483,175 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Almost finished the roman numeral calculator. However, it cannot ouput values between 183 and 199. We ran out of time, and we had to make an emergency save")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.24")
				print ("Alpha 3.24")
				print ("Created: November 14th 2018 ")
				print ("Last modified: November 14th 2018")
				print ("Total size: 472 KB (484,214 bytes) or 484 KB (484,214 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Finished the roman numeral calculator. For now, it is just going to be ran in 8 bit mode. It would take A LOT of work to make it go up to a 16 or 12 bit value")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.25")
				print ("Alpha 3.25")
				print ("Created: November 14th 2018 ")
				print ("Last modified: November 14th 2018 ")
				print ("Total size: 473 KB (484,841 bytes) OR 484 KB (484,841 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Added grading table to the grade checker ")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.26")
				print ("Alpha 3.26")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018 ")
				print ("Total size: 474 KB (486,173 bytes) or 486 KB (486,173 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Began to make the Wiki article about IQ python compatible. That task is currently incomplete, so the program doesn't function")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.27")
				print ("Alpha 3.27")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 475 KB (486,958 bytes) or 486 KB (486,958 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Still making the document about IQ compatible with python. This is going to take a while")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.28")
				print ("Alpha 3.28")
				print ("Created: November 14th 2018 ")
				print ("Last modified: November 14th 2018")
				print ("Total size: 476 KB (487,491 bytes) or 487 KB (487,491 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Continuing to work on the IQ document conversion")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.29")
				print ("Alpha 3.29")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 476 KB (488,258 bytes) or 488 KB (488,258 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Brief update to the Python conversion of the IQ document")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.30")
				print ("Alpha 3.30")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 478 KB (490,009 bytes) 490 KB (490,009 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Some more work inputting the IQ document")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.31")
				print ("Alpha 3.31")
				print ("Created: November 14th 2018")
				print ("Last modified: November 14th 2018")
				print ("Total size: 481 KB (492,863 bytes) or 492 KB (492,863 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Heavy progress into converting the IQ document. It is almost readable now")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.32")
				print ("Alpha 3.32")
				print ("Created: November 14th 2018 ")
				print ("Last modified: November 15th 2018 ")
				print ("Total size: 483 KB (494,692 bytes) or 494 KB (494,692 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("More progress in converting the IQ document")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.33")
				print ("Alpha 3.33")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018 ")
				print ("Total size: 484 KB (496,238 bytes) or 496 KB (496,238 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Even more progress in converting the document")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.34")
				print ("Alpha 3.34")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018")
				print ("Total size: 485 KB (497,368 bytes) or 497 KB (497,368 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Finished importing the IQ document")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.35")
				print ("Alpha 3.35")
				print ("Created: November 15th 2018 ")
				print ("Last modified: November 15th 2018")
				print ("Total size: 487 KB (499,657 bytes) or 499 KB (499,657 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Minor script changes")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.36")
				print ("Alpha 3.36")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018")
				print ("Total size: 495 KB (507,053 bytes) or 507 KB (507,053 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Added in Wiki documentation on Bit Slicing")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCaLc 3.37")
				print ("Alpha 3.37")
				print ("Created: November 15th 2018 ")
				print ("Last modified: November 15th 2018")
				print ("Total size: 501 KB (513,812 bytes) or 513 KB (513,812 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Added in Wiki documentation on 4 bit computing")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.38")
				print ("Alpha 3.38")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018")
				print ("Total size: 502 KB (514,481 bytes) or 514 KB (514,481 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Minor script changes")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.39")
				print ("Alpha 3.39")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018")
				print ("Total size: 504 KB (516,642 bytes) or 516 KB (516,642 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Minor script changes")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.40")
				print ("Alpha 3.40")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018 ")
				print ("Total size: 590 KB (604,322 bytes) or 604 KB (604,322 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Added documentation for 8 bit, 12 bit, 16 bit, 18 bit, 21 bit, 24 bit, 26 bit, 31 bit, 32 bit, 48 bit, 60 bit, 64 bit, 128 bit, 256 bit, and 512 bit computing, documents have to be converted to python format. For now, the build is not functional")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.41")
				print ("Alpha 3.41")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018 ")
				print ("Total size: 590 KB (604,603 bytes) or 604 KB (604,603 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Minor changes, as we had to make an emergency save")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.42")
				print ("Alpha 3.42")
				print ("Created: November 15th 2018 ")
				print ("Last modified: November 15th 2018")
				print ("Total size: 590 KB (604,726 bytes) or 604 KB (604,726 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("More minor changes, as there was another emergency save")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.43")
				print ("Alpha 3.43")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018")
				print ("Total size: 590 KB (605,137 bytes) or 605 KB (605,137 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("More updates to converting the newer documents into python format")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.44")
				print ("Alpha 3.44")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018")
				print ("Total size: 591 KB (606,044 bytes) or 606 KB (606,044 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("More work into converting the newer documents into python format")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.45")
				print ("Alpha 3.45")
				print ("Created: November 15th 2018 ")
				print ("Last modified: ")
				print ("Total size: 593 KB (607,486 bytes) or 607 KB (607,486 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Even more work on converting the newer documents into python format")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.46")
				print ("Alpha 3.46")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018 ")
				print ("Total size: 594 KB (608,384 bytes) or 608 KB (608,384 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("More work on converting the newer documents into python format")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.47")
				print ("Alpha 3.47")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018 ")
				print ("Total size: 594 KB (608,800 bytes) or 608 KB (608,800 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Small amount of work put into the project before this save, getting tired of working on this today")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.48")
				print ("Alpha 3.48")
				print ("Created: November 15th 2018")
				print ("Last modified: November 15th 2018")
				print ("Total size: 596 KB (611,062 bytes) or 611 KB (611,062 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Minor amount of work put into converting the newer documents into python format for this build, as I wanted to take a break from the project for the day")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.49")
				print ("Alpha 3.49")
				print ("Created: November 15th 2018")
				print ("Last modified: November 16th 2018")
				print ("Total size: 598 KB (613,224 bytes) or 613 KB (613,224 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Another day, another 1000 lines of code, minor changes have been made to the converting process of the Wiki computing documents")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.50")
				print ("Alpha 3.50")
				print ("Created: November 16th 2018")
				print ("Last modified: November 16th 2018")
				print ("Total size: 600 KB (615,177 bytes) or 615 KB (615,177 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("More work put into the plain text to python document conversion, it is getting close to completion now")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.51")
				print ("Alpha 3.51")
				print ("Created: November 16th 2018")
				print ("Last modified: November 16th 2018")
				print ("Total size: 604 KB (618,802 bytes) or 618 KB (618,802 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Almost finished converting the documents to python, some changes need to be made now")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.52")
				print ("Alpha 3.52")
				print ("Created: November 16th 2018")
				print ("Last modified: November 16th 2018 ")
				print ("Total size: 605 KB (619,528 bytes) or 619 KB (619,528 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("More documentation conversion work")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.53")
				print ("Alpha 3.53")
				print ("Created: November 16th 2018 ")
				print ("Last modified: November 16th 2018 ")
				print ("Total size: 609 KB (624,077 bytes) or 624 KB (624,077 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("New calculator modes being added: ANSI translator, credit/debit card maker, and Windows product key generator. The ANSI calculator is the first mode to include a class. It isn't very useful however, it is just a test of using classes in Python. The other 2 features will start development soon")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.54")
				print ("Alpha 3.54")
				print ("Created: November 16th 2018")
				print ("Last modified: November 16th 2018")
				print ("Total size: 616 KB (630,844 bytes) or 630 KB (630,844 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Working on documentation conversion again")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.55")
				print ("Alpha 3.55")
				print ("Created: November 16th 2018")
				print ("Last modified: November 16th 2018 ")
				print ("Total size: 618 KB (633,089 bytes) or 633 KB (633,089 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Starting to add finishing touchings on computing articles")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.56")
				print ("Alpha 3.56")
				print ("Created: November 16th 2018 ")
				print ("Last modified: November 17th 2018")
				print ("Total size: 625 KB (640,391 bytes) or 640 KB (640,391 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Continuing to make the program bootable again")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.57")
				print ("Alpha 3.57")
				print ("Created: November 17th 2018")
				print ("Last modified: November 17th 2018")
				print ("Total size: 630 KB (645,346 bytes) or 645 KB (645,346 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Adding the finishing touchings on the articles part 1 of 2")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.58")
				print ("Alpha 3.58")
				print ("Created: November 17th 2018")
				print ("Last modified: November 17th 2018 ")
				print ("Total size: 630 KB (645,894 bytes) or 645 KB (645,894 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Adding the finishing touchings on the articles part 2 of 2")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.59")
				print ("Alpha 3.59")
				print ("Created: November 17th 2018")
				print ("Last modified: November 17th 2018 ")
				print ("Total size: 642 KB (658,141 bytes) or 658 KB (658,141 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("After finishing up development on some features that required bug fixing, all the bug fixes finally occurred. This build is the first one in many to be able to ")
				print ("To actually function. Versions will continue to be made, and if they stop functioning again, another repair build will occur")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.60")
				print ("Alpha 3.60")
				print ("Created: November 17th 2018")
				print ("Last modified: November 17th 2018 ")
				print ("Total size: 642 KB (658,207 bytes) or 658 KB (658,207 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("This was a brief update after the big repair update. All it did was add comments to the internal code for the Windows/Microsoft product key generator")
				print ("We put in the list of all the product keys, and the link to where we got them")
				print ("Nothing else was done in this build")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.61")
				print ("Alpha 3.61")
				print ("Created: November 17th 2018 ")
				print ("Last modified: November 17th 2018 ")
				print ("Total size: 650 KB (665,745 bytes) or 665 KB (665,745 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Another small brief update with a few changes, such as updating the version number at startup, adding ASCII art design around the main menu settings, and adding")
				print ("An update manager")
				print ("Update manager is not yet fully functional due to the programs current level")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.62")
				print ("Alpha 3.62")
				print ("Created: November 17th 2018 ")
				print ("Last modified: November 18th 2018 ")
				print ("Total size: 693 KB (710,468 bytes) or 710 KB (710,468 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("This is a new update that improves the distance calculator. Not much was added other than that, but the distance calculator can now do more different types of distant calculations")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.63")
				print ("Alpha 3.63")
				print ("Created: November 18th 2018")
				print ("Last modified: November 18th 2018")
				print ("Total size: 739 KB (757,184 bytes) or 757 KB (757,184 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("This was another update for the distance calculator, that lets it do more distant calculations. This build was cut short so that we could test floating integers and decimals to improve the accuracy of the output")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.64")
				print ("Alpha 3.64")
				print ("Created: November 18th 2018")
				print ("Last modified: November 18th 2018")
				print ("Total size: 742 KB (759,846 bytes) or 759 KB (759,846 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("This was a big update for the distance calculator. We changed all the int values to float values. Now you can see every digit, and decimals are now accepted, despite it saying ''NO DECIMALS'' that will be fixed in a later build")
				print ("Fun fact: when converting all integers to floating decimals, we used the find and replace tool. We went and found all 'int' listed and replaced it with 'float' we ran into a funny unexpected issue that we didn't take into account, that it would also alter the print function. It switched 'print' to 'prfloat' luckily, we were easily able to reverse this, and the build is still functional")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.65")
				print ("Alpha 3.65")
				print ("Created: November 18th 2018")
				print ("Last modified: November 19th 2018")
				print ("Total size: 764 KB (783,283 bytes) or 783 KB (783,283 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("This is another update to finish up the distance calculator. In this build however, another huge goal was met, getting more lines than the first version of Linux")
				print ("The first version of Linux had 10,239 lines of code. Version 3.65 has 10,289 lines")
				print ("Our next goal is to reach 20000 lines of code")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.66")
				print ("Alpha 3.66")
				print ("Created: November 19th 2018")
				print ("Last modified: November 19th 2018")
				print ("Total size: 778 KB (797,477 bytes) or 797 KB (797,477 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("More compatibility added for distance calculator")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.67")
				print ("Alpha 3.67")
				print ("Created: November 19th 2018")
				print ("Last modified: November 19th 2018")
				print ("Total size: 787 KB (806,653 bytes) or 806 KB (806,653 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description:")
				print ("Minor update to the distance calculator, added measurement for miles")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.68")
				print ("Alpha 3.68")
				print ("Created: November 19th 2018")
				print ("Last modified: November 19th 2018 ")
				print ("Total size: 796 KB (816,015 bytes) or 816 KB (816,015 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Minor update that adds many placeholders for the alpha 3 series of development.")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.69")
				print ("Alpha 3.69")
				print ("Created: November 19th 2018")
				print ("Last modified: November 19th 2018")
				print ("Total size: 808 KB (828,146 bytes) or 828 KB (828,146 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("This was an experimental build to add multiple languages into UCalc. English is still fully supported, but now there is an opening for more languages. No new languages were added. There is now a new boot screen, ASCII art of the earth, which stands for 'International Language support'")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.70")
				print ("Alpha 3.70")
				print ("Created: November 19th 2018")
				print ("Last modified: November 19th 2018")
				print ("Total size: 812 KB (832,414 bytes) or 832 KB (832,414 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Began to add support for new languages. The text ''CALC'' was added to the language boot screen, along with partial support for Russian")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.71")
				print ("Alpha 3.71")
				print ("Created: November 19th 2018")
				print ("Last modified: November 19th 2018")
				print ("Total size: 813 KB (832,530 bytes) or 832 KB (832,530 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Began to add support for 6 new languages: German, Russian, Swedish, French, Chinese, and Japanese, ")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.72")
				print ("Alpha 3.72")
				print ("Created: November 19th 2018")
				print ("Last modified: November 19th 2018")
				print ("Total size: 838 KB (858,548 bytes) or 858 KB (858,548 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("1 line added")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.73")
				print ("Alpha 3.73")
				print ("Created: November 19th 2018")
				print ("Last modified: November 19th 2018")
				print ("Total size: 847 KB (868,227 bytes) or 868 KB (868,227 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Changes to the distance calculator")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.74")
				print ("Alpha 3.74")
				print ("Created: November 19th 2018")
				print ("Last modified: November 19th 2018")
				print ("Total size: 860 KB (880,772 bytes) or 880 KB (880,772 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("More changes to the distance calculator")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.75")
				print ("Alpha 3.75")
				print ("Created: November 19th 2018")
				print ("Last modified: November 20th 2018")
				print ("Total size: 871 KB (892,762 bytes) or 892 KB (892,762 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Changes to the distance calculator, adding the last 5 measurement units")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.76")
				print ("Alpha 3.76")
				print ("Created: November 20th 2018")
				print ("Last modified: November 20th 2018")
				print ("Total size: ")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("No description available")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.77")
				print ("Alpha 3.77")
				print ("Created: November 20th 2018")
				print ("Last modified: November 20th 2018 ")
				print ("Total size: 885 KB (906,807 bytes) or 906 KB (906,807 bytes) ")
				print ("Description: ")
				print ("Added support for parsecs in the distance calculator. Only 3 more measurement units need to be added before we can move on to the next unfinished planned feature")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.78")
				print ("Alpha 3.78")
				print ("Created: November 20th 2018")
				print ("Last modified: November 20th 2018 ")
				print ("Total size: 917 KB (939,239 bytes) or 939 KB (939,239 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Added support for picometers in the distance calculator. Only 2 more measurement units need to be added before we can move on to the next unfinished planned feature")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.79")
				print ("Alpha 3.79")
				print ("Created: November 20th 2018")
				print ("Last modified: November 20th 2018")
				print ("Total size: 931 KB (954,004 bytes) or 954 KB (954,004 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("This update finally wrapped up the distance calculator. This was a massive accomplishment, and Sean took a break from the calculator for the rest of the day as a cooldown period from this success")
				print ("We didn't expect there to be so much to it, but now it is complete. Minor changes will be made to it in the future however. ")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.80")
				print ("Alpha 3.80")
				print ("Created: November 20th 2018 ")
				print ("Last modified: November 21st 2018 ")
				print ("Total size: 937 KB (960,013 bytes) or 960 KB (960,013 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("This version was the introductory build of the weight calculator. It is being redone, and will be at the advancement level of the distance calculator. This update adds in the basic sorting options, calculator variables, and some of the script for the calculation")
				print ("Nothing else was done in this build")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.81")
				print ("Alpha 3.81")
				print ("Created: November 21st 2018 ")
				print ("Last modified: November 21st 2018")
				print ("Total size: 939 KB (962,275 bytes) or 962 KB (962,275 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Minor update to the weight/mass calculator")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.82")
				print ("Alpha 3.82")
				print ("Created: November 21st 2018")
				print ("Last modified: November 21st 2018 ")
				print ("Total size: 940 KB (963,545 bytes) or 963 KB (963,545 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Another minor update to the weight/mass calculator, not functional")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.83")
				print ("Alpha 3.83")
				print ("Created: November 21st 2018")
				print ("Last modified: November 21st 2018 ")
				print ("Total size: 955 KB (978,181 bytes) or 978 KB (978,181 bytes) ")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("The update that finally makes the Atomic Mass Unit calculation option in the mass/weight calculator functional. Now that we have the basis on the structure of this mode, we can continue to make updates to add the rest of the unit types")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.84")
				print ("Alpha 3.84")
				print ("Created: November 21st 2018 ")
				print ("Last modified: November 21st 2018")
				print ("Total size: 973 KB (996,885 bytes) or 996 KB (996,885 bytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Added Carat calculations to the weight/mass calculator")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.85")
				print ("Alpha 3.85")
				print ("Created: November 21st 2018  ")
				print ("Last modified: November 21st 2018 ")
				print ("Total size: 985 KB (1,009,017 bytes) or 1009 KB (1.09 Megabytes) (1,009,017 bytes)")
				print ("Description: ")
				print ("Added new calculations to the weight/mass calculator. The calculator is now a full megabyte in size in base 10 binary, but not in base 2 binary ")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.86")
				print ("Alpha 3.86")
				print ("Created: November 21st 2018 ")
				print ("Last modified: November 21st 2018")
				print ("Total size: 0.97 MB (1,024,412 bytes) or 1024 Kilobytes (1,024,412 bytes) (1.02 Megabytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Another update to the weight/mass calculator, stabilized the script in some abandoned areas")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.87")
				print ("Alpha 3.87")
				print ("Created: November 21st 2018 ")
				print ("Last modified: November 21st 2018 ")
				print ("Total size: 0.98 MB (1,033,714 bytes) or 1033 KB (1,033,714 bytes) (1.03 Megabytes) ")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Added new documentation for bundling, puns, and math in gaming ")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.88")
				print ("Alpha 3.88")
				print ("Created: November 21st 2018 ")
				print ("Last modified: November 22nd 2018 ")
				print ("Total size: 1.00 MB (1,048,954 bytes) or 1048 KB (1,048,954 bytes) (1.04 Megabytes)")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Added dekagrams to the mass/weight calculator. The program is now over 1 megabyte in size, both in base 2, and base 10 binary ")
				print (" ")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.89")
				print ("Alpha 3.89")
				print ("Created: November 22nd 2018 ")
				print ("Last modified: ")
				print ("Total size: ")
				print ("File type: .py (Python file) ")
				print ("Description: ")
				print ("Increased documentation. Added documentation for ALL past versions, that took a LONG time, and it was worth it")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.90")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.91")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.92")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.93")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.94")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.95")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.96")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.97")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.98")
				more1 = input("Read more? [ENTER]")
				print ("UCalc Alpha 3 series:\nUCalc 3.99")
				more1 = input("Read more? [ENTER]")
				print ("Overview of UCalc Alpha 3 series")
				print ("The UCalc Alpha 3 series was caused by an accidental overwrite that lead to frequent backups")
				print ("Changes:")
				print ("Completed distance calculator")
				print ("Updated documentation")
				print ("The GUI was updated for many menus")
				print ("A Microsoft Product key generator was added")
				print ("A vote counter was added")
				print ("Settings were added")
				print ("New increased language support")
				more1 = input("Read more? [ENTER]")
				noMore = input("End of update log. Press [ENTER to exit]")
				print ("Exiting update log")
				print ("Please wait...")