print (" ")
print (" ")
print ("          _____                    _____            _____                    _____                    _____    ")                                                                
print ("         /\\    \\                  /\\    \\          /\\    \\                  /\\    \\                  /\\    \\   ")                                                                
print ("        /::\\    \\                /::\\____\\        /::\\    \\                /::\\____\\                /::\\    \\  ")                                                                
print ("       /::::\\    \\              /:::/    /       /::::\\    \\              /::::|   |               /::::\\    \\       ")                                                          
print ("      /::::::\\    \\            /:::/    /       /::::::\\    \\            /:::::|   |              /::::::\\    \\        ")                                                        
print ("     /:::/\\:::\\    \\          /:::/    /       /:::/\\:::\\    \\          /::::::|   |             /:::/\\:::\\    \\      ")                                                         
print ("    /:::/__\\:::\\    \\        /:::/    /       /:::/__\\:::\\    \\        /:::/|::|   |            /:::/  \\:::\\    \\       ")                                                       
print ("    \\:::\\   \\:::\\    \\      /:::/    /       /::::\\   \\:::\\    \\      /:::/ |::|   |           /:::/    \\:::\\    \\     ")                                                        
print ("  ___\\:::\\   \\:::\\    \\    /:::/    /       /::::::\\   \\:::\\    \\    /:::/  |::|   | _____    /:::/    / \\:::\\    \\      ")                                                      
print (" /\\   \\:::\\   \\:::\\    \\  /:::/    /       /:::/\\:::\\   \\:::\\    \\  /:::/   |::|   |/\\    \\  /:::/    /   \\:::\\ ___\\   ")                                                        
print ("/::\\   \\:::\\   \\:::\\____\\/:::/____/       /:::/  \\:::\\   \\:::\\____\\/:: /    |::|   /::\\____\\/:::/____/  ___\\:::|    |      ")                                                    
print ("\\:::\\   \\:::\\   \\::/    /\\:::\\    \\       \\::/    \\:::\\  /:::/    /\\::/    /|::|  /:::/    /\\:::\\    \\ /\\  /:::|____|      ")                                                    
print (" \\:::\\   \\:::\\   \\/____/  \\:::\\    \\       \\/____/ \\:::\\/:::/    /  \\/____/ |::| /:::/    /  \\:::\\    /::\\ \\::/    /         ")                                                  
print ("  \\:::\\   \\:::\\    \\       \\:::\\    \\               \\::::::/    /           |::|/:::/    /    \\:::\\   \\:::\\ \\/____/              ")                                              
print ("   \\:::\\   \\:::\\____\\       \\:::\\    \\               \\::::/    /            |::::::/    /      \\:::\\   \\:::\\____\\                  ")                                            
print ("    \\:::\\  /:::/    /        \\:::\\    \\              /:::/    /             |:::::/    /        \\:::\\  /:::/    /                           ")                                   
print ("     \\:::\\/:::/    /          \\:::\\    \\            /:::/    /              |::::/    /          \\:::\\/:::/    /                              ")                                 
print ("      \\::::::/    /            \\:::\\    \\          /:::/    /               /:::/    /            \\::::::/    /                                   ")                             
print ("       \\::::/    /              \\:::\\____\\        /:::/    /               /:::/    /              \\::::/    /                                      ")                           
print ("        \\::/    /                \\::/    /        \\::/    /                \\::/    /                \\::/____/                                         ")                       
print ("         \\/____/                  \\/____/          \\/____/                  \\/____/                                                                     ")                      
print ("                                                                                                                                                              ")                 
print ("          _____                    _____                    _____                    _____                    _____                    _____                    _____      ")    
print ("         /\\    \\                  /\\    \\                  /\\    \\                  /\\    \\                  /\\    \\                  /\\    \\                  /\\    \\         ")
print ("        /::\\____\\                /::\\____\\                /::\\____\\                /::\\    \\                /::\\    \\                /::\\    \\                /::\\    \\       ") 
print ("       /::::|   |               /:::/    /               /::::|   |               /::::\\    \\              /::::\\    \\              /::::\\    \\              /::::\\    \\       ")
print ("      /:::::|   |              /:::/    /               /:::::|   |              /::::::\\    \\            /::::::\\    \\            /::::::\\    \\            /::::::\\    \\      ")
print ("     /::::::|   |             /:::/    /               /::::::|   |             /:::/\\:::\\    \\          /:::/\\:::\\    \\          /:::/\\:::\\    \\          /:::/\\:::\\    \\   ")  
print ("    /:::/|::|   |            /:::/    /               /:::/|::|   |            /:::/__\\:::\\    \\        /:::/__\\:::\\    \\        /:::/__\\:::\\    \\        /:::/__\\:::\\    \\    ")
print ("   /:::/ |::|   |           /:::/    /               /:::/ |::|   |           /::::\\   \\:::\\    \\      /::::\\   \\:::\\    \\      /::::\\   \\:::\\    \\       \\:::\\   \\:::\\    \\   ")
print ("  /:::/  |::|   | _____    /:::/    /      _____    /:::/  |::|___|______    /::::::\\   \\:::\\    \\    /::::::\\   \\:::\\    \\    /::::::\\   \\:::\\    \\    ___\\:::\\   \\:::\\    \\  ")
print (" /:::/   |::|   |/\\    \\  /:::/____/      /\\    \\  /:::/   |::::::::\\    \\  /:::/\\:::\\   \\:::\\ ___\\  /:::/\\:::\\   \\:::\\    \\  /:::/\\:::\\   \\:::\\____\\  /\\   \\:::\\   \\:::\\    \\ ")
print ("/:: /    |::|   /::\\____\\|:::|    /      /::\\____\\/:::/    |:::::::::\\____\\/:::/__\\:::\\   \\:::|    |/:::/__\\:::\\   \\:::\\____\\/:::/  \\:::\\   \\:::|    |/::\\   \\:::\\   \\:::\\____\\")
print ("\\::/    /|::|  /:::/    /|:::|____\\     /:::/    /\\::/    / ~~~~~/:::/    /\\:::\\   \\:::\\  /:::|____|\\:::\\   \\:::\\   \\::/    /\\::/   |::::\\  /:::|____|\\:::\\   \\:::\\   \\::/    /")
print (" \\/____/ |::| /:::/    /  \\:::\\    \\   /:::/    /  \\/____/      /:::/    /  \\:::\\   \\:::\\/:::/    /  \\:::\\   \\:::\\   \\/____/  \\/____|:::::\\/:::/    /  \\:::\\   \\:::\\   \\/____/ ")
print ("         |::|/:::/    /    \\:::\\    \\ /:::/    /               /:::/    /    \\:::\\   \\::::::/    /    \\:::\\   \\:::\\    \\            |:::::::::/    /    \\:::\\   \\:::\\    \\     ")
print ("         |::::::/    /      \\:::\\    /:::/    /               /:::/    /      \\:::\\   \\::::/    /      \\:::\\   \\:::\\____\\           |::|\\::::/    /      \\:::\\   \\:::\\____\\    ")
print ("         |:::::/    /        \\:::\\__/:::/    /               /:::/    /        \\:::\\  /:::/    /        \\:::\\   \\::/    /           |::| \\::/____/        \\:::\\  /:::/    /    ")
print ("         |::::/    /          \\::::::::/    /               /:::/    /          \\:::\\/:::/    /          \\:::\\   \\/____/            |::|  ~|               \\:::\\/:::/    /     ")
print ("         /:::/    /            \\::::::/    /               /:::/    /            \\::::::/    /            \\:::\\    \\                |::|   |                \\::::::/    /      ")
print ("        /:::/    /              \\::::/    /               /:::/    /              \\::::/    /              \\:::\\____\\               \\::|   |                 \\::::/    /   ")    
print ("        \\::/    /                \\::/____/                \\::/    /                \\::/____/                \\::/    /                \\:|   |                  \\::/    /      ")  
print ("         \\/____/                  ~~                       \\/____/                  ~~                       \\/____/                  \\|___|                   \\/____/         ")
print ("     ")                                                                                                                                                                           
print ("  ")
print (" ")
adminPassword = str("password")
adminUsername = str("admin")
enterToEnter = input("Press [ENTER] key to start")
WikIDSelect = int(30004)
if WikIDSelect == 30004:
	if WikIDSelect == 30004:
		if WikIDSelect == 30004:
			loop1 = int(1)
			while (loop1 == 1):
				'''
				print ("Slang numbers")
				print ("420 - Also known as ''420 blaze it'' is a number referrring to smoking weed")
				print ("42 - the meaning of life")
				print ("69 - Refers to 69ing, or the 69 sex position")
				print ("3 - The number of the illuminati")
				print ("1738 - The title of the song ''1738'' by fetty wap")
				print ("888 - Alternate to 666")
				print ("8008 - For some calculator UIs this looks like BOOB")
				print ("8008135 - For some calculator UIs this looks like BOOBIES")
				'''
				print ("3\t420\t42\t69\t1738\t888\t8008\t43")
				slangID = str(input("Enter a number to learn more about it: "))
				if (slangID == "3"):
					print ("3 is a superstitious number AND a slang number. 3 will represent the illumiunati, or sometimes bad luck")
					noMore = input("Press [ENTER] key to continue: ")
				if (slangID == "420"):
					print ("420 is considered the weed number. 420 is related to smoking pot/weed/marijuana. It can also be considered a normal number")
					noMore = input("Press [ENTER] key to continue")
				if (slangID == "42"):
					print ("42 is the ultimate answer to life, and the universe. This is an inside joke from the 2005 movie ''hitchhikers guide to the galaxy''")
					noMore = input("Press [ENTER] leuy to continue")
				if (slangID == "69"):
					print ("The following content is considered Not Safe For Work")
					adminuser2 = str(input("Enter an administrator username: "))
					if (adminuser2 == adminUsername):
						print ("Log in to " + str(adminUsername))
						adminpass2 = str(input("Enter an administrator password for this account: "))
						if (adminpass2 == adminPassword):
							print ("Successfully logged in as administrator")
							print ("\n[NSFW] ")
							print ("Excerpt from wikipedia")
							print ("Sixty-nine or 69, also known by its French name soixante-neuf, is a group of sex positions in which two people align themselves so ")
							print ("that each person's mouth is near the other's genitals, each simultaneously performing oral sex on the other.")
							noMore = input("Press [ENTER] key to continue: ")
				if (slangID == "1738"):
					print ("1738 is a song by fetty wapp")
					noMore = input("Press [ENTER] key to continue: ")
				if (slangID == "888"):
					print ("888 is an alternate to 666")
					noMore = input("Press [ENTER] key to continue: ")
				if (slangID == "8008"):
					print ("On older analog/digital calculators, numbers were very straight and had no curves. This resulted in jokes such as 8008 which meant boob")
					print ("or 43110 which when turned upside down would look like ''hello''")
					noMore = input("Press [ENTER] key to continue: ")
				if (slangID == "43"):
					print ("From the YouTube channel ''explodingTNT'' he had a character called 'pink sheep' who could not count past 43")
					noMore = input("Press [ENTER] key to continue")
crash1 = input("The program has run into an error and the loop has stopped. Please try again later. Press [ENTER] key to continue... ")
print ("Exiting | please wait...")