print ("UCALC editions")
print ("\n\n")
loopfor1 = int(1)
while (loopfor1 == 1):
	print ("==================================================")
	print ("\n\n\n\n\n\n\n\nEnter an ID to learn more about an edition")
	print ("All-in-one [001] Floppy [002] time [003] for electricians [004] for teachers [005]")
	print ("For students [006] for scientists [007] for artists [008] for historians [009] for gamers [010]")
	print ("For government [011] for friends [012] for developers [013] for markets [014] for business [015] ")
	print ("For hospitals [016]")
	entID = str(input("ID: "))
	if (entID == "0" or entID == "00" or entID == "000" or entID == "1" or entID == "001"):
		print ("UCALC All-in-one")
		print ("Features: ")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular division calculator")
		print ("=================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "2" or entID == "002"):
		print ("UCALC floppy")
		print ("Features: ")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular division calculator")
		print ("=================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "3" or entID == "003"):
		print ("UCALC time edition")
		print ("Features: ")
		print ("Years between calculator")
		print ("Years since calculator")
		print ("duration calculator")
		print ("Days since calculator")
		print ("Days between calculator")
		print ("Command line view only")
		print ("==================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "4" or entID == "004"):
		print ("UCALC for electricians")
		print ("Features: ")
		print ("Power calculator")
		print ("Temperature calculator")
		print ("Currency calculator")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular division calculator")
		print ("Hexadecimal converter 4 bit")
		print ("Hexadecimal converter 8 bit")
		print ("Hexadecimal converter 12 bit")
		print ("Hexadecimal converter 16 bit")
		print ("Hexadecimal converter 18 bit")
		print ("Hexadecimal converter 24 bit")
		print ("Hexadecimal converter 32 bit")
		print ("Command line view only or GUI view only")
		print ("============================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "5" or entID == "005"):
		print ("UCALC for teachers")
		print ("Features: ")
		print ("Grade calculator")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular division calculator")
		print ("============================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "6" or entID == "006"):
		print ("UCALC for students")
		print ("Features: ")
		print ("Documentation")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular division calculator")
		print ("Greater than calculator")
		print ("Less than calculator")
		print ("============================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "7" or entID == "007"):
		print ("UCALC for scientists")
		print ("Features: ")
		print ("Temperature calculator")
		print ("Speed calculator")
		print ("Distance calculator")
		print ("Weight calculator")
		print ("Factorial calculator")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular divison calculator")
		print ("Storage calculator")
		print ("Square root calculator")
		print ("Graph calculator")
		print ("Percentage calculator")
		print ("Energy calculator")
		print ("ASCII calculator 3 bit")
		print ("ASCII calculator 4 bit")
		print ("ASCII calculator 5 bit")
		print ("ASCII calculator 6 bit")
		print ("ASCII calculator 7 bit")
		print ("ASCII calculator 8 bit")
		print ("ASCII calculator 9 bit")
		print ("ASCII calculator 10 bit")
		print ("ASCII calculator 11 bit")
		print ("ASCII calculator 12 bit")
		print ("ASCII calculator 13 bit")
		print ("ASCII calculator 14 bit")
		print ("ASCII calculator 15 bit")
		print ("ASCII calculator 16 bit")
		print ("===============================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "8" or entID == "008"):
		print ("UCALC for artists")
		print ("Features: ")
		print ("Screensavers")
		print ("RGB calculator")
		print ("ASCII art maker")
		print ("100K Digits of Pi")
		print ("Accessory manager")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular division calculator")
		print ("===============================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "9" or entID == "009"):
		print ("UCALC for historians")
		print ("Features: ")
		print ("Roman numeral calculator 4 bit")
		print ("Roman numeral calculator 5 bit")
		print ("Roman numeral calculator 6 bit")
		print ("Roman numeral calculator 7 bit")
		print ("Roman numeral calculator 8 bit")
		print ("Roman numeral calculator 9 bit")
		print ("Roman numeral calculator 10 bit")
		print ("Roman numeral calculator 11 bit")
		print ("Roman numeral calculator 12 bit")
		print ("Greek numeral calculator 4 bit")
		print ("Greek numeral calculator 5 bit")
		print ("Greek numeral calculator 6 bit")
		print ("Greek numeral calculator 7 bit")
		print ("Greek numeral calculator 8 bit")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular division calculator")
		print ("=================================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "10" or entID == "010"):
		print ("UCALC for gamers")
		print ("Features: ")
		print ("2048")
		print ("Pi-mun")
		print ("X cups")
		print ("Launch the X")
		print ("Pig")
		print ("Rock Paper Scissors")
		print ("Tic-tac-toe")
		print ("Minesweeper")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular division calculator")
		print ("=================================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "11" or entID == "011"):
		print ("UCALC for friends")
		print ("Features: ")
		print ("Stephen Hawking chatbot")
		print ("Albert Einstein chatbot")
		print ("Sean Myrick chatbot")
		print ("Intro to chatgroups")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular division calculator")
		print ("=================================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "12" or entID == "012"):
		print ("UCALC for government")
		print ("Features: ")
		print ("Currency calculator")
		print ("Vote counter")
		print ("=================================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "13" or entID == "013"):
		print ("UCALC for developers")
		print ("Features: ")
		print ("Product Key generator")
		print ("Random equation calculator")
		print ("Random number generator")
		print ("Counting machine 128")
		print ("Screensavers")
		print ("Hexadecimal converter 4 bit")
		print ("Hexadecimal converter 8 bit")
		print ("Hexadecimal converter 12 bit")
		print ("Hexadecimal converter 16 bit")
		print ("Hexadecimal converter 18 bit")
		print ("Hexadecimal converter 24 bit")
		print ("Hexadecimal converter 32 bit")
		print ("Square root calculator")
		print ("Digital storage calculator")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular division calculator")
		print ("=================================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "14" or entID == "014"):
		print ("UCALC for markets")
		print ("Features: ")
		print ("Currency calculator")
		print ("Addition calculator")
		print ("Subtraction calculator")
		print ("Multiplication calculator")
		print ("Division calculator")
		print ("Modular division calculator")
		print ("=================================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "15" or entID == "015"):
		print ("UCALC for business")
		print ("Features: ")
		print ("=================================")
		more1 = input("Press [ENTER] key to continue")
	if (entID == "16" or entID == "016"):
		print ("UCALC for hospitals")
		print ("Features: ")
		print ("=================================")
		more1 = input("Press [ENTER] key to continue")
noMore = input("Press [ENTER] key to exit")
'''
All editions come as:
* operating system
* EXE file
* APK file 
* IPA file 
* APP file
* MSI file 
* TAR file
All versions are compatible with:
* Windows Vista and up (64 bit or 128 bit)
* Ubuntu 4.10 and up (64 bit or 128 bit)
* MacOS X 10.04 and up (64 bit or 128 bit)
* Fedora 6 and up (64 bit or 128 bit)
* Android 5.0 and up (64 bit or 128 bit)
* iOS 7 and up (64 bit or 128 bit)
'''