print ("Greek Numeral calculator | Launcher |")
print ("====================================|")
print ("Modes: ")
print ("4 bit mode    | ID: 4 |")
print ("5 bit mode    | ID: 5 |")
print ("6 bit mode    | ID: 6 |")
print ("7 bit mode    | ID: 7 |")
print ("8 bit mode    | ID: 8 |")
print ("NOTICE! ")
print ("Sean was unable to find Unicode characters that match the Greek Numerals, so he chose some that look closest")
print ("Guide: ")
print ("1 = I")
print ("5 = ┌")
print ("10 = ∆")
print ("100 = H")
print ("1000 = X")
noMore = input("Press [ENTER] key to quit"))
