print (" ")
print ("      ___           ___           ___           ___           ___              ")
print ("     /\\  \\         /\\  \\         /\\  \\         /\\__\\         /\\  \\             ")
print ("    /::\\  \\       /::\\  \\       /::\\  \\       /:/  /         \\:\\  \\            ")
print ("   /:/\\:\\  \\     /:/\\:\\  \\     /:/\\:\\  \\     /:/  /           \\:\\  \\           ")
print ("  /::\\~\\:\\  \\   /::\\~\\:\\__\\   /:/  \\:\\  \\   /:/  /  ___       /::\\  \\          ")
print (" /:/\\:\\ \\:\\__\\ /:/\\:\\ \\:|__| /:/__/ \\:\\__\\ /:/__/  /\\__\\     /:/\\:\\__\\    ")     
print (" \\/__\\:\\/:/  / \\:\\~\\:\\/:/  / \\:\\  \\ /:/  / \\:\\  \\ /:/  /    /:/  \\/__/    ")     
print ("      \\::/  /   \\:\\ \\::/  /   \\:\\  /:/  /   \\:\\  /:/  /    /:/  /             ") 
print ("      /:/  /     \\:\\/:/  /     \\:\\/:/  /     \\:\\/:/  /     \\/__/             ")  
print ("     /:/  /       \\::/__/       \\::/  /       \\::/  /                          ")
print ("     \\/__/         ~~            \\/__/         \\/__/                          ") 
print ("      ___           ___           ___           ___       ___                  ")
print ("     /\\__\\         /\\  \\         /\\  \\         /\\__\\     /\\  \\               ")  
print ("    /:/  /        /::\\  \\       /::\\  \\       /:/  /    /::\\  \\                ")
print ("   /:/  /        /:/\\:\\  \\     /:/\\:\\  \\     /:/  /    /:/\\:\\  \\               ")
print ("  /:/  /  ___   /:/  \\:\\  \\   /::\\~\\:\\  \\   /:/  /    /:/  \\:\\  \\            ")  
print (" /:/__/  /\\__\\ /:/__/ \\:\\__\\ /:/\\:\\ \\:\\__\\ /:/__/    /:/__/ \\:\\__\\      ")       
print (" \\:\\  \\ /:/  / \\:\\  \\  \\/__/ \\/__\\:\\/:/  / \\:\\  \\    \\:\\  \\  \\/__/")             
print ("  \\:\\  /:/  /   \\:\\  \\            \\::/  /   \\:\\  \\    \\:\\  \\        ")           
print ("   \\:\\/:/  /     \\:\\  \\           /:/  /     \\:\\  \\    \\:\\  \\      ")            
print ("    \\::/  /       \\:\\__\\         /:/  /       \\:\\__\\    \\:\\__\\    ")             
print ("     \\/__/         \\/__/         \\/__/         \\/__/     \\/__/       ")          
print (" ")
print (" ")
print (" ___  ____  __  __  ____  ____  _  _  ____    ____  ____  ____  ____  ____  _____  _  _ ")
print ("/ __)(_  _)(  )(  )(  _ \\( ___)( \\( )(_  _)  ( ___)(  _ \\(_  _)(_  _)(_  _)(  _  )( \\( )")
print ("\\__ \\  )(   )(__)(  )(_) ))__)  )  (   )(     )__)  )(_) )_)(_   )(   _)(_  )(_)(  )  ( ")
print ("(___/ (__) (______)(____/(____)(_)\\_) (__)   (____)(____/(____) (__) (____)(_____)(_)\\_)")
print (" ")
print ("This is the student edition of UCALC. This edition is designed to do tasks for students of all ages. It does not contain all the features. If you want to have more features, choose a different version. This is free software and you have the write to use, modify, and share this program with anybody")
print ("This is free, open-source software made for everyone")
print ("Version type: Android Package (.apk)")
print ("Platform: 86x64x128")
print ("(c) Copyleft, Sean Walla Walla 2015-2019")
noMore = input("Press [ENTER] key to exit")