WikIDSelect = int(20003)
if WikIDSelect == 20003:
	if WikIDSelect == 20003:
		if WikIDSelect == 20003:			
			if WikIDSelect == 20003:
				print ("In computer architecture, 4-bit integers, memory addresses, or other data units are those that are 4 bits wide. Also, ")
				print ("4-bit CPU and ALU architectures are those that are based on registers, address buses, or data buses of that size. A group ")
				print ("of four bits is also called a nibble and has 24 = 16 possible values.")
				print (" ")
				print ("Some of the first microprocessors had a 4-bit word length and were developed around 1970. The TMS 1000, the world's first ")
				print ("single-chip microprocessor, was a 4-bit CPU; it had a Harvard architecture, with an on-chip instruction ROM, 8-bit-wide ")
				print ("instructions and an on-chip data RAM with 4-bit words.[1] The first commercial microprocessor was the binary-coded decimal") 
				print ("(BCD-based) Intel 4004,[2][3] developed for calculator applications in 1971; it had a 4-bit word length, but had 8-bit ")
				print ("instructions and 12-bit addresses.")
				print (" ")
				print ("The HP Saturn processors, used in many Hewlett-Packard calculators between 1984 and 2003 (including the HP 48 series ")
				print ("of scientific calculators) are ''4-bit'' (or hybrid 64-/4-bit) machines; as the Intel 4004 did, they string multiple 4-bit") 
				print ("words together, e.g. to form a 20-bit memory address, and most of the registers are 64 bits wide, storing 16 ")
				print ("4-bit digits.[4][5][6]")
				print (" ")
				print ("The 4-bit processors were programmed in assembly language or Forth, e.g. ''MARC4 Family of 4 bit Forth CPU''[7] because of the ")
				print ("extreme size constraint on programs and because common programming languages (for microcontrollers, 8-bit and larger), such as") 
				print ("the C programming language, do not support 4-bit data types (C requires that the size of the char data type be at least 8 ")
				print ("bits,[8] and that all data types other than bitfields have a size that is a multiple of the character size[9][10][11]). ")
				print ("While larger than 4-bit values can be used by combining more than one manually, the language has to support the smaller ")
				print ("values used in the combining. If not, assembly is the only option.[dubious – discuss]")
				print (" ")
				print ("The 1970s saw the emergence of 4-bit software applications for mass markets like pocket calculators. During the ")
				print ("1980s 4-bit microprocessor were used in handheld electronic games to keep costs low.")
				print (" ")
				print ("In the 1970s and 1980s, a number of research and commercial computers used bit slicing, in which the CPU's arithmetic ")
				print ("logic unit (ALU) was built from multiple 4-bit-wide sections, each section including a chip such as an Am2901 or 74181 chip.")
				print (" ")
				print ("The Zilog Z80, although it is an 8-bit microprocessor, has a 4-bit ALU.[12][13]")
				more1 = input("Contents")
				print (" ")
				print ("1 Modern uses")
				print ("2 Details")
				print ("3 List of 4-bit processors")
				print ("4 See also")
				print ("5 References")
				print ("6 External links")
				print (" ")
				more1 = input("Modern uses")
				print (" ")
				print ("While 32- and 64-bit processors are more prominent in modern consumer electronics, 4-bit CPUs continue to be used ")
				print ("(usually as part of a microcontroller) in cost-sensitive applications that require minimal computing power. For example,") 
				print ("one bicycle computer specifies that it uses a ''4-bit 1-chip microcomputer''.[14] Other typical uses include coffee makers,") 
				print ("infrared remote controls,[15] and security alarms.[16]")
				print (" ")
				print ("Use of 4-bit processors has declined relative to 8-bit or even 32-bit processors, as they are hard to find cheaper in general") 
				print ("computer suppliers' stores. The simplest kinds are not available in any of them, and others are ''non-stock'' and more ")
				print ("expensive.[17] (A few expensive ones can be found, as of 2014, on eBay.)[18][19][20]")
				print (" ")
				print ("Electronics stores still carry, as of 2014, non-CPU/non-MCU 4-bit chips, such as counters.")
				print (" ")
				print ("As of 2015, most PC motherboards, especially laptop motherboards, use a 4-bit LPC bus (introduced in 1998) to connect the ")
				print ("southbridge to the motherboard firmware flash ROM (UEFI or BIOS) and the Super I/O chip.[21][22]")
				more1 = input("Details")
				print ("Main article: Nibble")
				print (" ")
				print ("With 4 bits, it is possible to create 16 different values. All single-digit hexadecimal numbers can be written with four bits. ")
				print ("Binary-coded decimal is a digital encoding method for numbers using decimal notation, with each decimal digit represented by ")
				print ("four bits.")
				print ("Binary 	Octal 	Decimal 	Hexadecimal")
				print ("0000 	0 	0 	0")
				print ("0001 	1 	1 	1")
				print ("0010 	2 	2 	2")
				print ("0011 	3 	3 	3")
				print ("0100 	4 	4 	4")
				print ("0101 	5 	5 	5")
				print ("0110 	6 	6 	6")
				print ("0111 	7 	7 	7")
				print ("1000 	10 	8 	8")
				print ("1001 	11 	9 	9")
				print ("1010 	12 	10 	A")
				print ("1011 	13 	11 	B")
				print ("1100 	14 	12 	C")
				print ("1101 	15 	13 	D")
				print ("1110 	16 	14 	E")
				print ("1111 	17 	15 	F")
				more1 = input("List of 4-bit processors")
				print ("16-pin DIP")
				print ("Intel C4004")
				print ("infrared remote control PCB")
				print ("an infrared remote control transmitter controlled by a NEC D63GS 4-bit microcontroller")
				print ("20-pin PSOP")
				print ("NEC D63GS: a 4-bit microcontroller for infrared remote control transmission")
				print ("card-edge PCB")
				print ("Olympia CD700 Desktop Calculator using the National Semiconductor MAPS MM570X bit-serial 4-bit microcontroller")
				print ("16-pin DIP")
				print ("National Semiconductor MM5700CA/D bit-serial 4-bit microcontroller")
				print (" ")
				print ("TMS 1000")
				print ("Intel 4004")
				print ("Intel 4040")
				print ("10NES")
				print ("Atmel MARC4 core[23][24] – (discontinued: ''Last ship date: March 7, 2015''[25])")
				print ("Samsung S3C7 (KS57 Series) 4-bit microcontrollers (RAM: 512 to 5264 nibbles, 6 MHz clock)")
				print ("Toshiba TLCS-47 series")
				print ("HP Saturn")
				print ("NEC μPD75X")
				print ("NEC μCOM-4")
				print ("NEC (now Renesas) µPD612xA (discontinued), µPD613x, μPD6x[15][26] and μPD1724x[27] infrared remote control transmitter ")
				print ("microcontrollers[28][29]")
				print ("EM Microelectronic-Marin EM6600 family,[30] EM6580,[31][32] EM6682,[33] etc.")
				print ("Epson S1C63 family")
				print ("National Semiconductor MAPS MM570X")
				noMore = input("Press [ENTER] key to exit")