WikIDSelect = int(30007)
if WikIDSelect == 30007:
	if WikIDSelect == 30007:
		if WikIDSelect == 30007:
			if WikIDSelect == 30007:
				print ("Intellect Quotient")
				print ("Excerpt from https://www.wikipedia.org/Intelligence_Quotient")
				print ("An intelligence quotient (IQ) is a total score derived from several standardized tests designed to assess human intelligence. ")
				print ("The abbreviation ''IQ'' was coined by the psychologist William Stern for the German term Intelligenzquotient, his term for a ")
				print ("scoring method for intelligence tests at University of Breslau he advocated in a 1912 book.[1] Historically, IQ is a score ")
				print ("obtained by dividing a person's mental age score, obtained by administering an intelligence test, by the person's chronological ")
				print ("age, both expressed in terms of years and months. The resulting fraction is multiplied by 100 to obtain the IQ score.[2] When ")
				print ("current IQ tests were developed, the median raw score of the norming sample is defined as IQ 100 and scores each standard ")
				print ("deviation (SD) up or down are defined as 15 IQ points greater or less,[3] although this was not always so historically. ")
				print ("By this definition, approximately two-thirds of the population scores are between IQ 85 and IQ 115. About 2.5 percent of the ")
				print ("population scores above 130, and 2.5 percent below 70.[4][5]")
				print (" ")
				print ("Scores from intelligence tests are estimates of intelligence. Unlike, for example, distance and mass, a concrete measure of ")
				print ("intelligence cannot be achieved given the abstract nature of the concept of ''intelligence''.[6] IQ scores have been shown to") 
				print ("be associated with such factors as morbidity and mortality,[7][8] parental social status,[9] and, to a substantial degree, ")
				print ("biological parental IQ. While the heritability of IQ has been investigated for nearly a century, there is still debate about") 
				print ("the significance of heritability estimates[10][11] and the mechanisms of inheritance.[12]")
				print (" ")
				print ("IQ scores are used for educational placement, assessment of intellectual disability, and evaluating job applicants. Even when") 
				print ("students improve their scores on standardized tests, they do not always improve their cognitive abilities, such as memory,")
				print ("attention and speed.[13] In research contexts they have been studied as predictors of job performance, and income. They are") 
				print ("also used to study distributions of psychometric intelligence in populations and the correlations between it and other ")
				print ("variables. Raw scores on IQ tests for many populations have been rising at an average rate that scales to three IQ points per ")
				print ("decade since the early 20th century, a phenomenon called the Flynn effect. Investigation of different patterns of increases in ")
				print ("subtest scores can also inform current research on human intelligence.")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Contents")
				print ("1 History")
				print ("1.1 Precursors to IQ testing")
				print ("1.2 General factor (g)")
				print ("1.3 United States military selection in World War I")
				print ("1.4 IQ testing and the Eugenics movement in the United States")
				print ("1.5 Cattell–Horn–Carroll theory")
				print ("1.6 Other theories")
				print ("2 Current tests")
				print ("3 Test bias or differential item functioning")
				print ("4 Reliability and validity")
				print ("5 Flynn effect")
				print ("6 Age")
				print ("7 Genetics and environment")
				print ("7.1 Heritability")
				print ("7.2 Shared family environment")
				print ("7.3 Non-shared family environment and environment outside the family")
				print ("7.4 Individual genes")
				print ("7.5 Gene-environment interaction")
				print (" 8 Interventions")
				print ("9 Music")
				print ("10 Brain anatomy")
				print ("11 Health")
				print ("12 Social correlations")
				print ("12.1 School performance")
				print ("12.2 Job performance")
				print ("12.3 Income")
				print ("12.4 Crime")
				print ("12.5 Health and mortality")
				print ("12.6 Other accomplishments")
				print ("13 Group-IQ or the collective intelligence factor c")
				print ("14 Group differences")
				print ("14.1 Sex")
				print ("14.2 Race and intelligence")
				print ("14.2.1 Race and intelligence in United States of America")
				print ("15 Public policy")
				print ("16 Criticism and views")
				print ("16.1 Relationship to intelligence")
				print ("16.2 Criticism of IQ")
				print ("16.3 Systematic exclusion of threshold effects")
				print ("16.4 Test bias")
				print ("16.5 Intermingling cultures and IQ classification fairness")
				print ("16.6 Outdated methodology")
				print ("16.7 Intelligence: Knowns and Unknowns")
				print ("16.8 Dynamic assessment")
				print ("17 Classification")
				print ("18 High IQ societies")
				print ("19 See also")
				print ("20 References")
				print ("21 Bibliography")
				print ("22 External links")
				print (" ")
				print ("\n\n\n\n\n\n\n")
				more1 = input("History")
				print ("See also: History of the race and intelligence controversy")
				more1 = input("Precursors to IQ testing")
				print ("Historically, even before IQ tests were devised, there were attempts to classify people into intelligence categories by")
				print ("observing their behavior in daily life.[14][15] Those other forms of behavioral observation are still important for ")
				print ("validating classifications based primarily on IQ test scores. Both intelligence classification by observation of behavior") 
				print ("outside the testing room and classification by IQ testing depend on the definition of ''intelligence'' used in a particular")
				print ("case and on the reliability and error of estimation in the classification procedure.")
				print (" ")
				print ("The English statistician Francis Galton made the first attempt at creating a standardized test for rating a person's")
				print ("intelligence. A pioneer of psychometrics and the application of statistical methods to the study of human diversity and the ")
				print ("study of inheritance of human traits, he believed that intelligence was largely a product of heredity (by which he did not ")
				print ("mean genes, although he did develop several pre-Mendelian theories of particulate inheritance).[16][17][18] He hypothesized ")
				print ("that there should exist a correlation between intelligence and other observable traits such as reflexes, muscle grip, and head ")
				print ("size.[19] He set up the first mental testing centre in the world in 1882 and he published ''Inquiries into Human Faculty and ")
				print ("Its Development'' in 1883, in which he set out his theories. After gathering data on a variety of physical variables, he was ")
				print ("unable to show any such correlation, and he eventually abandoned this research.[20][21]")
				print (" ")
				print ("French psychologist Alfred Binet was one of the key developers of what later became known as the Stanford–Binet test.")
				print (" ")
				print ("French psychologist Alfred Binet, together with Victor Henri and Théodore Simon had more success in 1905, when they published ")
				print ("the Binet-Simon test, which focused on verbal abilities. It was intended to identify mental retardation in school children,[22]")
				print ("but in specific contradistinction to claims made by psychiatrists that these children were ''sick'' (not ''slow'') and should ") 
				print ("therefore be removed from school and cared for in asylums.[23] The score on the Binet-Simon scale would reveal the child's ")
				print ("mental age. For example, a six-year-old child who passed all the tasks usually passed by six-year-olds—but nothing beyond—would ")
				print ("have a mental age that matched his chronological age, 6.0. (Fancher, 1985). Binet thought that intelligence was multifaceted, ")
				print ("but came under the control of practical judgment.")
				print (" ")
				print ("In Binet's view, there were limitations with the scale and he stressed what he saw as the remarkable diversity of intelligence ")
				print ("and the subsequent need to study it using qualitative, as opposed to quantitative, measures (White, 2000). American psychologist") 
				print ("Henry H. Goddard published a translation of it in 1910. American psychologist Lewis Terman at Stanford University revised the")
				print ("Binet-Simon scale, which resulted in the Stanford-Binet Intelligence Scales (1916). It became the most popular test in the ")
				print ("United States for decades.[22][24][25][26]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("General factor (g)")
				print ("Main article: g factor")
				print (" ")
				print ("The many different kinds of IQ tests include a wide variety of item content. Some test items are visual, while many are verbal.")
				print ("Test items vary from being based on abstract-reasoning problems to concentrating on arithmetic, vocabulary, or general ")
				print ("knowledge.")
				print (" ")
				print ("The British psychologist Charles Spearman in 1904 made the first formal factor analysis of correlations between the tests. He ")
				print ("observed that children's school grades across seemingly unrelated school subjects were positively correlated, and reasoned that ")
				print ("these correlations reflected the influence of an underlying general mental ability that entered into performance on all kinds of") 
				print ("mental tests. He suggested that all mental performance could be conceptualized in terms of a single general ability factor and") 
				print ("a large number of narrow task-specific ability factors. Spearman named it g for ''general factor'' and labeled the specific ") 
				print ("factors or abilities for specific tasks s. In any collection of test items that make up an IQ test, the score that best ")
				print ("measures g is the composite score that has the highest correlations with all the item scores. Typically, the ''g-loaded'' ")
				print ("composite score of an IQ test battery appears to involve a common strength in abstract reasoning across the test's item ")
				print ("content. Therefore, Spearman and others have regarded g as closely related to the essence of human intelligence.[citation needed]")
				print (" ")
				print ("Spearman's argument proposing a general factor of human intelligence is still accepted in principle by many psychometricians.") 
				print ("Today's factor models of intelligence typically represent cognitive abilities as a three-level hierarchy, where there are a ")
				print ("large number of narrow factors at the bottom of the hierarchy, a handful of broad, more general factors at the intermediate ")
				print ("level, and at the apex a single factor, referred to as the g factor, which represents the variance common to all cognitive ")
				print ("tasks. However, this view is not universally accepted; other factor analyses of the data, with different results, are possible.") 
				print ("Some psychometricians regard g as a statistical artifact.[citation needed]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("United States military selection in World War I")
				print (" ")
				print ("During World War I, a way was needed to evaluate and assign Army recruits to appropriate tasks. This led to the development of")
				print ("several mental tests by Robert Yerkes, who worked with major hereditarians of American psychometrics—including Terman, ")
				print ("Goddard—to write the test.[27] The testing generated controversy and much public debate in the United States. Nonverbal or ")
				print ("''performance'' tests were developed for those who could not speak English or were suspected of malingering.[22] Based on ")
				print ("Goddard's translation of the Binet-Simon test, the tests had an impact in screening men for officer training:")
				print (" ")
				print ("	...the tests did have a strong impact in some areas, particularly in screening men for officer training. At the start of")
				print ("the war, the army and national guard maintained nine thousand officers. By the end, two hundred thousand officers presided, ")
				print ("and two- thirds of them had started their careers in training camps where the tests were applied. In some camps, no man scoring")
				print ("below C could be considered for officer training.[27]")
				print (" ")
				print ("1.75 million men were tested in total, making the results the first mass-produced written tests of intelligence, though ")
				print ("considered dubious and non-usable, for reasons including high variability of test implementation throughout different camps and")
				print ("questions testing for familiarity with American culture rather than intelligence.[27] After the war, positive publicity ")
				print ("promoted by army psychologists helped to make psychology a respected field.[28] Subsequently, there was an increase in jobs and")
				print ("funding in psychology in the United States.[29] Group intelligence tests were developed and became widely used in schools and") 
				print ("industry.[30]")
				print (" ")
				print ("The results of these tests, which at the time reaffirmed contemporary racism and nationalism, are considered controversial and ")
				print ("dubious, having rested on certain contested assumptions: that intelligence was heritable, innate, and could be relegated to a ")
				print ("single number, the tests were enacted systematically, and test questions actually tested for innate intelligence rather than") 
				print ("subsuming environmental factors.[27] The tests also allowed for the bolstering of jingoist narratives in the context of ")
				print ("increased immigration, which may have influenced the passing of the Immigration Restriction Act of 1924.[27]")
				print (" ")
				print ("L.L. Thurstone argued for a model of intelligence that included seven unrelated factors (verbal comprehension, word fluency,")
				print ("number facility, spatial visualization, associative memory, perceptual speed, reasoning, and induction). While not widely used,")
				print ("Thurstone's model influenced later theories.[22]")
				print (" ")
				print ("David Wechsler produced the first version of his test in 1939. It gradually became more popular and overtook the Stanford-Binet ")
				print ("in the 1960s. It has been revised several times, as is common for IQ tests, to incorporate new research. One explanation is that")
				print ("psychologists and educators wanted more information than the single score from the Binet. Wechsler's ten or more subtests ")
				print ("provided this. Another is that the Stanford-Binet test reflected mostly verbal abilities, while the Wechsler test also ")
				print ("reflected nonverbal abilities. The Stanford-Binet has also been revised several times and is now similar to the Wechsler in")
				print ("several aspects, but the Wechsler continues to be the most popular test in the United States.[22]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("IQ testing and the Eugenics movement in the United States")
				print (" ")
				print ("Eugenics refers to the principles of heredity used to improve the human race. Francis Galton first used the term in the late") 
				print ("1800s.[31] The eugenics movement was popularized by Progressivism in the US in the 1920s and 1930s.[32]")
				print (" ")
				print ("Goddard was a eugenicist. In 1908, he published his own version, The Binet and Simon Test of Intellectual Capacity, and ")
				print ("cordially promoted the test. He quickly extended the use of the scale to the public schools (1913), to immigration ")
				print ("(Ellis Island, 1914) and to a court of law (1914).[33]")
				print (" ")
				print ("Different from Galton, who promoted eugenics through selective breeding for positive traits, Goddard went with the US eugenics ")
				print ("movement to eliminate ''undesirable'' traits.[34] Goddard used the term ''feeble-minded'' to refer to people who did not ")
				print ("perform well in the test and thus were intellectually inferior. He argued that ''feeble-mindedness'' is caused by heredity,") 
				print ("thus feeble-minded people should be prevented from giving birth, either by institutional isolation or sterilization surgeries.")
				print ("[33] At first sterilization targeted the disabled and was extended to poor people. Goddard's intelligence test was endorsed by ")
				print ("the eugenicists to push for laws for forced sterilization. Different states adopted the sterilization laws at different pace. ")
				print ("These laws forced over 64,000 people to go through sterilization in the United States.[35]")
				print (" ")
				print ("California's sterilization program was so effective that the Nazis turned to the government for advice on how to prevent the")
				print ("birth of the ''unfit''.[36] The US eugenics movement lost its momentum in 1940s and was halted in view of the horrors of Nazi ")
				print ("Germany.")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Cattell–Horn–Carroll theory")
				print ("Main article: Cattell–Horn–Carroll theory")
				print ("Psychologist Raymond Cattell defined fluid and crystallized intelligence and authored the Cattell Culture Fair III IQ test.")
				print ("Raymond Cattell (1941) proposed two types of cognitive abilities in a revision of Spearman's concept of general intelligence.")
				print ("Fluid intelligence (Gf) was hypothesized as the ability to solve novel problems by using reasoning, and crystallized ")
				print ("intelligence (Gc) was hypothesized as a knowledge-based ability that was very dependent on education and experience. In ")
				print ("addition, fluid intelligence was hypothesized to decline with age, while crystallized intelligence was largely resistant to the") 
				print ("effects of aging. The theory was almost forgotten, but was revived by his student John L. Horn (1966) who later argued Gf and")
				print ("Gc were only two among several factors, and who eventually identified nine or ten broad abilities. The theory continued to be ")
				print ("called Gf-Gc theory.[22]")
				print (" ")
				print ("John B. Carroll (1993), after a comprehensive reanalysis of earlier data, proposed the three stratum theory, which is a ")
				print ("hierarchical model with three levels. The bottom stratum consists of narrow abilities that are highly specialized (e.g., ")
				print ("induction, spelling ability). The second stratum consists of broad abilities. Carroll identified eight second-stratum abilities.") 
				print ("Carroll accepted Spearman's concept of general intelligence, for the most part, as a representation of the uppermost, third") 
				print ("stratum.[37][38]")
				print (" ")
				print ("In 1999, a merging of the Gf-Gc theory of Cattell and Horn with Carroll's Three-Stratum theory has led to the Cattell–Horn–Carroll theory (CHC Theory). It has greatly influenced many of the current broad IQ tests.[22]")
				print (" ")
				print ("In CHC theory, a hierarchy of factors is used; g is at the top. Under it are ten broad abilities that in turn are subdivided into seventy narrow abilities. The broad abilities are:[22]")
				print (" ")
				print ("	Fluid intelligence (Gf) includes the broad ability to reason, form concepts, and solve problems using unfamiliar information or novel procedures.")
				print ("    Crystallized intelligence (Gc) includes the breadth and depth of a person's acquired knowledge, the ability to communicate one's knowledge, and the ability to reason using previously learned experiences or procedures.")
				print ("    Quantitative reasoning (Gq) is the ability to comprehend quantitative concepts and relationships and to manipulate numerical symbols.")
				print ("    Reading and writing ability (Grw) includes basic reading and writing skills.")
				print ("    Short-term memory (Gsm) is the ability to apprehend and hold information in immediate awareness, and then use it within a few seconds.")
				print ("    Long-term storage and retrieval (Glr) is the ability to store information and fluently retrieve it later in the process of thinking.")
				print ("    Visual processing (Gv) is the ability to perceive, analyze, synthesize, and think with visual patterns, including the ability to store and recall visual representations.")
				print ("    Auditory processing (Ga) is the ability to analyze, synthesize, and discriminate auditory stimuli, including the ability to process and discriminate speech sounds that may be presented under distorted conditions.")
				print ("    Processing speed (Gs) is the ability to perform automatic cognitive tasks, particularly when measured under pressure to maintain focused attention.")
				print ("    Decision/reaction time/speed (Gt) reflects the immediacy with which an individual can react to stimuli or a task (typically measured in seconds or fractions of seconds; it is not to be confused with Gs, which typically is measured in intervals of 2–3 minutes). See Mental chronometry.")
				print (" ")
				print ("Modern tests do not necessarily measure all of these broad abilities. For example, Gq and Grw may be seen as measures of school ")
				print ("achievement and not IQ.[22] Gt may be difficult to measure without special equipment. g was earlier often subdivided into only ")
				print ("Gf and Gc, which were thought to correspond to the nonverbal or performance subtests and verbal subtests in earlier versions of") 
				print ("the popular Wechsler IQ test. More recent research has shown the situation to be more complex.[22] Modern comprehensive IQ ")
				print ("tests do not stop at reporting a single IQ score. Although they still give an overall score, they now also give scores for ")
				print ("many of these more restricted abilities, identifying particular strengths and weaknesses of an individual.[22]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Other theories")
				print (" ")
				print ("J.P. Guilford's Structure of Intellect (1967) model used three dimensions which when combined yielded a total of 120 types of") 
				print ("intelligence. It was popular in the 1970s and early 1980s, but faded owing to both practical problems and theoretical")
				print ("criticisms.[22]")
				print (" ")
				print ("Alexander Luria's earlier work on neuropsychological processes led to the PASS theory (1997). It argued that only looking at ")
				print ("one general factor was inadequate for researchers and clinicians who worked with learning disabilities, attention disorders,") 
				print ("intellectual disability, and interventions for such disabilities. The PASS model covers four kinds of processes (planning ")
				print ("process, attention/arousal process, simultaneous processing, and successive processing). The planning processes involve ")
				print ("decision making, problem solving, and performing activities and requires goal setting and self-monitoring.")
				print (" ")
				print ("The attention/arousal process involves selectively attending to a particular stimulus, ignoring distractions, and maintaining") 
				print ("vigilance. Simultaneous processing involves the integration of stimuli into a group and requires the observation of ")
				print ("relationships. Successive processing involves the integration of stimuli into serial order. The planning and attention/arousal") 
				print ("components comes from structures located in the frontal lobe, and the simultaneous and successive processes come from ")
				print ("structures located in the posterior region of the cortex.[39][40][41] It has influenced some recent IQ tests, and been seen as")			
				print ("a complement to the Cattell-Horn-Carroll theory described above.[22]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Current tests")
				print ("Normalized IQ distribution with mean 100 and standard deviation 15.")
				print (" ")
				print ("There are a variety of individually administered IQ tests in use in the English-speaking world.[42][43] The most commonly used") 
				print ("individual IQ test series is the Wechsler Adult Intelligence Scale for adults and the Wechsler Intelligence Scale for Children ")
				print ("for school-age test-takers. Other commonly used individual IQ tests (some of which do not label their standard scores as ''IQ''")
				print ("scores) include the current versions of the Stanford-Binet Intelligence Scales, Woodcock-Johnson Tests of Cognitive Abilities, ")
				print ("the Kaufman Assessment Battery for Children, the Cognitive Assessment System, and the Differential Ability Scales.")
				print (" ")
				print ("IQ tests that measure intelligence also include:")
				print (" ")
				print ("    Raven's Progressive Matrices ")
				print ("    Cattell Culture Fair III ")
				print ("    Reynolds Intellectual Assessment Scales ")
				print ("    Thurstone's Primary Mental Abilities[44][45] ")
				print ("    Kaufman Brief Intelligence Test[46]")
				print ("   Multidimensional Aptitude Battery II")
				print ("   Das–Naglieri cognitive assessment system")
				print (" ")
				print ("IQ scales are ordinally scaled.[47][48][49][50][51] While one standard deviation is 15 points, and two SDs are 30 points, and")
				print ("so on, this does not imply that mental ability is linearly related to IQ, such that IQ 50 means half the cognitive ability of ")
				print ("IQ 100. In particular, IQ points are not percentage points.")
				print (" ")
				print ("On a related note, this fixed standard deviation means that the proportion of the population who have IQs in a particular range") 
				print ("is theoretically fixed, and current Wechsler tests only give Full Scale IQs between 40 and 160. This should be borne in mind ")
				print ("when considering reports of people with much higher IQs.[52][53]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Test bias or differential item functioning")
				print (" ")
				print ("Differential item functioning (DIF), sometimes referred to as measurement bias, is a phenomenon when participants from ")
				print ("different groups (e.g. gender, race, disability) with the same latent abilities give different answers to specific questions on ")
				print ("the same IQ test.[54] DIF analysis measures such specific items on a test alongside measuring participants latent abilities on ")
				print ("other similar questions. A consistent different group response to a specific question among similar type of questions can ")
				print ("indicate an effect of DIF. It does not count as differential item functioning if both groups have equally valid chance of ")
				print ("giving different responses to the same questions. Such bias can be a result of culture, educational level and other factors")
				print ("that are independent of group traits. DIF is only considered if test-takers from different groups with the same underlying ")
				print ("latent ability level have a different chance of giving specific responses.[55] Such questions are usually removed in order to") 
				print ("make the test equally fair for both groups. Common techniques for analyzing DIF are item response theory (IRT) based methods, ")
				print ("Mantel-Haenszel, and logistic regression.[55]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Reliability and validity")
				print (" ")
				print ("Psychometricians generally regard IQ tests as having high statistical reliability.[9][56] A high reliability implies that – ")
				print ("although test-takers may have varying scores when taking the same test on differing occasions, and although they may have ")
				print ("varying scores when taking different IQ tests at the same age – the scores generally agree with one another and across time.")
				print ("Like all statistical quantities, any particular estimate of IQ has an associated standard error that measures uncertainty about ")
				print ("the estimate. For modern tests, the standard error of measurement is about three points[citation needed]. Clinical psychologists")
				print ("generally regard IQ scores as having sufficient statistical validity for many clinical purposes.[22][57][58] In a survey of 661")
				print ("randomly sampled psychologists and educational researchers, published in 1988, Mark Snyderman and Stanley Rothman reported a") 
				print ("general consensus supporting the validity of IQ testing. ''On the whole, scholars with any expertise in the area of ")
				print ("intelligence and intelligence testing (defined very broadly) share a common view of the most important components of ")
				print ("intelligence, and are convinced that it can be measured with some degree of accuracy.'' Almost all respondents picked out ")
				print ("abstract reasoning, ability to solve problems and ability to acquire knowledge as the most important elements.[59]")
				print (" ")
				print ("IQ scores can differ to some degree for the same person on different IQ tests, so a person does not always belong to the same") 
				print ("IQ score range each time the person is tested. (IQ score table data and pupil pseudonyms adapted from description of KABC-II ")
				print ("norming study cited in Kaufman 2009.[60][61]) Pupil 	KABC-II 	WISC-III 	WJ-III")
				print ("Asher 	90 	95 	111")
				print ("Brianna 	125 	110 	105")
				print ("Colin 	100 	93 	101")
				print ("Danica 	116 	127 	118")
				print ("Elpha 	93 	105 	93")
				print ("Fritz 	106 	105 	105")
				print ("Georgi 	95 	100 	90")
				print ("Hector 	112 	113 	103")
				print ("Imelda 	104 	96 	97")
				print ("Jose 	101 	99 	86")
				print ("Keoku 	81 	78 	75")
				print ("Leo 	116 	124 	102")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Flynn effect")
				print ("Main article: Flynn effect")
				print (" ")
				print ("Since the early 20th century, raw scores on IQ tests have increased in most parts of the world.[62][63][64] When a new version ")
				print ("of an IQ test is normed, the standard scoring is set so performance at the population median results in a score of IQ 100. The ")
				print ("phenomenon of rising raw score performance means if test-takers are scored by a constant standard scoring rule, IQ test scores ")
				print ("have been rising at an average rate of around three IQ points per decade. This phenomenon was named the Flynn effect in the") 
				print ("book The Bell Curve after James R. Flynn, the author who did the most to bring this phenomenon to the attention of ")
				print ("psychologists.[65][66]")
				print (" ")
				print ("Researchers have been exploring the issue of whether the Flynn effect is equally strong on performance of all kinds of IQ test") 
				print ("items, whether the effect may have ended in some developed nations, whether there are social subgroup differences in the ")
				print ("effect, and what possible causes of the effect might be.[67] A 2011 textbook, IQ and Human Intelligence, by N. J. Mackintosh, ")
				print ("noted the Flynn effect demolishes the fears that IQ would be decreased. He also asks whether it represents a real increase in ")
				print ("intelligence beyond IQ scores.[68] A 2011 psychology textbook, lead authored by Harvard Psychologist Professor Daniel Schacter, ")
				print ("noted that humans' inherited intelligence could be going down while acquired intelligence goes up.[69]")
				print (" ")
				print ("Research has revealed that the Flynn effect has slowed or reversed course in several Western countries beginning in the late")
				print ("20th century. The phenomenon has been termed the negative Flynn effect.[70][71] A study of Norwegian military conscripts' test ")
				print ("records found that IQ scores have been falling for generations born after the year 1975, and that the underlying nature of both ")
				print ("initial increasing and subsequent falling trends appears to be environmental rather than genetic.[71]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Age")
				print (" ")
				print ("IQ can change to some degree over the course of childhood.[72] However, in one longitudinal study, the mean IQ scores of ")
				print ("tests at ages 17 and 18 were correlated at r=0.86 with the mean scores of tests at ages five, six, and seven and at r=0.96 with")
				print ("the mean scores of tests at ages 11, 12, and 13.[9]")
				print (" ")
				print ("For decades, practitioners' handbooks and textbooks on IQ testing have reported IQ declines with age after the beginning of ")
				print ("adulthood. However, later researchers pointed out this phenomenon is related to the Flynn effect and is in part a cohort effect") 
				print ("rather than a true aging effect. A variety of studies of IQ and aging have been conducted since the norming of the first ")
				print ("Wechsler Intelligence Scale drew attention to IQ differences in different age groups of adults. Current consensus is that fluid")
				print ("intelligence generally declines with age after early adulthood, while crystallized intelligence remains intact. Both cohort")
				print ("effects (the birth year of the test-takers) and practice effects (test-takers taking the same form of IQ test more than once)") 
				print ("must be controlled to gain accurate data. It is unclear whether any lifestyle intervention can preserve fluid intelligence into ")
				print ("older ages.[73]")
				print (" ")
				print ("The exact peak age of fluid intelligence or crystallized intelligence remains elusive. Cross-sectional studies usually show ")
				print ("that especially fluid intelligence peaks at a relatively young age (often in the early adulthood) while longitudinal data ")
				print ("mostly show that intelligence is stable until mid-adulthood or later. Subsequently, intelligence seems to decline slowly.[74]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Genetics and environment")
				print (" ")
				print ("Environmental and genetic factors play a role in determining IQ. Their relative importance has been the subject of much ")
				print ("research and debate.[75]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Heritability")
				print ("See also: Heritability of IQ and Environment and intelligence")
				print (" ")
				print ("Heritability is defined as the proportion of variance in a trait which is attributable to genotype within a defined population ")
				print ("in a specific environment. A number of points must be considered when interpreting heritability.[76] Heritability, as a term, ")
				print ("applies to populations, and in populations there are variations in traits between individuals. Heritability measures how much ")
				print ("of that variation is caused by genetics. The value of heritability can change if the impact of environment (or of genes) in the ")
				print ("population is substantially altered. A high heritability of a trait does not mean environmental effects, such as learning, are") 
				print ("not involved. Since heritability increases during childhood and adolescence, one should be cautious drawing conclusions ")
				print ("regarding the role of genetics and environment from studies where the participants are not followed until they are adults.")
				print ("[citation needed]")
				print (" ")
				print ("The general figure for the heritability of IQ, according to an authoritative American Psychological Association report, is ")
				print ("0.45 for children, and rises to around 0.75 for late adolescents and adults.[77][78] Heritability measures in infancy are as ")
				print ("low as 0.2, around 0.4 in middle childhood, and as high as 0.9 in adulthood.[79][80] One proposed explanation is that people ")
				print ("with different genes tend to reinforce the effects of those genes, for example by seeking out different environments.[9][81]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Shared family environment")
				print (" ")
				print ("Family members have aspects of environments in common (for example, characteristics of the home). This shared family")
				print ("environment accounts for 0.25–0.35 of the variation in IQ in childhood. By late adolescence, it is quite low ")
				print ("(zero in some studies). The effect for several other psychological traits is similar. These studies have not looked at the ")
				print ("effects of such extreme environments, such as in abusive families.[9][82][83][84]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Non-shared family environment and environment outside the family")
				print (" ")
				print ("Although parents treat their children differently, such differential treatment explains only a small amount of ")				
				print ("nonshared environmental influence. One suggestion is that children react differently to the same environment because of ")
				print ("different genes. More likely influences may be the impact of peers and other experiences outside the family.[9][83]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Individual genes")
				print (" ")
				print ("A very large proportion of the over 17,000 human genes are thought to have an effect on the development and functionality of ")
				print ("the brain.[85] While a number of individual genes have been reported to be associated with IQ, none have a strong effect. Deary")
				print ("and colleagues (2009) reported that no finding of a strong single gene effect on IQ has been replicated.[86] Recent findings of ")
				print ("gene associations with normally varying intelligence differences in adults continue to show weak effects for any one gene;[87] ")
				print ("likewise in children,[88] but see.[89]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Gene-environment interaction")
				print (" ")
				print ("David Rowe reported an interaction of genetic effects with socioeconomic status, such that the heritability was high in ")
				print ("high-SES families, but much lower in low-SES families.[90] In the US, this has been replicated in infants,[91] children,[92]") 
				print ("adolescents,[93] and adults.[94] Outside the US, studies show no link between heritability and SES.[95] Some effects may even ")
				print ("reverse sign outside the US.[95][96]")
				print (" ")
				print ("Dickens and Flynn (2001) have argued that genes for high IQ initiate an environment-shaping feedback cycle, with genetic") 
				print ("effects causing bright children to seek out more stimulating environments that then further increase their IQ. In Dickens") 
				print ("model, environment effects are modeled as decaying over time. In this model, the Flynn effect can be explained by an increase") 
				print ("in environmental stimulation independent of it being sought out by individuals. The authors suggest that programs aiming to ")
				print ("increase IQ would be most likely to produce long-term IQ gains if they enduringly raised children's drive to seek out ")
				print ("cognitively demanding experiences.[97][98]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Interventions")
				print (" ")
				print ("In general, educational interventions, as those described below, have shown short-term effects on IQ, but long-term follow-up ")
				print ("is often missing. For example, in the US very large intervention programs such as the Head Start Program have not produced ")
				print ("lasting gains in IQ scores. More intensive, but much smaller projects such as the Abecedarian Project have reported lasting ")
				print ("effects, often on socioeconomic status variables, rather than IQ.[9]")
				print (" ")
				print ("Recent studies have shown that training in using one's working memory may increase IQ. A study on young adults published in") 
				print ("April 2008 by a team from the Universities of Michigan and Bern supports the possibility of the transfer of fluid intelligence") 
				print ("from specifically designed working memory training.[99] Further research will be needed to determine nature, extent and ")
				print ("duration of the proposed transfer. Among other questions, it remains to be seen whether the results extend to other kinds of") 
				print ("fluid intelligence tests than the matrix test used in the study, and if so, whether, after training, fluid intelligence ")
				print ("measures retain their correlation with educational and occupational achievement or if the value of fluid intelligence for ")
				print ("predicting performance on other tasks changes. It is also unclear whether the training is durable of extended periods of time.")
				print ("[100]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Music")
				print (" ")
				print ("Musical training in childhood has been found to correlate with higher than average IQ.[101][102] It is popularly thought that ")
				print ("listening to classical music raises IQ. However, multiple attempted replications (e.g.[103]) have shown that this is at best a ")
				print ("short-term effect (lasting no longer than 10 to 15 minutes), and is not related to IQ-increase.[104]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Brain anatomy")
				print ("Main article: Neuroscience and intelligence")
				print (" ")
				print ("Several neurophysiological factors have been correlated with intelligence in humans, including the ratio of brain weight to ")
				print ("body weight and the size, shape, and activity level of different parts of the brain. Specific features that may affect IQ ")
				print ("include the size and shape of the frontal lobes, the amount of blood and chemical activity in the frontal lobes, the total") 
				print ("amount of gray matter in the brain, the overall thickness of the cortex, and the glucose metabolic rate.[105]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Health")
				print ("Main articles: Impact of health on intelligence and Cognitive epidemiology")
				print (" ")
				print ("Health is important in understanding differences in IQ test scores and other measures of cognitive ability. Several factors ")
				print ("can lead to significant cognitive impairment, particularly if they occur during pregnancy and childhood when the brain is ")
				print ("growing and the blood–brain barrier is less effective. Such impairment may sometimes be permanent, sometimes be partially or") 
				print ("wholly compensated for by later growth.[citation needed]")
				print (" ")
				print ("Since about 2010, researchers such as Eppig, Hassel, and MacKenzie have found a very close and consistent link between IQ ")
				print ("scores and infectious diseases, especially in the infant and preschool populations and the mothers of these children.[106] ")
				print ("They have postulated that fighting infectious diseases strains the child's metabolism and prevents full brain development. ")
				print ("Hassel postulated that it is by far the most important factor in determining population IQ. However, they also found that ")
				print ("subsequent factors such as good nutrition and regular quality schooling can offset early negative effects to some extent.")
				print (" ")
				print ("Developed nations have implemented several health policies regarding nutrients and toxins known to influence cognitive function.")
				print ("These include laws requiring fortification of certain food products and laws establishing safe levels of pollutants (e.g. lead,")
				print ("mercury, and organochlorides). Improvements in nutrition, and in public policy in general, have been implicated in worldwide ")
				print ("IQ increases.[citation needed]")
				print (" ")
				print ("Cognitive epidemiology is a field of research that examines the associations between intelligence test scores and health. ")
				print ("Researchers in the field argue that intelligence measured at an early age is an important predictor of later health and ")
				print ("mortality differences.")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Social correlations")
				more1 = input("School performance")
				print (" ")
				print ("The American Psychological Association's report Intelligence: Knowns and Unknowns states that wherever it has been studied, ")
				print ("children with high scores on tests of intelligence tend to learn more of what is taught in school than their lower-scoring ")
				print ("peers. The correlation between IQ scores and grades is about .50. This means that the explained variance is 25%. Achieving good ")
				print ("grades depends on many factors other than IQ, such as ''persistence, interest in school, and willingness to study'' (p. 81).[9]")
				print (" ")
				print ("It has been found that the correlation of IQ scores with school performance depends on the IQ measurement used. For ")
				print ("undergraduate students, the Verbal IQ as measured by WAIS-R has been found to correlate significantly (0.53) with the grade")
				print ("point average (GPA) of the last 60 hours. In contrast, Performance IQ correlation with the same GPA was only 0.22 in the same") 
				print ("study.[107]")
				print (" ")
				print ("Some measures of educational aptitude correlate highly with IQ tests – for instance, Frey and Detterman (2004) reported a ")
				print ("correlation of 0.82 between g (general intelligence factor) and SAT scores;[108] another research found a correlation of 0.81")
				print ("between g and GCSE scores, with the explained variance ranging ''from 58.6% in Mathematics and 48% in English to 18.1% in Art ")
				print ("and Design''.[109]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Job performance")
				print (" ")
				print ("According to Schmidt and Hunter, ''for hiring employees without previous experience in the job the most valid predictor of ")
				print ("future performance is general mental ability.''[110] The validity of IQ as a predictor of job performance is above zero for ")
				print ("all work studied to date, but varies with the type of job and across different studies, ranging from 0.2 to 0.6.[111] The ")
				print ("correlations were higher when the unreliability of measurement methods was controlled for.[9] While IQ is more strongly ")
				print ("correlated with reasoning and less so with motor function,[112] IQ-test scores predict performance ratings in all occupations.")
				print ("[110] That said, for highly qualified activities (research, management) low IQ scores are more likely to be a barrier to ")
				print ("adequate performance, whereas for minimally-skilled activities, athletic strength (manual strength, speed, stamina, and ")
				print ("coordination) are more likely to influence performance.[110] The prevailing view among academics is that it is largely ")
				print ("through the quicker acquisition of job-relevant knowledge that higher IQ mediates job performance. This view has been ")
				print ("challenged by Byington & Felps (2010), who argued that ''the current applications of IQ-reflective tests allow individuals ")
				print ("with high IQ scores to receive greater access to developmental resources, enabling them to acquire additional capabilities") 
				print ("over time, and ultimately perform their jobs better.''[113]")
				print (" ")
				print ("In establishing a causal direction to the link between IQ and work performance, longitudinal studies by Watkins and others ")
				print ("suggest that IQ exerts a causal influence on future academic achievement, whereas academic achievement does not substantially") 
				print ("influence future IQ scores.[114] Treena Eileen Rohde and Lee Anne Thompson write that general cognitive ability, but not")
				print ("specific ability scores, predict academic achievement, with the exception that processing speed and spatial ability predict")
				print ("performance on the SAT math beyond the effect of general cognitive ability.[115]")
				print (" ")
				print ("The US military has minimum enlistment standards at about the IQ 85 level. There have been two experiments with lowering this")
				print ("to 80 but in both cases these men could not master soldiering well enough to justify their costs.[116]")
				more1 = input("Income")
				print (" ")
				print ("While it has been suggested that ''in economic terms it appears that the IQ score measures something with decreasing ")
				print ("marginal value. It is important to have enough of it, but having lots and lots does not buy you that much'',[117][118] ")
				print ("large-scale longitudinal studies indicate an increase in IQ translates into an increase in performance at all levels of IQ:") 
				print ("i.e. ability and job performance are monotonically linked at all IQ levels.[119][120] Charles Murray, coauthor of The Bell ")
				print ("Curve, found that IQ has a substantial effect on income independent of family background.[121]")
				print (" ")
				print ("The link from IQ to wealth is much less strong than that from IQ to job performance. Some studies indicate that IQ is unrelated")
				print ("to net worth.[122][123]")
				print (" ")
				print ("The American Psychological Association's 1995 report Intelligence: Knowns and Unknowns stated that IQ scores accounted for ")
				print ("(explained variance) about a quarter of the social status variance and one-sixth of the income variance. Statistical controls") 
				print ("for parental SES eliminate about a quarter of this predictive power. Psychometric intelligence appears as only one of a great")
				print ("many factors that influence social outcomes.[9]")
				print (" ")
				print ("In a meta-analysis, Strenze (2006) reviewed much of the literature and estimated the correlation between IQ and income to be ")
				print ("about 0.23.[124]")
				print (" ")
				print ("Some studies claim that IQ only accounts for (explains) a sixth of the variation in income because many studies are based on") 
				print ("young adults, many of whom have not yet reached their peak earning capacity, or even their education. On pg 568 of The g ")
				print ("Factor, Arthur Jensen claims that although the correlation between IQ and income averages a moderate 0.4 (one sixth or 16% ")
				print ("of the variance), the relationship increases with age, and peaks at middle age when people have reached their maximum career")
				print ("potential. In the book, A Question of Intelligence, Daniel Seligman cites an IQ income correlation of 0.5 (25% of the variance).")
				print (" ")
				print ("A 2002 study[125] further examined the impact of non-IQ factors on income and concluded that an individual's location, ")
				print ("inherited wealth, race, and schooling are more important as factors in determining income than IQ.")
				more1 = input("Crime")
				print (" ")
				print ("The American Psychological Association's 1995 report Intelligence: Knowns and Unknowns stated that the correlation between ")
				print ("IQ and crime was −0.2. It was −0.19 between IQ scores and number of juvenile offenses in a large Danish sample; with social")
				print ("class controlled, the correlation dropped to −0.17. A correlation of 0.20 means that the explained variance is 4%. The causal")
				print ("links between psychometric ability and social outcomes may be indirect. Children with poor scholastic performance may feel")
				print ("alienated. Consequently, they may be more likely to engage in delinquent behavior, compared to other children who do well.[9]")
				print (" ")
				print ("In his book The g Factor (1998), Arthur Jensen cited data which showed that, regardless of race, people with IQs between 70 ")
				print ("and 90 have higher crime rates than people with IQs below or above this range, with the peak range being between 80 and 90.")
				print (" ")
				print ("The 2009 Handbook of Crime Correlates stated that reviews have found that around eight IQ points, or 0.5 SD, separate criminals")
				print ("from the general population, especially for persistent serious offenders. It has been suggested that this simply reflects that ")
				print ("''only dumb ones get caught'' but there is similarly a negative relation between IQ and self-reported offending. That children")
				print ("with conduct disorder have lower IQ than their peers ''strongly argues'' for the theory.[126]")
				print (" ")
				print ("A study of the relationship between US county-level IQ and US county-level crime rates found that higher average IQs were ")
				print ("associated with lower levels of property crime, burglary, larceny rate, motor vehicle theft, violent crime, robbery, and ")
				print ("aggravated assault. These results were not ''confounded by a measure of concentrated disadvantage that captures the effects")
				print ("of race, poverty, and other social disadvantages of the county.''[127][128]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Health and mortality")
				print (" ")
				print ("Multiple studies conducted in Scotland have found that higher IQs in early life are associated with lower mortality and")
				print ("morbidity rates later in life.[129][130]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Other accomplishments")
				print ("Average adult combined IQs associated with real-life accomplishments by various tests[131][132] Accomplishment 	IQ 	Test/study ")
				print ("Year")
				print ("MDs, JDs, and PhDs 	125 	WAIS-R 	1987")
				print ("College graduates 	112 	KAIT 	2000")
				print ("K-BIT 	1992")
				print ("115 	WAIS-R") 	
				print ("1–3 years of college 	104 	KAIT ")	
				print ("K-BIT 	")
				print ("105–110 	WAIS-R 	")
				print ("Clerical and sales workers 	100–105 		")
				print ("High school graduates, skilled workers (e.g., electricians, cabinetmakers) 	100 	KAIT ")	
				print ("WAIS-R 	")
				print ("97 	K-BIT 	")
				print ("1–3 years of high school (completed 9–11 years of school) 	94 	KAIT 	")
				print ("90 	K-BIT 	")
				print ("95 	WAIS-R 	")
				print ("Semi-skilled workers (e.g. truck drivers, factory workers) 	90–95 ")		
				print ("Elementary school graduates (completed eighth grade) 	90 		")
				print ("Elementary school dropouts (completed 0–7 years of school) 	80–85 		")
				print ("Have 50/50 chance of reaching high school 	75 		")
				print ("Average IQ of various occupational groups:[133] Accomplishment 	IQ 	Test/study 	Year")
				print ("Professional and technical 	112 		")
				print ("Managers and administrators 	104 		")
				print ("Clerical workers, sales workers, skilled workers, craftsmen, and foremen 	101 		")
				print ("Semi-skilled workers (operatives, service workers, including private household) 	92") 		
				print ("Unskilled workers 	87 		")
				print ("Type of work that can be accomplished:[131] Accomplishment 	IQ 	Test/study 	Year")
				print ("Adults can harvest vegetables, repair furniture 	60 ")		
				print ("Adults can do domestic work 	50 	")	
				print (" ")
				print ("There is considerable variation within and overlap among these categories. People with high IQs are found at all levels of ")
				print ("education and occupational categories. The biggest difference occurs for low IQs with only an occasional college graduate or")
				print ("professional scoring below 90.[22]")
				more1 = input("Group-IQ or the collective intelligence factor c")
				print ("\n\n\n\n\n\n\n")
				print ("Main article: Collective intelligence")
				print (" ")
				print ("With operationalization and methodology derived from the general intelligence factor g, a new scientific understanding of ")
				print ("collective intelligence, defined as a group’s general ability to perform a wide range of tasks,[134] aims to explain ")
				print ("intelligent behavior of groups. Goal is to detect and explain a general intelligence factor c for groups, parallel to the g ")
				print ("factor for individuals. As g is highly interrelated with the concept of IQ,[135][136] this measurement of collective ")
				print ("intelligence can be interpreted as intelligence quotient for groups (Group-IQ) even though the score is not a quotient per se")
				print ("Current evidence suggests that this Group-IQ is only moderately correlated with group members' IQs but with other correlates")
				print ("such as group members' Theory of Mind.[134]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Group differences")
				print (" ")
				print ("Among the most controversial issues related to the study of intelligence is the observation that intelligence measures such as ")
				print ("IQ scores vary between ethnic and racial groups and sexes. While there is little scholarly debate about the existence of some ")
				print ("of these differences, their causes remain highly controversial both within academia and in the public sphere.[137]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Sex")
				print ("Main article: Sex differences in intelligence")
				print (" ")
				print ("Most IQ tests are constructed so that there are no overall score differences between females and males.[9][138] Popular IQ ")
				print ("batteries such as the WAIS and the WISC-R are also constructed in order to eliminate sex differences.[139] In a paper")
				print ("presented at the International Society for Intelligence Research in 2002, it was pointed out that because test constructors")
				print ("and the United States' Educational Testing Service (which developed the US SAT test) often eliminate items showing marked ")
				print ("sex differences in order to reduce the perception of bias, the ''true sex'' difference is masked. Items like the Mental ")
				print ("Rotations Test and reaction time tests, which show a male advantage in IQ, are often removed.[140] Meta-analysis focusing on") 
				print ("gender differences in math performance found nearly identical performance for boys and girls,[141] and the subject of ")
				print ("mathematical intelligence and gender has been controversial.[142]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("IQ by country")
				more1 = input("Race and intelligence")
				print ("Main articles: Race and intelligence and Nations and intelligence")
				print ("Race and intelligence in United States of America")
				print (" ")
				print ("The 1996 Task Force investigation on Intelligence sponsored by the American Psychological Association concluded that there")
				print ("are significant variations in IQ across races.[9] The problem of determining the causes underlying this variation relates ")
				print ("to the question of the contributions of ''nature and nurture'' to IQ. Psychologists such as Alan S. Kaufman[143] and Nathan")
				print ("Brody[144] and statisticians such as Bernie Devlin[145] argue that there are insufficient data to conclude that this is ")
				print ("because of genetic influences. A review article published in 2012 by leading scholars on human intelligence concluded, ")
				print ("after reviewing the prior research literature, that group differences in IQ are best understood as environmental in origin.")
				print ("[146]")
				print (" ")
				print ("In considering disparities between test results of different ethnic groups, one might investigate the effects of stereotype ")
				print ("threat (a situational predicament in which a person feels at risk of confirming negative stereotypes about the group(s) he ")
				print ("identifies with),[147] as well as culture and acculturation.[148] This phenomenon has been criticized as a fiction of ")
				print ("publication bias.[149]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Public policy")
				print ("Main article: Intelligence and public policy")
				print (" ")
				print ("In the United States, certain public policies and laws regarding military service,[150][151] education, public benefits,")
				print ("[152] capital punishment,[153] and employment incorporate an individual's IQ into their decisions. However, in the case of") 
				print ("Griggs v. Duke Power Co. in 1971, for the purpose of minimizing employment practices that disparately impacted racial")
				print ("minorities, the U.S. Supreme Court banned the use of IQ tests in employment, except when linked to job performance via a job") 
				print ("analysis. Internationally, certain public policies, such as improving nutrition and prohibiting neurotoxins, have as one of ")
				print ("their goals raising, or preventing a decline in, intelligence.")
				print (" ")
				print ("A diagnosis of intellectual disability is in part based on the results of IQ testing. Borderline intellectual functioning is a") 
				print ("categorization where a person has below average cognitive ability (an IQ of 71–85), but the deficit is not as severe as ")
				print ("intellectual disability (70 or below).")
				print (" ")
				print ("In the United Kingdom, the eleven plus exam which incorporated an intelligence test has been used from 1945 to decide, at")
				print ("eleven years of age, which type of school a child should go to. They have been much less used since the widespread ")
				print ("introduction of comprehensive schools.")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Criticism and views")
				more1 = input("Relationship to intelligence")
				print ("See also: Intelligence")
				print (" ")
				print ("IQ is the most thoroughly researched means of measuring intelligence, and by far the most widely used in practical settings. ")
				print ("However, while IQ strives to measure some concepts of intelligence, it may fail to serve as an accurate measure of broader ")
				print ("definitions of intelligence. IQ tests examine some areas of intelligence, while neglecting to account for other areas, such as")
				print ("creativity and social intelligence.")
				print (" ")
				print ("Critics such as Keith Stanovich do not dispute the reliability of IQ test scores or their capacity to predict some kinds of")
				print ("achievement, but argue that basing a concept of intelligence on IQ test scores alone neglects other important aspects of") 
				print ("mental ability.[9][154]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Criticism of IQ")
				print (" ")
				print ("Some scientists dispute the worthiness of IQ entirely. In The Mismeasure of Man (1996), paleontologist Stephen Jay Gould")
				print ("criticized IQ tests and argued that they were used for scientific racism. He argued that g was a mathematical artifact and") 
				print ("criticized:")
				print (" ")
				print ("	...the abstraction of intelligence as a single entity, its location within the brain, its quantification as one number ")
				print ("for each individual, and the use of these numbers to rank people in a single series of worthiness, invariably to find that ")
				print ("oppressed and disadvantaged groups—races, classes, or sexes—are innately inferior and deserve their status.[155] ")
				print (" ")
				print ("Arthur Jensen responded:")
				print (" ")
				print ("    ...what Gould has mistaken for ''reification'' is neither more nor less than the common practice in every science of") 
				print ("hypothesizing explanatory models to account for the observed relationships within a given domain. Well known examples ")
				print ("include the heliocentric theory of planetary motion, the Bohr atom, the electromagnetic field, the kinetic theory of gases,") 
				print ("gravitation, quarks, Mendelian genes, mass, velocity, etc. None of these constructs exists as a palpable entity occupying")
				print ("physical space.[156] ")
				print (" ")
				print ("Jensen also argued that even if g were replaced by a model with several intelligences this would change the situation less ")
				print ("than expected. He argues that all tests of cognitive ability would continue to be highly correlated with one another and there")
				print ("would still be a black-white gap on cognitive tests.[157] Hans Eysenck responded to Gould by stating that no psychologist had")
				print ("said that intelligence was an area located in the brain.[158] Eysenck also argued IQ tests were not racist, pointing out that")
				print ("Northeast Asians and Jews both scored higher than non-Jewish Europeans on IQ tests, and this would not please European racists.")
				print ("[159]")
				print (" ")
				print ("Psychologist Peter Schönemann persistently criticized IQ, calling it ''the IQ myth''. He argued that g is a flawed theory")
				print ("and that the high heritability estimates of IQ are based on false assumptions.[160][161] Robert Sternberg, another significant")
				print ("critic of g as the main measure of human cognitive abilities, argued that reducing the concept of intelligence to the")
				print ("measure of g does not fully account for the different skills and knowledge types that produce success in human society.[162]")
				more1 = input("Systematic exclusion of threshold effects")
				print ("\n\n\n\n\n\n\n")
				print (" ")
				print ("Cecil Reynolds and Paul Kline argue that the construction of IQ tests around the rule that they should show a bell curve")
				print ("distribution in the population leads to systematic exclusion of cognitive tests that display threshold effects and are not")
				print ("gradually variable, as well as biasing IQ tests towards questions that can be made to fit a bell curve model and against")
				print ("questions that show any non-bell distributions. They argue that just as swarms change their collective behavior at certain")
				print ("thresholds of animals in the swarm, it is possible that brains change their abilities at thresholds of number of connected ")
				print ("neurons and/or level of connectivity. Cecil Reynolds and Paul Kline argue that such a bias may be the reason why IQ tests")
				print ("yield paradoxes such as the heredity paradox between high heredity showed by twin studies and the high environmental")
				print ("effect shown by the Flynn effect and suggest that other cognitive tests that do not conform to bell curve distributions")
				print ("should be tried with the possibility that some of them may produce falsifiable predictions of key abilities requiring a ")
				print ("critical level of underlying quantitative brain access and simpler proxies of such in every case, unlike IQ tests which")
				print ("are argued to fail the falsifiability criterion by defining away problems by systematically demanding bell curves and ")
				print ("failing to make any absolute system requirement predictions of what brain capacity is required to make a certain ")
				print ("performance. It is argued that probabilistic predictions with loopholes for ''exceptions'' are not scientifically ")
				print ("appliceable to capacity theories, as capacities follow minimum system requirements for performing tasks.[163][164]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Test bias")
				print ("See also: Stereotype threat")
				print (" ")
				print ("The American Psychological Association's report Intelligence: Knowns and Unknowns stated that in the United States IQ tests") 
				print ("as predictors of social achievement are not biased against African Americans since they predict future performance, ")
				print ("such as school achievement, similarly to the way they predict future performance for Caucasians.[9] While agreeing that ")
				print ("IQ tests predict performance equally well for all racial groups, Nicholas Mackintosh also points out that there may still") 
				print ("be a bias inherent in IQ testing if the education system is also systematically biased against African Americans, in")
				print ("which case educational performance may in fact also be an underestimation of African American children's cognitive")
				print ("abilities.[165] Earl Hunt points out that while this may be the case that would not be a bias of the test, but of society.[166]")
				print (" ")
				print ("However, IQ tests may well be biased when used in other situations. A 2005 study stated that ''differential validity in ")
				print ("prediction suggests that the WAIS-R test may contain cultural influences that reduce the validity of the WAIS-R as a measure") 
				print ("of cognitive ability for Mexican American students,''[167] indicating a weaker positive correlation relative to sampled ")
				print ("white students. Other recent studies have questioned the culture-fairness of IQ tests when used in South Africa.[168][169]") 
				print ("Standard intelligence tests, such as the Stanford-Binet, are often inappropriate for autistic children; the alternative of ")
				print ("using developmental or adaptive skills measures are relatively poor measures of intelligence in autistic children, and may ")
				print ("have resulted in incorrect claims that a majority of autistic children are mentally retarded.[170]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Intermingling cultures and IQ classification fairness")
				print (" ")
				print ("Barbara P. Uzzell and Harvey N. Switzky argue that defining IQ from an average at a period of time and putting different")
				print ("thresholds of what is considered retarded based on average IQ test performance in a culture faces issues of defining who ")
				print ("belongs to what culture. They argue that since people are not actually in boxes of isolated cultures, essentialistic ")
				print ("classification of culture that is said to make IQ tests ''culturally fair'' will show false ''evidence'' of underlying ")
				print ("cognitive differences between individuals who are formally classified in the same culture but have faced different cultural") 
				print ("non-shared environments due to the fluid intermingling of cultures in real life, making IQ tests a false measure of mental ")
				print ("retardation. It is argued by Barbara P. Uzzell and Harvey N. Switzky that different social treatment depending on hereditary ")
				print ("factors in appearance that may not necessarily be classified as ''racial'' but can often be considered individual leads to an")
				print ("appearance of genes for such appearances being linked to learned behaviors and false evidence of the genes affecting the ")
				print ("brain's response to the environment, and that environmental differences in whether other people with whom a person speaks are") 
				print ("willing to counter misunderstandings with factual arguments or dismisses the person as ''incapable of reasoning if he or she ")
				print ("does not already know it'' creates differences in the opportunities to learn rules that can be used for solving problems in ")
				print ("IQ tests and that widespread persistence of such cultural treatment gives a false appearance of IQ tests being reliable ")
				print ("and valid measures of underlying cognitive abilities. It is argued that such effects of different opportunities to ")
				print ("sharpen arguments through debate in all walks of life, including prejudice towards choice of words shaped by earlier ")
				print ("differences in debate opportunities, make different predictions than lab setting only stereotype threat theory and ")
				print ("must therefore be tested by different evidence than that theory, and that discrimination in society based on choice of") 
				print ("words is a possible explanation of apparent links between IQ test performance and success in society.[171][172]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Outdated methodology")
				print ("See also: Psychometrics")
				print (" ")
				print ("According to a 2006 article, contemporary psychological research often did not reflect substantial recent developments in ")
				print ("psychometrics and ''bears an uncanny resemblance to the psychometric state of the art as it existed in the 1950s.''[173]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Intelligence: Knowns and Unknowns")
				print (" ")
				print ("In response to the controversy surrounding The Bell Curve, the American Psychological Association's Board of Scientific ")
				print ("Affairs established a task force in 1995 to write a report on the state of intelligence research which could be used by all") 
				print ("sides as a basis for discussion, Intelligence: Knowns and Unknowns. The full text of the report is available through several ")
				print ("websites.[9]")
				print (" ")
				print ("In this paper, the representatives of the association regret that IQ-related works are frequently written with a view to ")
				print ("their political consequences: ''research findings were often assessed not so much on their merits or their scientific ")
				print ("standing as on their supposed political implications''.")
				print (" ")
				print ("The task force concluded that IQ scores do have high predictive validity for individual differences in school ")
				print ("achievement. They confirm the predictive validity of IQ for adult occupational status, even when variables such as ")
				print ("education and family background have been statistically controlled. They stated that individual differences in ")
				print ("intelligence are substantially influenced by both genetics and environment.")
				print (" ")
				print ("The report stated that a number of biological factors, including malnutrition, exposure to toxic substances, and various ")
				print ("prenatal and perinatal stressors, result in lowered psychometric intelligence under at least some conditions. The task ")
				print ("force agrees that large differences do exist between the average IQ scores of blacks and whites, saying")
				print (" ")
				print ("	The cause of that differential is not known; it is apparently not due to any simple form of bias in the content or ")
				print ("	administration of the tests themselves. The Flynn effect shows that environmental factors can produce differences of at") 
				print ("	least this magnitude, but that effect is mysterious in its own right. Several culturally based explanations of the ")
				print ("	Black/ White IQ differential have been proposed; some are plausible, but so far none has been conclusively supported.") 
				print ("	There is even less empirical support for a genetic interpretation. In short, no adequate explanation of the ")
				print ("	differential between the IQ means of Blacks and Whites is presently available. ")
				print (" ")
				print ("The APA journal that published the statement, American Psychologist, subsequently published eleven critical responses in ")
				print ("January 1997, several of them arguing that the report failed to examine adequately the evidence for partly genetic ")
				print ("explanations.")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Dynamic assessment")
				print (" ")
				print ("An alternative to standard IQ tests originated in the writings of psychologist Lev Vygotsky (1896–1934) from his ")
				print ("last two years of work.[174][175] The notion of the zone of proximal development that he introduced in 1933, ")
				print ("roughly a year before his death, served as the banner for his proposal to diagnose development as the level of actual") 
				print ("development that can be measured by the child's independent problem solving and, at the same time, the level of proximal,") 
				print ("or potential development that is measured in the situation of moderately assisted problem solving by the child.[176] The ")
				print ("maximum level of complexity and difficulty of the problem that the child is capable to solve under some guidance indicates ")
				print ("the level of potential development. Then, the difference between the higher level of potential and the lower level of ")
				print ("actual development indicates the zone of proximal development. Combination of the two indexes—the level of actual and the") 
				print ("zone of the proximal development—according to Vygotsky, provides a significantly more informative indicator of psychological") 
				print ("development than the assessment of the level of actual development alone.[177][178]")
				print (" ")
				print ("The ideas on the zone of development were later developed in a number of psychological and educational theories and ")
				print ("practices. Most notably, they were developed under the banner of dynamic assessment that focuses on the testing of ")
				print ("learning and developmental potential[179][180][181] (for instance, in the work of Reuven Feuerstein and his associates,[182]") 
				print ("who has criticized standard IQ testing for its putative assumption or acceptance of ''fixed and immutable'' characteristics ")
				print ("of intelligence or cognitive functioning). Grounded in developmental theories of Vygotsky and Feuerstein, who maintained ")
				print ("that human beings are not static entities but are always in states of transition and transactional relationships with the ")
				print ("world, dynamic assessment received also considerable support in the recent revisions of cognitive developmental theory by ")
				print ("Joseph Campione, Ann Brown, and John D. Bransford and in theories of multiple intelligences by Howard Gardner and Robert ")
				print ("Sternberg.[183] Still, dynamic assessment has not been implemented in education on a large scale as is up to now, by ")
				print ("admission of one of its notable proponents, ''in search of its identity''.[184]")
				print ("\n\n\n\n\n\n\n")
				more1 = input("Classification")
				print ("Main article: IQ classification")
				print (" ")
				print ("IQ classification is the practice used by IQ test publishers for designating IQ score ranges into various categories with ")
				print ("labels such as ''superior'' or ''average.''[185] IQ classification was preceded historically by attempts to classify human ")
				print ("beings by general ability based on other forms of behavioral observation. Those other forms of behavioral observation are ")
				print ("still important for validating classifications based on IQ tests.")
				print ("\n\n\n\n\n\n\n")
				more1 = input("High IQ societies")
				print ("Main article: High IQ society")
				print (" ")
				print ("There are social organizations, some international, which limit membership to people who have scores as high as or ")
				print ("higher than the 98th percentile (2 standard deviations above the mean) on some IQ test or equivalent. Mensa International") 
				print ("is perhaps the best known of these. The largest 99.9th percentile (3 standard deviations above the mean) society is the")
				print ("Triple Nine Society. ")
				print ("\n\n\n\n\n\n\n")
				noMore = input("Press [ENTER] key to quit")