WikIDSelect = int(20006)
if WikIDSelect == 20006:
	if WikIDSelect == 20006:
		if WikIDSelect == 20006:
			if WikIDSelect == 20006:
				print ("In computer architecture, 16-bit integers, memory addresses, or other data units are those that are 16 bits (2 octets) wide.") 
				print ("Also, 16-bit CPU and ALU architectures are those that are based on registers, address buses, or data buses of that size. ")
				print ("16-bit microcomputers are computers in which 16-bit microprocessors were the norm.")
				print (" ")
				print ("A 16-bit register can store 216 different values. The signed range of integer values that can be stored in 16 bits is ")
				print ("−32,768 (−1 × 215) through 32,767 (215 − 1); the unsigned range is 0 through 65,535 (216 − 1). Since 216 is 65,536, a ")
				print ("processor with 16-bit memory addresses can directly access 64 KB (65,536 bytes) of byte-addressable memory. If a system ")
				print ("uses segmentation with 16-bit segment offsets, more can be accessed.")
				more1 = input("Contents")
				print (" ")
				print ("1 16-bit architecture")
				print ("1.1 16/32-bit Motorola 68000 and Intel 386SX")
				print ("2 Intel 16-bit memory models")
				print ("3 16-bit application")
				print ("4 List of 16-bit CPUs")
				print ("5 See also")
				print ("6 References")
				print (" ")
				more1 = input("16-bit architecture")
				print (" ")
				print ("The MIT Whirlwind (c. 1951)[1][2] was quite possibly the first-ever 16-bit computer. Other early (c. 1965–70) 16-bit computers ")
				print ("include the IBM 1130,[3] the HP 2100,[4] the Data General Nova,[5] and the DEC PDP-11.[6] Early (c. 1973–75) multi-chip 16-bit ")
				print ("microprocessors include the National Semiconductor IMP-16 and the Western Digital MCP-1600. Early (c. 1975–76) single-chip ")
				print ("16-bit microprocessors include the Panafacom MN1610,[7][8] National Semiconductor PACE, the HP BPC, and the TI TMS9900. ")
				print ("Other notable 16-bit processors include the Intel 8086, the Intel 80286, the WDC 65C816, and the Zilog Z8000. The Intel ")
				print ("8088 was binary compatible with the Intel 8086, and was 16-bit in that its registers were 16 bits wide, and arithmetic ")
				print ("instructions could operate on 16-bit quantities, even though its external bus was 8 bits wide.")
				print (" ")
				print ("A 16-bit integer can store 216 (or 65,536) distinct values. In an unsigned representation, these values are the integers ")
				print ("between 0 and 65,535; using two's complement, possible values range from −32,768 to 32,767. Hence, a processor with ")
				print ("16-bit memory addresses can directly access 64 KB of byte-addressable memory.")
				print (" ")
				print ("16-bit processors have been almost entirely supplanted in the personal computer industry, and are used less than 32-bit ")
				print ("(or 8-bit) CPUs in embedded applications.")
				print ("16/32-bit Motorola 68000 and Intel 386SX")
				print (" ")
				print ("The Motorola 68000 is sometimes called 16-bit because its internal and external data buses were 16 bits wide; however, it ")
				print ("could be considered a 32-bit processor in that the general purpose registers were 32 bits wide and most arithmetic ")
				print ("instructions supported 32-bit arithmetic. The 68000 was a microcoded processor with three internal 16-bit ALUs. Only 24") 
				print ("bits of the program counter (PC) were available on original DIP packages, with up to 16 megabytes of addressable RAM. ")
				print ("68000 software is 32-bit in nature and forward-compatible with other 32-bit processors in the same family.[9] The 68008 ")
				print ("was a version of the 68000 with 8-bit external data path and 1 megabyte addressing for the 48-pin DIP version and 4 ")
				print ("megabyte for the 52-pin PLCC version. Several Apple Inc. Macintosh models; e.g., LC series, used 32-bit 68020 and ")
				print ("68030 processors on a 16-bit data bus to save cost.")
				print (" ")
				print ("Similar analysis applies to Intel's 80286 CPU replacement called the 386SX which is a 32-bit processor with 32-bit ALU and ")
				print ("internal 32-bit data paths with a 16-bit external bus and 24-bit addressing of the processor it replaced.")
				more1 = input("Intel 16-bit memory models")
				print ("Main article: Intel Memory Model")
				print (" ")
				print ("This article may be confusing or unclear to readers. Please help us clarify the article. There might be a discussion about ")
				print ("this on the talk page. (August 2017) (Learn how and when to remove this template message)")
				print (" ")
				print ("Just as there are multiple data models for 64-bit architectures, the 16-bit Intel architecture allows for different memory ")
				print ("models—ways to access a particular memory location. The reason for using a specific memory model is the size of the ")
				print ("assembler instructions or required storage for pointers. Compilers of the 16-bit era generally had the following type-width") 
				print ("characteristic:")
				print ("16-bit data model Data model 	short 	int 	long 	Pointers")
				print ("IP16L32 (near) 	16 	16 	32 	16")
				print ("I16LP32 (far) 	16 	16 	32 	32")
				print (" ")
				print ("Tiny")
				print ("Code and data will be in the same segment (especially, the registers CS, DS, ES, SS will point to the same segment); near ")
				print ("(16-bit) pointers are always used. Code, data and stack together cannot exceed 64 KB.")
				print ("Small")
				print ("Code and data will be in different segments, and near pointers are always used. There will be 64 KB of space for code and ")
				print ("64 KB for data/stack.")
				print ("Medium")
				print ("Code pointers will use far pointers (16:16 bit), enabling access to 1 MB. Data pointers remain to be of the near type.")
				print ("Compact")
				print ("Data pointers will use far and code will use near pointers.")
				print ("Large/huge")
				print ("Code and data pointers will be far.[10]")
				print (" ")
				more1 = input("16-bit application")
				print (" ")
				print ("In the context of IBM PC compatible and Wintel platforms, a 16-bit application is any software written for MS-DOS, OS/2 1.x ")
				print ("or early versions of Microsoft Windows which originally ran on the 16-bit Intel 8088 and Intel 80286 microprocessors. ")
				print ("Such applications used a 20-bit or 24-bit segment or selector-offset address representation to extend the range of addressable ")
				print ("memory locations beyond what was possible using only 16-bit addresses. Programs containing more than 216 bytes (65,536 bytes)")
				print ("of instructions and data therefore required special instructions to switch between their 64-kilobyte segments, increasing the ")
				print ("complexity of programming 16-bit applications.")
				more1 = input("List of 16-bit CPUs")
				print ("This list is incomplete; you can help by expanding it.")
				print (" ")
				print ("Angstrem")
				print ("1801 series CPU")
				print ("Data General")
				print ("Nova")
				print ("Eclipse")
				print ("Digital Equipment Corporation")
				print ("PDP-11 (for LSI-11, see Western Digital, below)")
				print ("DEC J-11")
				print ("DEC T-11")
				print ("EnSilica")
				print ("eSi-1600")
				print ("Ferranti")
				print ("Ferranti F100-L")
				print ("Ferranti F200-L")
				print ("Freescale")
				print ("Freescale 68HC12")
				print ("Freescale 68HC16")
				print ("General Instrument")
				print ("CP1600")
				print ("Hewlett-Packard")
				print ("HP 21xx/2000/1000/98xx/BPC")
				print ("HP 3000")
				print ("Honeywell")
				print ("Honeywell Level 6/DPS 6")
				print ("IBM")
				print ("1130/1800")
				print ("System/7")
				print ("Series/1")
				print ("System/36")
				print ("Infineon")
				print ("XE166 family")
				print ("C166 family")
				print ("C167 family")
				print ("XC2000")
				print ("Intel")
				print ("Intel 8086/Intel 8088")
				print ("Intel 80186/Intel 80188")
				print ("Intel 80286")
				print ("Intel MCS-96")
				print ("Lockheed")
				print ("MAC-16")
				print ("Motorola")
				print ("Motorola 68000 (32-bit registers, 16-bit bus)")
				print ("Motorola 68010 (32-bit registers, 16-bit bus)")
				print ("National Semiconductor")
				print ("IMP-16")
				print ("ACE/INS8900")
				print ("NEC")
				print ("V20/V30")
				print ("Renesas")
				print ("Renesas M16C (16-bit registers, 24-bit address space)")
				print ("Ricoh")
				print ("Ricoh 5A22 (WDC 65816 clone used in SNES)")
				print ("Texas Instruments")
				print ("Texas Instruments TMS9900")
				print ("TI MSP430")
				print ("Western Design Center")
				print ("WDC 65816/65802")
				print ("Western Digital")
				print ("MCP-1600 (used in the DEC LSI-11)")
				print ("Xerox")
				print ("Alto")
				print ("Zilog")
				print ("Zilog Z8000")
				print (" ")
				print (" ")
				print (" ")
				noMore = input("Press [ENTER] key to exit")