print (" ")
print (" ")
print (" __  __  __  __  __   ____  ____  ____  __    ____  ___    _____  ____      __      _  _  __  __  __  __  ____  ____  ____ ")
print ("(  \\/  )(  )(  )(  ) (_  _)(_  _)(  _ \\(  )  ( ___)/ __)  (  _  )( ___)    /__\\    ( \\( )(  )(  )(  \\/  )(  _ \\( ___)(  _ \\ ")
print (" )    (  )(__)(  )(__  )(   _)(_  )___/ )(__  )__) \\__ \\   )(_)(  )__)    /(__)\\    )  (  )(__)(  )    (  ) _ < )__)  )   / '') ")
print ("(_/\\/\\_)(______)(____)(__) (____)(__)  (____)(____)(___/  (_____)(__)    (__)(__)  (_)\\_)(______)(_/\\/\\_)(____/(____)(_)\\_) ")
print ("  ___    __    __    ___  __  __  __      __   ____  _____  ____        ")                                                    
print (" / __)  /__\\  (  )  / __)(  )(  )(  )    /__\\ (_  _)(  _  )(  _ \\       ")                                                    
print ("( (__  /(__)\\  )(__( (__  )(__)(  )(__  /(__)\\  )(   )(_)(  )   /           ")                                                
print (" \\___)(__)(__)(____)\\___)(______)(____)(__)(__)(__) (_____)(_)\\_)             ")                                              
print (" ")
print (" ")
startInputEnter = input("Press [ENTER] key to start")
print ("This is the NO DECIMAL version. Do NOT enter ANY decimals!")
multiask1 = int(input("Enter a number to find its multiples: "))
multiask1original = int(multiask1)
multiask2 = int(input("Enter a stopping number: "))
multiask3 = int(multiask1)
startmult = int(multiask1 - (multiask3 * 2))
stopMultiple = int(multiask2 - multiask1 + 1)
print ("\n\n\n")
print (multiask1)
if (multiask1 > multiask2):
	print ("\n\nSyntax error: The stopping number is lower than the starting number")
if not (multiask1 > multiask2):
	while not (multiask1 > stopMultiple):
		multiask1 = multiask1 + multiask3
		print (multiask1)
print ("\n\n\nThose are the multiples of " + str(multiask1original))
noMore = input("Press [ENTER] key to quit")