		if calcIDSes == 13:
					print ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
					print ("Subtract")
					minus1 = int(input("Enter first number to subtract: "))
					minus2 = int(input("\nEnter second number to subtract: "))
					minus3 = int(input("\nEnter third number to subtract (if you only want to use 2 numbers, type 0): "))
					minus4 = int(input("\nEnter fourth number to subtract (if you only want to use 2 numbers, type 0): "))
					minus5 = int(input("\nEnter fifth number to subtract (if you only want to use 2 numbers, type 0): "))
					curanswer = (minus1 - minus2 - minus3 - minus4 - minus5)
					print ("\n\nThe answer is: " + str(curanswer))
					bloat1 = input("| FAIL! SETUP RESTARTING (we can't fix the bug right now, we are porting features in. Stabilizing later, my bad)")