print (" ")
print (" ")
print (" ____  ____  __  __  ____  ____  ____    __   ____  __  __  ____  ____ ")
print ("(_  _)( ___)(  \\/  )(  _ \\( ___)(  _ \\  /__\\ (_  _)(  )(  )(  _ \\( ___)")
print ("  )(   )__)  )    (  )___/ )__)  )   / /(__)\\  )(   )(__)(  )   / )__) ")
print (" (__) (____)(_/\\/\\_)(__)  (____)(_)\\_)(__)(__)(__) (______)(_)\\_)(____)")
print ("  ___    __    __    ___  __  __  __      __   ____  _____  ____       ")
print (" / __)  /__\\  (  )  / __)(  )(  )(  )    /__\\ (_  _)(  _  )(  _ \\      ")
print ("( (__  /(__)\\  )(__( (__  )(__)(  )(__  /(__)\\  )(   )(_)(  )   /     ") 
print (" \\___)(__)(__)(____)\\___)(______)(____)(__)(__)(__) (_____)(_)\\_)  ")    
print (" ")
enterToEnter = input("Press [ENTER] key to start")
calcIDSes = int(17)
if calcIDSes == 17:
	if calcIDSes == 17:
		if calcIDSes == 17:
		'''
					print ("\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n")
					print ("Temperature")
					fahOrCel = int(input("What do you want to start with? Fahrenheit (1) Celsius (2) "))
					if fahOrCel == 1:
						fahent = float(input("Enter the temperature in Fahrenheit: "))
					if fahOrCel == 2:
						celent = float(input("Enter the temperature in Celsius: "))
						fahent = (celent * 1.8 + 32)
						print ("The temperature in Fahrenheit is " + str(fahent))
					bloat1 = input("| FAIL! SETUP RESTARTING (we can't fix the bug right now, we are porting features in. Stabilizing later, my bad)")
		'''
			print ("Temperature calculator")
			more1 = input("New sorting options are available! ")
			print ("| A-Z (0) | Z-A (1) | Coldest to Hottest (2) | Hottest to Coldest (3) |")
			sortOpt1 = int(input("Select a sorting option: "))
			if sortOpt1 == 0:
				print ("Select a temperature type:\n ")
				print ("Celsius")
				print ("Fahrenheit")
				print ("Kelvin")
				print ("Rankine")
			if sortOpt1 == 1:
				print ("Select a temperature type:\n ")
				print ("Rankine")
				print ("Kelvin")
				print ("Fahrenheit")
				print ("Celsius")
			if sortOpt1 == 2:
				print ("Select a temperature type:\n ")
				print ("Rankine")
				print ("Kelvin")
				print ("Celsius")
				print ("Fahrenheit")
			if sortOpt1 == 3:
				print ("Select a temperature type:\n ")
				print ("Fahrenheit")
				print ("Celsius")
				print ("Kelvin")
				print ("Rankine")
			unit1 = str(input("Enter the name of the texture here: "))
			if (unit1 == "Fahrenheit"):
				fahrenheit1 = float(input("Enter the temperature in fahrenheit: "))
				print ("Select an exponent")
				print ("Addition (+)         | 0 |")
				print ("Subtraction (-)      | 1 |")
				print ("Multiplication (*)   | 2 |")
				print ("Division (/)         | 3 |")
				print ("Modular division (%) | 4 |")
				unit2 = int(input("Enter an exponent ID to continue: "))
				if unit2 == 0:
					fahrenheit2 = float(input("Enter a number to add: "))
					curanswer == (fahrenheit1 + fahrenheit2)
					print ("The answer is: " + str(curanswer) + " Degrees Fahrenheit"))
					celsiusCalc = float(curanswer - 32 * (5 / 9))
					kelvinCalc = float(curasnwer - 273 * (5 / 9))
					rankineCalc = float(curanswer - 492 * (5 / 9))
					print ("This is also equal to:" ")
					print ("Celsius: " + str(celsiusCalc))
					print ("Kelvin: " + str(kelvinCalc))
					print ("Rankine: " + str(rankineCalc))
noMore = input("Press [ENTER] key to quit")