	if uCMainConsole == 8:
		print ("UCalc Accessories Manager")
		print ("\n")
		print ("Screensavers   [ID: 1]")
		print ("Chatrooms      [ID: 2]")
		selectACessory = str(input("Enter an ID to begin"))
		if selectACessory == ("1"):
			print ("UCalc screensavers")
			print ("\n")
			print ("Number blocks      [ID: 1]")
			print ("Rocket shuttle     [ID: 2]")
			print ("Matrix             [ID: 3]")
			print ("DNA farm           [ID: 4]")
			print ("Binary bay         [ID: 5]")
			screensaverSelect = str(input("Enter an ID to begin"))