WikIDSelect = int(20012)
if WikIDSelect == 20012:
	if WikIDSelect == 20012:
		if WikIDSelect == 20012:
			if WikIDSelect == 20012:
				print ("In computer architecture, 36-bit integers, memory addresses, or other data units are those that are 36 bits (six six-bit ")
				print ("characters) wide. Also, 36-bit CPU and ALU architectures are those that are based on registers, address buses, or data buses") 
				print ("of that size.")
				print (" ")
				print ("Prior to the introduction of computers, the state of the art in precision scientific and engineering calculation was the ")
				print ("ten-digit, electrically powered, mechanical calculator, such as those manufactured by Friden, Marchant and Monroe. These ")
				print ("calculators had a column of keys for each digit, and operators were trained to use all their fingers when entering numbers,") 
				print ("so while some specialized calculators had more columns, ten was a practical limit. Computers, as the new competitor, had to ")
				print ("match that accuracy. Decimal computers sold in that era, such as the IBM 650 and the IBM 7070, had a word length of ten ")
				print ("digits, as did ENIAC, one of the earliest computers.")
				print (" ")
				print ("Early binary computers aimed at the same market therefore often used a 36-bit word length. This was long enough to represent ")
				print ("positive and negative integers to an accuracy of ten decimal digits (35 bits would have been the minimum). It also allowed ")
				print ("the storage of six alphanumeric characters encoded in a six-bit character code. Computers with 36-bit words included the ")
				print ("MIT Lincoln Laboratory TX-2, the IBM 701/704/709/7090/7094, the UNIVAC 1103/1103A/1105 and 1100/2200 series, the General") 
				print ("Electric GE-600/Honeywell 6000, the Digital Equipment Corporation PDP-6/PDP-10 (as used in the DECsystem-10/DECSYSTEM-20),") 
				print ("and the Symbolics 3600 series.")
				print (" ")
				print ("Smaller machines like the PDP-1/PDP-9/PDP-15 used 18-bit words, so a double word was 36 bits.")
				print (" ")
				print ("These computers had addresses 15 to 18 bits in length. The addresses referred to 36-bit words, so the computers were ")
				print ("limited to addressing between 32768 and 262144 words (196608 to 1572864 six-bit characters). The older 36-bit computers") 
				print ("were limited to a similar amount of physical memory as well. Architectures that survived evolved over time to support ")
				print ("larger virtual address spaces using memory segmentation or other mechanisms.")
				print (" ")
				print ("The common character packings included:")
				print (" ")
				print ("six 5.32-bit DEC Radix-50 characters, plus four spare bits")
				print ("six 6-bit Fieldata or IBM BCD characters (ubiquitous in early usage)")
				print ("six 6-bit ASCII characters, supporting the upper-case unaccented letters, digits, space, and most ASCII punctuation ")
				print ("characters. It was used on the PDP-6 and PDP-10 under the name sixbit.")
				print ("five 7-bit characters and 1 unused bit (the usual PDP-6/10 convention, called five-seven ASCII)[1][2]")
				print ("four 8-bit characters (7-bit ASCII plus 1 spare bit, or 8-bit EBCDIC), plus four spare bits")
				print ("four 9-bit characters[1][2] (the Multics convention).")
				print (" ")
				print ("Characters were extracted from words either using machine code shift and mask operations or with special-purpose hardware ")
				print ("supporting 6-bit, 9-bit, or variable-length characters. The Univac 1100/2200 used the partial word designator of the ")
				print ("instruction, the ''J'' field, to access characters. The GE-600 used special indirect words to access 6- and 9-bit characters.") 
				print ("the PDP-6/10 had special instructions to access arbitrary-length byte fields.")
				print (" ")
				print ("The standard C programming language requires that the size of the char data type be at least 8 bits,[3] and that all data ")
				print ("types other than bitfields have a size that is a multiple of the character size,[4] so standard C implementations on") 
				print ("36-bit machines would typically use 9-bit chars, although 12-bit, 18-bit, or 36-bit would also satisfy the requirements of the") 
				print ("standard.[5]")
				print (" ")
				print ("By the time IBM introduced System/360, scientific calculations had shifted to floating point and mechanical calculators were ")
				print ("no longer a competitor. The 360s also included instructions for variable length decimal arithmetic for commercial applications,") 
				print ("so the practice of using word lengths that were a power of two quickly became commonplace, though some 36-bit computer ")
				print ("systems are still sold as of 2014, e.g., the Unisys ClearPath Dorado series, which is the continuation of the UNIVAC ")
				print ("1100/2200 series of mainframe computers.")
				print (" ")
				print ("CompuServe was launched using 36-bit PDP-10 computers in the late 1960s. It continued using PDP-10 and DECSYSTEM-10-compatible ")
				print ("hardware and retired the service in the late 2000s.")
				more1 = input("Other uses in electronics")
				print (" ")
				print ("The LatticeECP3 FPGAs from Lattice Semiconductor include multiplier slices that can be configured to support the ")
				print ("multiplication of two 36-bit numbers.[6] The DSP block in Altera Stratix FPGAs can do 36-bit additions and ")
				print ("multiplications.[7] ")
				print (" ")
				noMore = input("Press [ENTER] key to exit")