			if WikIDSelect == 20002:
				print ("Compatibility")
				print ("\nMicrosoft Windows")
				print ("Windows 2000")
				print ("Windows XP")
				print ("Windows Vista")
				print ("Windows 7")
				print ("Windows 8")
				print ("Windows 8.1")
				print ("Windows 10")
				print ("Windows Server 2003")
				print ("Windows Server 2008")
				print ("Windows Server 2012")
				print ("Windows Server 2016")
				print ("Windows Server 2019")
				print ("\nMacOS")
				print ("MacOS X 10.2")
				print ("MacOS X 10.3")
				print ("MacOS X 10.4")
				print ("MacOS X 10.5")
				print ("MacOS X 10.6")
				print ("MacOS X 10.7")
				print ("OS X 10.8")
				print ("OS X 10.9")
				print ("OS X 10.10")
				print ("OS X 10.11")
				print ("MacOS 10.12")
				print ("MacOS 10.13")
				print ("MacOS 10.14")
				print ("\nLinux")
				print ("\nUbuntu")
				print ("Ubuntu 4.04 and up")
				print ("Lubuntu 6.10 and up")
				print ("Xubuntu 6.10 and up")
				print ("\nFedora")
				print ("Fedora Core 3 and up")
				print ("\nMint")
				print ("Linux Mint 4 and up")
				print ("\nArch")
				print ("Unknown")
				print ("\nGentoo")
				print ("Unknown")