print (" ")
print (" ")
print ("                                                                                                                                              ")
print ("                                                                                                                                              ")
print ("                                                      ____                         ___                   ___                                  ")
print ("      ,---,                                         ,'  , `.                     ,--.'|_               ,--.'|_    ,--,                        ")
print ("    ,---.'|   ,---.                     ,--,     ,-+-,.' _ |             ,---,   |  | :,'              |  | :,' ,--.'|    ,---.        ,---,  ")
print ("    |   | :  '   ,'\\                  ,'_ /|  ,-+-. ;   , ||         ,-+-. /  |  :  : ' :              :  : ' : |  |,    '   ,'\\   ,-+-. /  |") 
print ("    |   | | /   /   |   ,---.    .--. |  | : ,--.'|'   |  || ,---.  ,--.'|'   |.;__,'  /    ,--.--.  .;__,'  /  `--'_   /   /   | ,--.'|'   | ")
print ("  ,--.__| |.   ; ,. :  /     \\ ,'_ /| :  . ||   |  ,', |  |,/     \\|   |  ,'' ||  |   |    /       \\ |  |   |   ,' ,'| .   ; ,. :|   |  ,''' |") 
print (" /   ,'   |'   | |: : /    / ' |  ' | |  . .|   | /  | |--'/    /  |   | /  | |:__,'| :   .--.  .-. |:__,'| :   '  | | '   | |: :|   | /  | | ")
print (".   '  /  |'   | .; :.    ' /  |  | ' |  | ||   : |  | ,  .    ' / |   | |  | |  '  : |__  \\__\\/: . .  '  : |__ |  | : '   | .; :|   | |  | | ")
print ("'   ; |:  ||   :    |'   ; :__ :  | : ;  ; ||   : |  |/   '   ;   /|   | |  |/   |  | '.'| ,' .--.; |  |  | '.'|'  : |_|   :    ||   | |  |/  ")
print ("|   | '/  ' \\   \\  / '   | '.'|'  :  `--'   \\   | |`-'    '   |  / |   | |--'    ;  :    ;/  /  ,.  |  ;  :    ;|  | '.'\\   \\  / |   | |--' ")  
print ("|   :    :|  `----'  |   :    ::  ,      .-./   ;/        |   :    |   |/        |  ,   /;  :   .'   \\ |  ,   / ;  :    ;`----'  |   |/       ")
print (" \\   \\  /             \\   \\  /  `--`----'   '---'          \\   \\  /'---'          ---`-' |  ,     .-./  ---`-'  |  ,   /         '---'   ")     
print ("  `----'               `----'                               `----'                        `--`---'               ---`-'          ")             
print (" ")                                                                                                                                              
print (" ")
enterToEnter = input("Press [ENTER] key to start")
uCMainConsole = int(3)
if uCMainConsole == 3:
	if uCMainConsole == 3:
		konloop = int(0)
		while konloop == 0:
			print ("The ultimate math encyclopedia")
			print ("Volume 1")
			print ("\nUCalc exclusives")
			print ("Update log [ID: 10000]")
			print ("Version info [ID: 10001]")
			print ("Developer Data Folder ReadMe [ID: 10002]")
			print ("Source info [ID: 10003]")
			print ("Development goals [ID: 10004]")
			print ("Manufacturing guide [ID: 10005]")
			print ("Terms of use [ID: 10006]")
			print ("Credits [ID: 10007]")
			print ("Math puns [ID: 10008]")
			print ("Math in gaming [ID: 10009]")
			print ("Bundle info [ID: 10010]")
			print ("Contact us [ID: 10011]")
			print ("Feedback center [ID: 10012]")
			print ("Comments [ID: 10013]")
			print ("Common math mistakes - fractions edition [ID: 10014]")
			more1 = input("Press [ENTER] key for more")
			print ("\nProcessor setup")
			print ("4 bit-128 bit [ID: 20000]")
			print ("Weak calculators [ID: 20001]")
			print ("System compatibility [ID: 20002]")
			print ("4 bit computing [ID: 20003]")
			print ("8 bit computing [ID: 20004]")
			print ("12 bit computing [ID: 20005]")
			print ("16 bit computing [ID: 20006]")
			print ("18 bit computing [ID: 20007]")
			print ("24 bit computing [ID: 20008]")
			print ("26 bit computing [ID: 20009]")
			print ("31 bit computing  [ID: 20010]")
			print ("32 bit computing  [ID: 20011]")
			print ("36 bit computing  [ID: 20012]")
			print ("48 bit computing  [ID: 20013]")
			print ("60 bit computing  [ID: 20014]")
			print ("64 bit computing  [ID: 20015]")
			print ("128 bit computing  [ID: 20016]")
			print ("256 bit computing  [ID: 20017]")
			print ("512 bit computing  [ID: 20018]")
			print ("Variable names and their purpose for UCalc [ID: 20019]") 
			more1 = input("Press [ENTER] key for more")
			print ("\nGetting started with math [ID: 30000]")
			print ("Counting [ID: 30001]")
			print ("Names of numbers [ID: 30002]")
			print ("Superstitious numbers [ID: 30003]")
			print ("Slang numbers [ID: 30004]")
			print ("Roman numerals [ID: 30005]")
			print ("Multiples table [ID: 30006]")
			print ("IQ Definition [ID: 30007]")
			print ("Bit slicing definiton [ID: 30008]")
			more1 = input("Press [ENTER] key for more")
			print ("\nAlgebra")
			more1 = input("Press [ENTER] key for more")
			print ("\nCalculus")
			more1 = input("Press [ENTER] key for more")
			WikIDSelect = int(input("Enter an ID to start: "))