WikIDSelect = int(20004)
if WikIDSelect == 20004:
	if WikIDSelect == 20004:
		if WikIDSelect == 20004:
			if WikIDSelect == 20004:
				print ("In computer architecture, 8-bit integers, memory addresses, or other data units are those that are 8 bits (1 octet) wide. Also, ")
				print ("8-bit CPU and ALU architectures are those that are based on registers, address buses, or data buses of that size. 8-bit is also ")
				print ("a generation of microcomputers in which 8-bit microprocessors were the norm.")
				print (" ")
				print ("The IBM System/360 introduced byte-addressable memory with 8-bit bytes, as opposed to bit-addressable or decimal ")
				print ("digit-addressable or word-addressable memory, although its general purpose registers were 32 bits wide, and addresses ")
				print ("were contained in the lower 24 bits of those addresses. Different models of System/360 had different internal data path ")
				print ("widths; the IBM System/360 Model 30 (1965) implemented the 32-bit System/360 architecture, but had an 8 bit native path width, and")
				print ("performed 32-bit arithmetic 8 bits at a time.[1]")
				print (" ")
				print ("The first widely adopted 8-bit microprocessor was the Intel 8080, being used in many hobbyist computers of the late 1970s ")
				print ("and early 1980s, often running the CP/M operating system; it had 8-bit data words and 16-bit addresses. The Zilog Z80 ")
				print ("(compatible with the 8080) and the Motorola 6800 were also used in similar computers. The Z80 and the MOS Technology 6502 8-bit") 
				print ("CPUs were widely used in home computers and second- and third-generation game consoles of the 1970s and 1980s. Many 8-bit ")
				print ("CPUs or microcontrollers are the basis of today's ubiquitous embedded systems.")
				more1 = input("Details")
				print (" ")
				print ("There are 28 (256) different possible values for 8 bits. When unsigned, it has possible values ranging from 0 to 255, when ")
				print ("signed, it has -128 to 127.")
				print (" ")
				print ("Eight-bit CPUs use an 8-bit data bus and can therefore access 8 bits of data in a single machine instruction. The address bus ")
				print ("is typically a double octet wide (i.e. 16-bit), due to practical and economical considerations. This implies a direct address ")
				print ("space of only 64 kB on most 8-bit processors.")
				more1 = input("Notable 8-bit CPUs")
				print (" ")
				print ("The first commercial 8-bit processor was the Intel 8008 (1972) which was originally intended for the Datapoint 2200 intelligent ")
				print ("terminal. Most competitors to Intel started off with such character oriented 8-bit microprocessors. Modernized variants of ")
				print ("these 8-bit machines are still one of the most common types of processor in embedded systems.")
				print (" ")
				print ("Another notable 8-bit CPU is the MOS Technology 6502; it, and variants of it, were used in a number of personal computers such")
				print ("as the Apple I and Apple II, the Atari 8-bit family, the BBC Micro, and the Commodore PET and Commodore VIC-20, and in a ")
				print ("number of video game consoles such as the Atari 2600 and the Nintendo Entertainment System.")
				print ("Early or popular 8-bit processors (incomplete) Manufacturer 	Processor 	Year 	Comment")
				print ("Intel 	8008 	1972 	Datapoint 2200 compatible")
				print ("Signetics 	2650 	1973 	")
				print ("Intel 	8080 	1974 	8008 source compatible")
				print ("Motorola 	6800 	1974 ")	
				print ("Fairchild 	F8 	1975 	")
				print ("MOS 	6502 	1975 	Similar to 6800, but incompatible")
				print ("Microchip 	PIC 	1975 	Harvard architecture microcontroller")
				print ("Electronic Arrays 	EA9002 	1976 	8-bit data, 12-bit addressing")
				print ("RCA 	1802 	1976 	")
				print ("Zilog 	Z80 	1976 	8080 binary compatible")
				print ("Intel 	8085 	1977 	8080 binary compatible")
				print ("Motorola 	6809 	1978 	6800 source compatible")
				print ("Zilog 	Z8 	1978 	Harvard architecture microcontroller")
				print ("Intel 	8051 	1980 	Harvard architecture microcontroller")
				print ("MOS 	6510 	1982 	Enhanced 6502 custom-made for use in the Commodore 64")
				print ("Ricoh 	2A03 	1982 	6502 clone minus BCD instructions for the Nintendo Entertainment System")
				print ("Zilog 	Z180 	1985 	Z80 binary compatible")
				print ("Motorola 	68HC11 	1985 ")	
				print ("Atmel 	AVR 	1996 	")
				print ("Zilog 	EZ80 	1999 	Z80 binary compatible")
				print ("Infineon 	XC800 	2005 ")	
				print ("Freescale 	68HC08 		")
				print ("Hudson 	HuC6280 		")
				print ("Motorola 	6803 ")		
				print ("NEC 	78K0[2]") 		
				print (" ")
				noMore = input("Press [ENTER] key to exit")