print (" ")
print (" ")
print (" ____  ____  __  __  ____  ____  ____    __   ____  __  __  ____  ____ ")
print ("(_  _)( ___)(  \\/  )(  _ \\( ___)(  _ \\  /__\\ (_  _)(  )(  )(  _ \\( ___)")
print ("  )(   )__)  )    (  )___/ )__)  )   / /(__)\\  )(   )(__)(  )   / )__) ")
print (" (__) (____)(_/\\/\\_)(__)  (____)(_)\\_)(__)(__)(__) (______)(_)\\_)(____)")
print ("  ___    __    __    ___  __  __  __      __   ____  _____  ____       ")
print (" / __)  /__\\  (  )  / __)(  )(  )(  )    /__\\ (_  _)(  _  )(  _ \\      ")
print ("( (__  /(__)\\  )(__( (__  )(__)(  )(__  /(__)\\  )(   )(_)(  )   /     ") 
print (" \\___)(__)(__)(____)\\___)(______)(____)(__)(__)(__) (_____)(_)\\_)  ")    
print (" ")
enterToEnter = input("Press [ENTER] key to start")
calcIDSes = int(17)
if calcIDSes == 17:
	if calcIDSes == 17:
		if calcIDSes == 17:
			print ("Temperature calculator")
			more1 = input("New sorting options are available! ")
			print ("| A-Z (0) | Z-A (1) | Coldest to Hottest (2) | Hottest to Coldest (3) |")
			sortOpt1 = int(input("Select a sorting option: "))
			if sortOpt1 == 0:
				print ("Sorting by A-Z")
				print ("Select a temperature type:\n ")
				print ("Celsius")
				print ("Fahrenheit")
				print ("Kelvin")
				print ("Rankine")
			if sortOpt1 == 1:
				print ("Sorting by Z-A")
				print ("Select a temperature type:\n ")
				print ("Rankine")
				print ("Kelvin")
				print ("Fahrenheit")
				print ("Celsius")
			if sortOpt1 == 2:
				print ("Sorting by coldest to hottest")
				print ("Select a temperature type:\n ")
				print ("Rankine")
				print ("Kelvin")
				print ("Celsius")
				print ("Fahrenheit")
			if sortOpt1 == 3:
				print ("Sorting from hottest to coldest")
				print ("Select a temperature type:\n ")
				print ("Fahrenheit")
				print ("Celsius")
				print ("Kelvin")
				print ("Rankine")
			unit1 = str(input("Enter the name of the texture here: "))
			if (unit1 == "Fahrenheit" or unit1 == "FAHRENHEIT" 	or unit1 == "fahrenheit"):
				fahrenheit1 = float(input("Enter the temperature in fahrenheit: "))
				print ("Select an exponent")
				print ("Addition (+)         | 0 |")
				print ("Subtraction (-)      | 1 |")
				print ("Multiplication (*)   | 2 |")
				print ("Division (/)         | 3 |")
				print ("Modular division (%) | 4 |")
				unit2 = int(input("Enter an exponent ID to continue: "))
				if unit2 == 0:
					fahrenheit2 = float(input("Enter a number to add: "))
					curanswer = float(fahrenheit1 + fahrenheit2)
					celsiusCalc = float((curanswer - 32) * 5/9)
					kelvinCalc = float(curanswer + 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Fahrenheit")
					print ("This is also equal to:")
					print ("Celsius: " + str(celsiusCalc))
					print ("Kelvin: " + str(kelvinCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 1:
					fahrenheit2 = float(input("Enter a number to subtract by: "))
					curanswer = float(fahrenheit1 - fahrenheit2)
					celsiusCalc = float((curanswer - 32) * 5/9)
					kelvinCalc = float(curanswer + 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Fahrenheit")
					print ("This is also equal to:")
					print ("Celsius: " + str(celsiusCalc))
					print ("Kelvin: " + str(kelvinCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 2:
					fahrenheit2 = float(input("Enter a number to multiply by: "))
					curanswer = float(fahrenheit1 * fahrenheit2)
					celsiusCalc = float((curanswer - 32) * 5/9)
					kelvinCalc = float(curanswer + 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Fahrenheit")
					print ("This is also equal to:")
					print ("Celsius: " + str(celsiusCalc))
					print ("Kelvin: " + str(kelvinCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 3:
					fahrenheit2 = float(input("Enter a number to divide by: "))
					curanswer = float(fahrenheit1 / fahrenheit2)
					celsiusCalc = float((curanswer - 32) * 5/9)
					kelvinCalc = float(curanswer + 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Fahrenheit")
					print ("This is also equal to:")
					print ("Celsius: " + str(celsiusCalc))
					print ("Kelvin: " + str(kelvinCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 4:
					fahrenheit2 = float(input("Enter a number to mod: "))
					curanswer = float(fahrenheit1 % fahrenheit2)
					celsiusCalc = float((curanswer - 32) * 5/9)
					kelvinCalc = float(curanswer + 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Fahrenheit")
					print ("This is also equal to:")
					print ("Celsius: " + str(celsiusCalc))
					print ("Kelvin: " + str(kelvinCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
			if (unit1 == "Celsius" or unit1 == "CELSIUS" or unit1 == "celsius"):
				celsius1 = float(input("Enter the temperature in celsius: "))
				print ("Select an exponent")
				print ("Addition (+)         | 0 |")
				print ("Subtraction (-)      | 1 |")
				print ("Multiplication (*)   | 2 |")
				print ("Division (/)         | 3 |")
				print ("Modular division (%) | 4 |")
				unit2 = int(input("Enter an exponent ID to continue: "))
				if unit2 == 0:
					celsius2 = float(input("Enter a number to add: "))
					curanswer = float(celsius1 + celsius2)
					fahrenheitCalc = float((curanswer * 9 / 5) + 32)
					kelvinCalc = float(curanswer + 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Celsius")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Kelvin: " + str(kelvinCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 1:
					celsius2 = float(input("Enter a number to subtract by: "))
					curanswer = float(celsius1 - celsius2)
					fahrenheitCalc = float((curanswer * 9 / 5) + 32)
					kelvinCalc = float(curanswer + 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Celsius")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Kelvin: " + str(kelvinCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 2:
					celsius2 = float(input("Enter a number to multiply by: "))
					curanswer = float(celsius1 * celsius2)
					fahrenheitCalc = float((curanswer * 9 / 5) + 32)
					kelvinCalc = float(curanswer + 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Celsius")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Kelvin: " + str(kelvinCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 3:
					celsius2 = float(input("Enter a number to divide by: "))
					curanswer = float(celsius1 / celsius2)
					fahrenheitCalc = float((curanswer * 9 / 5) + 32)
					kelvinCalc = float(curanswer + 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Celsius")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Kelvin: " + str(kelvinCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 4:
					celsius2 = float(input("Enter a number to mod: "))
					curanswer = float(celsius1 % celsius2)
					fahrenheitCalc = float((curanswer * 9 / 5) + 32)
					kelvinCalc = float(curanswer + 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Celsius")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Kelvin: " + str(kelvinCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
			if (unit1 == "Kelvin" or unit1 == "KELVIN" or unit1 == "kelvin"):
				kelvin1 = float(input("Enter the temperature in kelvin: "))
				print ("Select an exponent")
				print ("Addition (+)         | 0 |")
				print ("Subtraction (-)      | 1 |")
				print ("Multiplication (*)   | 2 |")
				print ("Division (/)         | 3 |")
				print ("Modular division (%) | 4 |")
				unit2 = int(input("Enter an exponent ID to continue: "))
				if unit2 == 0:
					kelvin2 = float(input("Enter a number to add: "))
					curanswer = float(kelvin1 + kelvin2)
					fahrenheitCalc = float((curanswer * 9 / 5) + 32)
					celsiusCalc = float(curanswer - 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Kelvin")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Celsius: " + str(celsiusCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 1:
					kelvin2 = float(input("Enter a number to subtract: "))
					curanswer = float(kelvin1 - kelvin2)
					fahrenheitCalc = float((curanswer * 9 / 5) + 32)
					celsiusCalc = float(curanswer - 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Kelvin")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Celsius: " + str(celsiusCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 2:
					kelvin2 = float(input("Enter a number to multiply: "))
					curanswer = float(kelvin1 * kelvin2)
					fahrenheitCalc = float((curanswer * 9 / 5) + 32)
					celsiusCalc = float(curanswer - 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Kelvin")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Celsius: " + str(celsiusCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 3:
					kelvin2 = float(input("Enter a number to divide by: "))
					curanswer = float(kelvin1 / kelvin2)
					fahrenheitCalc = float((curanswer * 9 / 5) + 32)
					celsiusCalc = float(curanswer - 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Kelvin")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Celsius: " + str(celsiusCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 4:
					kelvin2 = float(input("Enter a number to mod: "))
					curanswer = float(kelvin1 % kelvin2)
					fahrenheitCalc = float((curanswer * 9 / 5) + 32)
					celsiusCalc = float(curanswer - 273.15)
					rankineCalc = float(curanswer + 459.67)
					print ("The answer is: " + str(curanswer) + " Degrees Kelvin")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Celsius: " + str(celsiusCalc))
					print ("Rankine: " + str(rankineCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
			if (unit1 == "Rankine" or unit1 == "RANKINE" or unit1 == "rankine"):
				rankine1 = float(input("Enter the temperature in rankine: "))
				print ("Select an exponent")
				print ("Addition (+)         | 0 |")
				print ("Subtraction (-)      | 1 |")
				print ("Multiplication (*)   | 2 |")
				print ("Division (/)         | 3 |")
				print ("Modular division (%) | 4 |")
				unit2 = int(input("Enter an exponent ID to continue: "))
				if unit2 == 0:
					rankine2 = float(input("Enter a number to add: "))
					curanswer = float(rankine1 + rankine2)
					fahrenheitCalc = float(curanswer - 459.67)
					celsiusCalc = float(curanswer - 273.15)
					kelvinCalc = float(curanswer * 5 / 9)
					print ("The answer is: " + str(curanswer) + " Degrees rankine")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Celsius: " + str(celsiusCalc))
					print ("Kelvin: " + str(kelvinCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 1:
					rankine2 = float(input("Enter a number to subtract: "))
					curanswer = float(rankine1 - rankine2)
					fahrenheitCalc = float(curanswer - 459.67)
					celsiusCalc = float(curanswer - 273.15)
					kelvinCalc = float(curanswer * 5 / 9)
					print ("The answer is: " + str(curanswer) + " Degrees rankine")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Celsius: " + str(celsiusCalc))
					print ("Kelvin: " + str(kelvinCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 2:
					rankine2 = float(input("Enter a number to multiply by: "))
					curanswer = float(rankine1 * rankine2)
					fahrenheitCalc = float(curanswer - 459.67)
					celsiusCalc = float(curanswer - 273.15)
					kelvinCalc = float(curanswer * 5 / 9)
					print ("The answer is: " + str(curanswer) + " Degrees rankine")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Celsius: " + str(celsiusCalc))
					print ("Kelvin: " + str(kelvinCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 3:
					rankine2 = float(input("Enter a number to divide by: "))
					curanswer = float(rankine1 / rankine2)
					fahrenheitCalc = float(curanswer - 459.67)
					celsiusCalc = float(curanswer - 273.15)
					kelvinCalc = float(curanswer * 5 / 9)
					print ("The answer is: " + str(curanswer) + " Degrees rankine")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Celsius: " + str(celsiusCalc))
					print ("Kelvin: " + str(kelvinCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
				if unit2 == 4:
					rankine2 = float(input("Enter a number to mod: "))
					curanswer = float(rankine1 % rankine2)
					fahrenheitCalc = float(curanswer - 459.67)
					celsiusCalc = float(curanswer - 273.15)
					kelvinCalc = float(curanswer * 5 / 9)
					print ("The answer is: " + str(curanswer) + " Degrees rankine")
					print ("This is also equal to:")
					print ("Fahrenheit: " + str(fahrenheitCalc))
					print ("Celsius: " + str(celsiusCalc))
					print ("Kelvin: " + str(kelvinCalc))
					more1 = input("\n\n\nPress [ENTER] key to exit ")
noMore = input("Press [ENTER] key to quit")