print (" ")
print ("      ___           ___           ___           ___           ___              ")
print ("     /\\  \\         /\\  \\         /\\  \\         /\\__\\         /\\  \\             ")
print ("    /::\\  \\       /::\\  \\       /::\\  \\       /:/  /         \\:\\  \\            ")
print ("   /:/\\:\\  \\     /:/\\:\\  \\     /:/\\:\\  \\     /:/  /           \\:\\  \\           ")
print ("  /::\\~\\:\\  \\   /::\\~\\:\\__\\   /:/  \\:\\  \\   /:/  /  ___       /::\\  \\          ")
print (" /:/\\:\\ \\:\\__\\ /:/\\:\\ \\:|__| /:/__/ \\:\\__\\ /:/__/  /\\__\\     /:/\\:\\__\\    ")     
print (" \\/__\\:\\/:/  / \\:\\~\\:\\/:/  / \\:\\  \\ /:/  / \\:\\  \\ /:/  /    /:/  \\/__/    ")     
print ("      \\::/  /   \\:\\ \\::/  /   \\:\\  /:/  /   \\:\\  /:/  /    /:/  /             ") 
print ("      /:/  /     \\:\\/:/  /     \\:\\/:/  /     \\:\\/:/  /     \\/__/             ")  
print ("     /:/  /       \\::/__/       \\::/  /       \\::/  /                          ")
print ("     \\/__/         ~~            \\/__/         \\/__/                          ") 
print ("      ___           ___           ___           ___       ___                  ")
print ("     /\\__\\         /\\  \\         /\\  \\         /\\__\\     /\\  \\               ")  
print ("    /:/  /        /::\\  \\       /::\\  \\       /:/  /    /::\\  \\                ")
print ("   /:/  /        /:/\\:\\  \\     /:/\\:\\  \\     /:/  /    /:/\\:\\  \\               ")
print ("  /:/  /  ___   /:/  \\:\\  \\   /::\\~\\:\\  \\   /:/  /    /:/  \\:\\  \\            ")  
print (" /:/__/  /\\__\\ /:/__/ \\:\\__\\ /:/\\:\\ \\:\\__\\ /:/__/    /:/__/ \\:\\__\\      ")       
print (" \\:\\  \\ /:/  / \\:\\  \\  \\/__/ \\/__\\:\\/:/  / \\:\\  \\    \\:\\  \\  \\/__/")             
print ("  \\:\\  /:/  /   \\:\\  \\            \\::/  /   \\:\\  \\    \\:\\  \\        ")           
print ("   \\:\\/:/  /     \\:\\  \\           /:/  /     \\:\\  \\    \\:\\  \\      ")            
print ("    \\::/  /       \\:\\__\\         /:/  /       \\:\\__\\    \\:\\__\\    ")             
print ("     \\/__/         \\/__/         \\/__/         \\/__/     \\/__/       ")          
print (" ")
print (" ")
print (" ____  _____  ____    __  __    __    ____  _  _  ____  ____  ___ ")
print ("( ___)(  _  )(  _ \\  (  \\/  )  /__\\  (  _ \\( )/ )( ___)(_  _)/ __)")
print (" )__)  )(_)(  )   /   )    (  /(__)\\  )   / )  (  )__)   )(  \\__ \\")
print ("(__)  (_____)(_)\\_)  (_/\\/\\_)(__)(__)(_)\\_)(_)\\_)(____) (__) (___/")
print ("This is the market edition of UCALC. It is designed for shopping stores, markets, malls, and other businesses It does not contain all the features. If you want to have more features, choose a different version. This is free software and you have the write to use, modify, and share this program with anybody")
print ("This is free, open-source software made for everyone")
print ("Version type: Android Package (.apk)")
print ("Platform: 86x64x128")
print ("(c) Copyleft, Sean Walla Walla 2015-2019")
noMore = input("Press [ENTER] key to exit")