print ("Location setup")
enterToEnter = input("Press [ENTER] key to start")
print ("Galaxy select: ")
print (" ")
print ("The milky way [1]")
galaxySelectID = int(input("ID >> "))
if (galaxySelectID == 1):
	print ("The milky way ")
	print (" ")
	print ("Mercury (0)")
	print ("Venus (1)")
	print ("Earth (2)")
	print ("Mars (3)")
	print ("Jupitor (4)")
	print ("Saturn (5)")
	print ("Uranus (6)")
	print ("Neptune (7) ")
	print ("Pluto (8)")
	planetSelectID = int(input("ID >> "))
	if (planetSelectID == 0):
		print ("Error! No destinations found on Mercury")
	if (planetSelectID == 1):
		print ("Error! No destinations found on Venus")
	if (planetSelectID == 2):
		print ("Earth ")
		print (" ")
		print ("North America (0)")
		print ("South America (1)")
		print ("Europe (2)")
		print ("Africa (3)")
		print ("Asia (4)")
		print ("Australia (5)")
		print ("Antarctica (6)")
		earthContinentSelect = int(input("ID >> "))
		if (earthContinentSelect == 0):
			print ("North America")
			print ("United States of America (0)")
			print ("Canada (1) ")
			northAmericaSelect = int(input("ID >> "))
			if (northAmericaSelect == 0):
				print ("United States of America")
				print (" ")
				print ("Alabama (1)")
				print ("Alaska (2)")
				print ("Arizona (3)")
				print ("Arkansas (4)")
				print ("California (5)")
				print ("Colorado (6)")
				print ("Connecticut (7)")
				print ("Delaware (8)")
				print ("Florida (9)")
				print ("Georgia (10)")
				print ("Hawaii (11)")
				print ("Idaho (12)")
				print ("Illinois (13)")
				print ("Indiana (14)")
				print ("Iowa (15)")
				print ("Kansas (16)")
				print ("Kentucky (17)")
				print ("Louisiana (18)")
				print ("Maine (19)")
				print ("Maryland (20)")
				print ("Massachusetts (21)")
				print ("Michigan (22)")
				print ("Minnesota (23)")
				print ("Mississippi (24)")
				print ("Missouri (25)")
				print ("Montana (26)")
				print ("Nebraska (27)")
				print ("Nevada (28)")
				print ("New Hampshire (29)")
				print ("New Jersey (30)")
				print ("New Mexico (31)")
				print ("New York (32)")
				print ("North Carolina (33)")
				print ("North Dakota (34)")
				print ("Ohio (35)")
				print ("Oklahoma (36)")
				print ("Oregon (37)")
				print ("Pennsylvania (38)")
				print ("Rhode Island (39)")
				print ("South Carolina (40)")
				print ("South Dakota (41)")
				print ("Tennessee (42)")
				print ("Texas (43)")
				print ("Utah (44)")
				print ("Vermont (45)")
				print ("Virginia (46)")
				print ("Washington (47)")
				print ("West Virginia (48)")
				print ("Wisconsin (49)")
				print ("Wyoming (50)")
				USAStateSelect = int(input("ID >> "))
				if (USAStateSelect == 1):
					print ("Alabama ")
					print (" ")
					print ("Birmingham (0)")
					print ("Mobile (1)")
					print ("Huntsville (2)")
					print ("Montgomery (3)")
					print ("Auburn (4)")
					print ("Dothan (5)")
					print ("Tuscaloosa (6)")
					print ("Gulf shores (7)")
					print ("Decatur (8)")
					print ("Hoover (9)")
					print ("Gadsden (10)")
					print ("Orange Beach (11)")
					print ("Anniston (12)")
					print ("Prattville (13)")
					print ("Opelika (19)")
					print ("Foley (20)")
					print ("Enterprise (21)")
					print ("Fairhope (22)")
					print ("Cullman (23)")
					print ("Daphne (24)")
					print ("Phenix City (25)")
					print ("Trussville (26)")
					print ("Muscle Shoals (27)")
					print ("Alabaster (28)")
					print ("Talladega (29)")
					print ("Fort Payne (30)")
					print ("Guntersville (31)")
					print ("Eufaula (32)")
					print ("Vestavia Hills (33)")
					print ("Spanish Fort (34)")
					print ("Monroeville (35)")
					print ("Sylacauga (36)")
					print ("Calera (37)")
					print ("Pelham (38)")
					print ("Demopolis (39)")
					print ("Bay minette (40)")
					print ("Tuscumbia (41)")
					print ("Tuskegee (42)")
					print ("Dauphin Island (43)")
					print ("Mountain Brook (44)")
					print ("Scottsboro (45)")
					print ("Northport (46)")
					print ("Fort Rucker (47)")
					print ("Bayou La Batre (48)")
					print ("Montevallo (49)")
					print ("Wetumpka (50)")
					print ("Gardenvale (51)")
					print ("Pell City (52)")
					print ("Clanton (53)")
					print ("Alexander City (54)")
					print ("Hartselle (55)")
				USAAlabamaSelect = int(input("ID >> "))
				if (USAStateSelect == 2):
					print ("Not yet available")
				if (USAStateSelect == 3):
					print ("Not yet available")
				if (USAStateSelect == 4):
					print ("Not yet available")
				if (USAStateSelect == 5):
					print ("Not yet available")
				if (USAStateSelect == 6):
					print ("Not yet available")
				if (USAStateSelect == 7):
					print ("Not yet available")
				if (USAStateSelect == 8):
					print ("Not yet available")
				if (USAStateSelect == 9):
					print ("Not yet available")
				if (USAStateSelect == 10):
					print ("Not yet available")
				if (USAStateSelect == 11):
					print ("Not yet available")
				if (USAStateSelect == 12):
					print ("Not yet available")
				if (USAStateSelect == 13):
					print ("Not yet available")
				if (USAStateSelect == 14):
					print ("Not yet available")
				if (USAStateSelect == 15):
					print ("Not yet available")
				if (USAStateSelect == 16):
					print ("Not yet available")
				if (USAStateSelect == 17):
					print ("Not yet available")
				if (USAStateSelect == 18):
					print ("Not yet available")
				if (USAStateSelect == 19):
					print ("Not yet available")
				if (USAStateSelect == 20):
					print ("Not yet available")
				if (USAStateSelect == 21):
					print ("Not yet available")
				if (USAStateSelect == 22):
					print ("Not yet available")
				if (USAStateSelect == 23):
					print ("Not yet available")
				if (USAStateSelect == 24):
					print ("Not yet available")
				if (USAStateSelect == 25):
					print ("Not yet available")
				if (USAStateSelect == 26):
					print ("Not yet available")
				if (USAStateSelect == 27):
					print ("Not yet available")
				if (USAStateSelect == 28):
					print ("Not yet available")
				if (USAStateSelect == 29):
					print ("Not yet available")
				if (USAStateSelect == 30):
					print ("Not yet available")
				if (USAStateSelect == 31):
					print ("Not yet available")
				if (USAStateSelect == 32):
					print ("Not yet available")
				if (USAStateSelect == 33):
					print ("Not yet available")
				if (USAStateSelect == 34):
					print ("Not yet available")
				if (USAStateSelect == 35):
					print ("Not yet available")
				if (USAStateSelect == 36):
					print ("Not yet available")
				if (USAStateSelect == 37):
					print ("Not yet available")
				if (USAStateSelect == 38):
					print ("Not yet available")
				if (USAStateSelect == 39):
					print ("Not yet available")
				if (USAStateSelect == 40):
					print ("Not yet available")
				if (USAStateSelect == 41):
					print ("Not yet available")
				if (USAStateSelect == 42):
					print ("Not yet available")
				if (USAStateSelect == 43):
					print ("Not yet available")
				if (USAStateSelect == 44):
					print ("Not yet available")
				if (USAStateSelect == 45):
					print ("Not yet available")
				if (USAStateSelect == 46):
					print ("Not yet available")
				if (USAStateSelect == 47):
					print ("Washington")
					print (" ")
					print ("Seattle (0)")
					print ("Vancouver (1)")
					print ("Spokane (2)")
					print ("Tacoma (3)")
					print ("Bellevue (4)")
					print ("Everett (5)")
					print ("Olympia (6)")
					print ("Bellingham (7)")
					print ("Yakima (8)")
					print ("Puyallup (9)")
					print ("Redmond (10)")
					print ("Leavenworth (11)")
					print ("Renton (12)")
					print ("Kennewick (13)")
					print ("Auburn (14)")
					print ("Lynnwood (15)")
					print ("Richland (16)")
					print ("Kirkland (17)")
					print ("Pasco (18)")
					print ("Federal way (19)")
					print ("Wenatchee (20)")
					print ("Bothell (21)")
					print ("Bremerton (22)")
					print ("Lacey (23)")
					print ("Walla Walla (24)")
					print ("Issaquah (25)")
					print ("Edmonds (26)")
					print ("Tri-cities (27)")
					print ("Moses lake (28)")
					print ("Port Angeles (29)")
					print ("Gig Harbor (30)")
					print ("Port Orchard (31)")
					print ("Spokane Valley (32)")
					print ("Woodinville (33)")
					print ("Tukwila (34)")
					print ("Camas (35)")
					print ("Chehalis (36)")
					print ("Sequim (37)")
					print ("Ellensburg (38)")
					print ("Anacortes (39)")
					print ("Snohomish (40)")
					print ("Port Townsend (41)")
					print ("Poulsbo (42)")
					print ("Burien (43)")
					print ("Forks (44)")
					print ("Sammamish (45)")
					print ("Bainbridge Island (46)")
					print ("Snoqualmie (47)")
					print ("George (48)")
					print ("Mercer Island (49)")
					print ("Mukilteo (50)")
					USAWashingtonSelect = int(input("ID >> "))
				if (USAStateSelect == 48):
					print ("Not yet available")
				if (USAStateSelect == 49):
					print ("Not yet available")
				if (USAStateSelect == 50):
					print ("Not yet available")
noMore = input("Press [ENTER] key to quit")